<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TenagaPendidik;

class TenagaPendidikSeeder extends Seeder
{
    public function run(): void
    {
        $tenagaPendidikData = [
            // Wali Kelas (12 orang - user_id 5-16)
            [
                'user_id' => 5,
                'nip' => '198501012010012001',
                'nama_lengkap' => 'Dewi Lestari, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1985-01-01',
                'alamat' => 'Jl. Merdeka No. 123, Jakarta Selatan',
                'telepon' => '081234567890',
                'email' => 'wali.smp.a@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Matematika',
            ],
            [
                'user_id' => 6,
                'nip' => '198702022011012002',
                'nama_lengkap' => 'Rina Wijaya, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1987-02-02',
                'alamat' => 'Jl. Sudirman No. 456, Tangerang',
                'telepon' => '081234567891',
                'email' => 'wali.sma.a@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Indonesia',
            ],
            [
                'user_id' => 7,
                'nip' => '198303032012011003',
                'nama_lengkap' => 'Hendra Kusuma, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1983-03-03',
                'alamat' => 'Jl. Raya Bogor No. 111, Bogor',
                'telepon' => '081234567892',
                'email' => 'wali.sd.a@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => 8,
                'nip' => '198904042013012004',
                'nama_lengkap' => 'Nurul Hidayah, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1989-04-04',
                'alamat' => 'Jl. Margonda No. 222, Depok',
                'telepon' => '081234567893',
                'email' => 'wali.paud.a@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],
            [
                'user_id' => 9,
                'nip' => '198105052014011005',
                'nama_lengkap' => 'Arif Budiman, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '1981-05-05',
                'alamat' => 'Jl. Ahmad Yani No. 333, Bekasi',
                'telepon' => '081234567894',
                'email' => 'wali.smp.b@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Matematika',
            ],
            [
                'user_id' => 10,
                'nip' => '198606062015012006',
                'nama_lengkap' => 'Linda Permata, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '1986-06-06',
                'alamat' => 'Jl. BSD Raya No. 444, Tangerang Selatan',
                'telepon' => '081234567895',
                'email' => 'wali.sma.b@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Inggris',
            ],
            [
                'user_id' => 11,
                'nip' => '198407072016011007',
                'nama_lengkap' => 'Rudi Hartono, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-07-07',
                'alamat' => 'Jl. Raya Jakarta No. 555, Jakarta Pusat',
                'telepon' => '081234567896',
                'email' => 'wali.sd.b@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => 12,
                'nip' => '199008082017012008',
                'nama_lengkap' => 'Mega Puspita, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-08-08',
                'alamat' => 'Jl. Pahlawan No. 666, Surabaya',
                'telepon' => '081234567897',
                'email' => 'wali.paud.b@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],
            [
                'user_id' => 13,
                'nip' => '198209092018011009',
                'nama_lengkap' => 'Faisal Rahman, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1982-09-09',
                'alamat' => 'Jl. Gatot Subroto No. 777, Medan',
                'telepon' => '081234567898',
                'email' => 'wali.smp.c@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan IPA',
            ],
            [
                'user_id' => 14,
                'nip' => '198810102019012010',
                'nama_lengkap' => 'Dian Anggraini, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-10-10',
                'alamat' => 'Jl. Malioboro No. 888, Yogyakarta',
                'telepon' => '081234567899',
                'email' => 'wali.sma.c@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Sejarah',
            ],
            [
                'user_id' => 15,
                'nip' => '198511112020011011',
                'nama_lengkap' => 'Yoga Pratama, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-11-11',
                'alamat' => 'Jl. Dago No. 999, Bandung',
                'telepon' => '081234567800',
                'email' => 'wali.sd.c@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => 16,
                'nip' => '199112122021012012',
                'nama_lengkap' => 'Lilis Suryani, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1991-12-12',
                'alamat' => 'Jl. Pandanaran No. 1010, Semarang',
                'telepon' => '081234567801',
                'email' => 'wali.paud.c@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],

            // Guru Pengajar (12 orang - user_id 17-28)
            [
                'user_id' => 17,
                'nip' => '197505052000031001',
                'nama_lengkap' => 'Prof. Andi Prasetyo, M.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1975-05-05',
                'alamat' => 'Jl. Gatot Subroto No. 789, Tangerang',
                'telepon' => '081234567802',
                'email' => 'guru.matematika@sipaduhok.com',
                'pendidikan_terakhir' => 'S2 Pendidikan Matematika',
            ],
            [
                'user_id' => 18,
                'nip' => '198003032005012001',
                'nama_lengkap' => 'Sri Mulyani, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1980-03-03',
                'alamat' => 'Jl. Ahmad Yani No. 321, Tangerang',
                'telepon' => '081234567803',
                'email' => 'guru.bahasa@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Indonesia',
            ],
            [
                'user_id' => 19,
                'nip' => '198204042007011001',
                'nama_lengkap' => 'Bambang Sutrisno, S.Si',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1982-04-04',
                'alamat' => 'Jl. Diponegoro No. 654, Tangerang',
                'telepon' => '081234567804',
                'email' => 'guru.ipa@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Biologi',
            ],
            [
                'user_id' => 20,
                'nip' => '198606062009012001',
                'nama_lengkap' => 'Ratna Sari, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1986-06-06',
                'alamat' => 'Jl. Sudirman No. 987, Tangerang',
                'telepon' => '081234567805',
                'email' => 'guru.ips@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan IPS',
            ],
            [
                'user_id' => 21,
                'nip' => '197907072003011002',
                'nama_lengkap' => 'Agus Setiawan, M.Si',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1979-07-07',
                'alamat' => 'Jl. Ijen No. 1111, Malang',
                'telepon' => '081234567806',
                'email' => 'guru.fisika@sipaduhok.com',
                'pendidikan_terakhir' => 'S2 Fisika',
            ],
            [
                'user_id' => 22,
                'nip' => '198308082008012002',
                'nama_lengkap' => 'Wulan Dari, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1983-08-08',
                'alamat' => 'Jl. Slamet Riyadi No. 1212, Solo',
                'telepon' => '081234567807',
                'email' => 'guru.kimia@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Kimia',
            ],
            [
                'user_id' => 23,
                'nip' => '198109092006011003',
                'nama_lengkap' => 'Hendro Wijaya, S.Si',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1981-09-09',
                'alamat' => 'Jl. Sudirman No. 1313, Palembang',
                'telepon' => '081234567808',
                'email' => 'guru.biologi@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Biologi',
            ],
            [
                'user_id' => 24,
                'nip' => '198710102012012003',
                'nama_lengkap' => 'Sinta Dewi, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '1987-10-10',
                'alamat' => 'Jl. Sunset Road No. 1414, Denpasar',
                'telepon' => '081234567809',
                'email' => 'guru.inggris@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Inggris',
            ],
            [
                'user_id' => 25,
                'nip' => '197811112001011004',
                'nama_lengkap' => 'Yudi Santoso, M.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1978-11-11',
                'alamat' => 'Jl. Pettarani No. 1515, Makassar',
                'telepon' => '081234567810',
                'email' => 'guru.sejarah@sipaduhok.com',
                'pendidikan_terakhir' => 'S2 Pendidikan Sejarah',
            ],
            [
                'user_id' => 26,
                'nip' => '198412122009012004',
                'nama_lengkap' => 'Ani Susanti, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '1984-12-12',
                'alamat' => 'Jl. Ahmad Yani No. 1616, Padang',
                'telepon' => '081234567811',
                'email' => 'guru.geografi@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Geografi',
            ],
            [
                'user_id' => 27,
                'nip' => '198001012004011005',
                'nama_lengkap' => 'Budi Prasetyo, S.E',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '1980-01-01',
                'alamat' => 'Jl. Gajah Mada No. 1717, Pontianak',
                'telepon' => '081234567812',
                'email' => 'guru.ekonomi@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Ekonomi',
            ],
            [
                'user_id' => 28,
                'nip' => '198602022011012005',
                'nama_lengkap' => 'Maya Kartika, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Lampung',
                'tanggal_lahir' => '1986-02-02',
                'alamat' => 'Jl. Raden Intan No. 1818, Lampung',
                'telepon' => '081234567813',
                'email' => 'guru.pkn@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Kewarganegaraan',
            ],
        ];

        foreach ($tenagaPendidikData as $tenagaPendidik) {
            TenagaPendidik::create($tenagaPendidik);
        }
    }
}