<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TenagaPendidik;
use App\Models\User;

class TenagaPendidikSeeder extends Seeder
{
    public function run(): void
    {
        // PENTING: Ambil user_id dari users berdasarkan email untuk sinkronisasi
        $getUserId = function($email) {
            return User::where('email', $email)->value('id');
        };

        $tenagaPendidikData = [
            // Wali Kelas (12 orang) - SINKRON dengan UserSeeder via EMAIL
            [
                'user_id' => $getUserId('wali.hendrakusuma@sipaduhok.com'),
                'nip' => '198303032012011003',
                'nama_lengkap' => 'Hendra Kusuma, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1983-03-03',
                'alamat' => 'Jl. Raya Bogor No. 111, Bogor',
                'telepon' => '081234567892',
                'email' => 'wali.hendrakusuma@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => $getUserId('wali.nurulhidayah@sipaduhok.com'),
                'nip' => '198904042013012004',
                'nama_lengkap' => 'Nurul Hidayah, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1989-04-04',
                'alamat' => 'Jl. Margonda No. 222, Depok',
                'telepon' => '081234567893',
                'email' => 'wali.nurulhidayah@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],
            [
                'user_id' => $getUserId('wali.arifbudiman@sipaduhok.com'),
                'nip' => '198105052014011005',
                'nama_lengkap' => 'Arif Budiman, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '1981-05-05',
                'alamat' => 'Jl. Ahmad Yani No. 333, Bekasi',
                'telepon' => '081234567894',
                'email' => 'wali.arifbudiman@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Matematika',
            ],
            [
                'user_id' => $getUserId('wali.lindapermata@sipaduhok.com'),
                'nip' => '198606062015012006',
                'nama_lengkap' => 'Linda Permata, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '1986-06-06',
                'alamat' => 'Jl. BSD Raya No. 444, Tangerang Selatan',
                'telepon' => '081234567895',
                'email' => 'wali.lindapermata@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Inggris',
            ],
            [
                'user_id' => $getUserId('wali.rudihartono@sipaduhok.com'),
                'nip' => '198407072016011007',
                'nama_lengkap' => 'Rudi Hartono, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-07-07',
                'alamat' => 'Jl. Raya Jakarta No. 555, Jakarta Pusat',
                'telepon' => '081234567896',
                'email' => 'wali.rudihartono@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => $getUserId('wali.megapuspita@sipaduhok.com'),
                'nip' => '199008082017012008',
                'nama_lengkap' => 'Mega Puspita, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-08-08',
                'alamat' => 'Jl. Pahlawan No. 666, Surabaya',
                'telepon' => '081234567897',
                'email' => 'wali.megapuspita@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],
            [
                'user_id' => $getUserId('wali.faisalrahman@sipaduhok.com'),
                'nip' => '198209092018011009',
                'nama_lengkap' => 'Faisal Rahman, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1982-09-09',
                'alamat' => 'Jl. Gatot Subroto No. 777, Medan',
                'telepon' => '081234567898',
                'email' => 'wali.faisalrahman@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan IPA',
            ],
            [
                'user_id' => $getUserId('wali.diananggraini@sipaduhok.com'),
                'nip' => '198810102019012010',
                'nama_lengkap' => 'Dian Anggraini, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-10-10',
                'alamat' => 'Jl. Malioboro No. 888, Yogyakarta',
                'telepon' => '081234567899',
                'email' => 'wali.diananggraini@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Sejarah',
            ],
            [
                'user_id' => $getUserId('wali.dewilestari@sipaduhok.com'),
                'nip' => '198501012010012001',
                'nama_lengkap' => 'Dewi Lestari, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1985-01-01',
                'alamat' => 'Jl. Merdeka No. 123, Jakarta Selatan',
                'telepon' => '081234567890',
                'email' => 'wali.dewilestari@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Matematika',
            ],
            [
                'user_id' => $getUserId('wali.lilissuryani@sipaduhok.com'),
                'nip' => '199112122021012012',
                'nama_lengkap' => 'Lilis Suryani, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1991-12-12',
                'alamat' => 'Jl. Pandanaran No. 1010, Semarang',
                'telepon' => '081234567801',
                'email' => 'wali.lilissuryani@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],
            [
                'user_id' => $getUserId('wali.yogapratama@sipaduhok.com'),
                'nip' => '198511112020011011',
                'nama_lengkap' => 'Yoga Pratama, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-11-11',
                'alamat' => 'Jl. Dago No. 999, Bandung',
                'telepon' => '081234567800',
                'email' => 'wali.yogapratama@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => $getUserId('wali.srimulyani@sipaduhok.com'),
                'nip' => '198003032005012001',
                'nama_lengkap' => 'Sri Mulyani, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1980-03-03',
                'alamat' => 'Jl. Ahmad Yani No. 321, Tangerang',
                'telepon' => '081234567803',
                'email' => 'wali.srimulyani@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Indonesia',
            ],

            // Guru Pengajar (10 orang) - SINKRON dengan UserSeeder via EMAIL
            [
                'user_id' => $getUserId('guru.bambangsutrisno@sipaduhok.com'),
                'nip' => '198204042007011001',
                'nama_lengkap' => 'Bambang Sutrisno, S.Si',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1982-04-04',
                'alamat' => 'Jl. Diponegoro No. 654, Tangerang',
                'telepon' => '081234567804',
                'email' => 'guru.bambangsutrisno@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Biologi',
            ],
            [
                'user_id' => $getUserId('guru.ratnasari@sipaduhok.com'),
                'nip' => '198606062009012001',
                'nama_lengkap' => 'Ratna Sari, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1986-06-06',
                'alamat' => 'Jl. Sudirman No. 987, Tangerang',
                'telepon' => '081234567805',
                'email' => 'guru.ratnasari@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan IPS',
            ],
            [
                'user_id' => $getUserId('guru.agussetiawan@sipaduhok.com'),
                'nip' => '197907072003011002',
                'nama_lengkap' => 'Agus Setiawan, M.Si',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1979-07-07',
                'alamat' => 'Jl. Ijen No. 1111, Malang',
                'telepon' => '081234567806',
                'email' => 'guru.agussetiawan@sipaduhok.com',
                'pendidikan_terakhir' => 'S2 Fisika',
            ],
            [
                'user_id' => $getUserId('guru.wulandari@sipaduhok.com'),
                'nip' => '198308082008012002',
                'nama_lengkap' => 'Wulan Dari, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1983-08-08',
                'alamat' => 'Jl. Slamet Riyadi No. 1212, Solo',
                'telepon' => '081234567807',
                'email' => 'guru.wulandari@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Kimia',
            ],
            [
                'user_id' => $getUserId('guru.hendrowijaya@sipaduhok.com'),
                'nip' => '198109092006011003',
                'nama_lengkap' => 'Hendro Wijaya, S.Si',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1981-09-09',
                'alamat' => 'Jl. Sudirman No. 1313, Palembang',
                'telepon' => '081234567808',
                'email' => 'guru.hendrowijaya@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Biologi',
            ],
            [
                'user_id' => $getUserId('guru.sintadewi@sipaduhok.com'),
                'nip' => '198710102012012003',
                'nama_lengkap' => 'Sinta Dewi, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '1987-10-10',
                'alamat' => 'Jl. Sunset Road No. 1414, Denpasar',
                'telepon' => '081234567809',
                'email' => 'guru.sintadewi@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Inggris',
            ],
            [
                'user_id' => $getUserId('guru.yudisantoso@sipaduhok.com'),
                'nip' => '197811112001011004',
                'nama_lengkap' => 'Yudi Santoso, M.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1978-11-11',
                'alamat' => 'Jl. Pettarani No. 1515, Makassar',
                'telepon' => '081234567810',
                'email' => 'guru.yudisantoso@sipaduhok.com',
                'pendidikan_terakhir' => 'S2 Pendidikan Sejarah',
            ],
            [
                'user_id' => $getUserId('guru.anisusanti@sipaduhok.com'),
                'nip' => '198412122009012004',
                'nama_lengkap' => 'Ani Susanti, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '1984-12-12',
                'alamat' => 'Jl. Ahmad Yani No. 1616, Padang',
                'telepon' => '081234567811',
                'email' => 'guru.anisusanti@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Geografi',
            ],
            [
                'user_id' => $getUserId('guru.budiprasetyo@sipaduhok.com'),
                'nip' => '198001012004011005',
                'nama_lengkap' => 'Budi Prasetyo, S.E',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '1980-01-01',
                'alamat' => 'Jl. Gajah Mada No. 1717, Pontianak',
                'telepon' => '081234567812',
                'email' => 'guru.budiprasetyo@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Ekonomi',
            ],
            [
                'user_id' => $getUserId('guru.mayakartika@sipaduhok.com'),
                'nip' => '198602022011012005',
                'nama_lengkap' => 'Maya Kartika, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Lampung',
                'tanggal_lahir' => '1986-02-02',
                'alamat' => 'Jl. Raden Intan No. 1818, Lampung',
                'telepon' => '081234567813',
                'email' => 'guru.mayakartika@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Kewarganegaraan',
            ],

            // Staff Struktural (3 orang) - SINKRON dengan UserSeeder via EMAIL
            [
                'user_id' => $getUserId('ketua@sipaduhok.com'),
                'nip' => '197501012000011001',
                'nama_lengkap' => 'Dr. Budi Santoso, M.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1975-01-01',
                'alamat' => 'Jl. Pendidikan No. 1, Jakarta',
                'telepon' => '081234567888',
                'email' => 'ketua@sipaduhok.com',
                'pendidikan_terakhir' => 'S3 Manajemen Pendidikan',
            ],
            [
                'user_id' => $getUserId('sekretaris@sipaduhok.com'),
                'nip' => '198001012005012001',
                'nama_lengkap' => 'Siti Nurhaliza, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1980-01-01',
                'alamat' => 'Jl. Administrasi No. 2, Tangerang',
                'telepon' => '081234567889',
                'email' => 'sekretaris@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Administrasi Pendidikan',
            ],
            [
                'user_id' => $getUserId('bendahara@sipaduhok.com'),
                'nip' => '197805052003011001',
                'nama_lengkap' => 'Ahmad Dahlan, S.E',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1978-05-05',
                'alamat' => 'Jl. Ekonomi No. 3, Tangerang',
                'telepon' => '081234567887',
                'email' => 'bendahara@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Ekonomi',
            ],
        ];

        foreach ($tenagaPendidikData as $tenagaPendidik) {
            TenagaPendidik::create($tenagaPendidik);
        }
    }
}