<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TenagaPendidik;
use App\Models\User;

class TenagaPendidikSeeder extends Seeder
{
    public function run(): void
    {
        // PENTING: Ambil user_id dari users berdasarkan email untuk sinkronisasi
        // Return null jika tidak ditemukan (skip record tersebut)
        $getUserId = function($email) {
            return User::where('email', $email)->value('id');
        };

        $tenagaPendidikData = [
            // Wali Kelas - Data asli (4 orang)
            [
                'user_id' => $getUserId('walidelia@sipaduhok.com'),
                'nip' => '199001012020012001',
                'nama_lengkap' => 'Delia Parsauliani S.K.M.',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'alamat' => 'Jl. Pendidikan No. 1, Jakarta',
                'telepon' => '081234567890',
                'email' => 'walidelia@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Kesehatan Masyarakat',
            ],
            [
                'user_id' => $getUserId('walicharol@sipaduhok.com'),
                'nip' => '199102022020012002',
                'nama_lengkap' => 'Charoline Revlecya S. Mat.',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1991-02-02',
                'alamat' => 'Jl. Pendidikan No. 2, Bandung',
                'telepon' => '081234567891',
                'email' => 'walicharol@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Matematika',
            ],
            [
                'user_id' => $getUserId('walidyah@sipaduhok.com'),
                'nip' => '199203032020012003',
                'nama_lengkap' => 'Dyah Yossie S. I. Kom,',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1992-03-03',
                'alamat' => 'Jl. Pendidikan No. 3, Surabaya',
                'telepon' => '081234567892',
                'email' => 'walidyah@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Ilmu Komunikasi',
            ],
            [
                'user_id' => $getUserId('walihiskia@sipaduhok.com'),
                'nip' => '199304042020011004',
                'nama_lengkap' => 'Hiskia Oktaviandri',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1993-04-04',
                'alamat' => 'Jl. Pendidikan No. 4, Depok',
                'telepon' => '081234567893',
                'email' => 'walihiskia@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan',
            ],

            // Wali Kelas - Data dummy (8 orang) - SINKRON dengan UserSeeder
            [
                'user_id' => $getUserId('wali.rudihartono@sipaduhok.com'),
                'nip' => '198407072016011007',
                'nama_lengkap' => 'Rudi Hartono, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-07-07',
                'alamat' => 'Jl. Raya Jakarta No. 555, Jakarta Pusat',
                'telepon' => '081234567896',
                'email' => 'wali.rudihartono@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => $getUserId('wali.megapuspita@sipaduhok.com'),
                'nip' => '199008082017012008',
                'nama_lengkap' => 'Mega Puspita, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-08-08',
                'alamat' => 'Jl. Pahlawan No. 666, Surabaya',
                'telepon' => '081234567897',
                'email' => 'wali.megapuspita@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],
            [
                'user_id' => $getUserId('wali.faisalrahman@sipaduhok.com'),
                'nip' => '198209092018011009',
                'nama_lengkap' => 'Faisal Rahman, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1982-09-09',
                'alamat' => 'Jl. Gatot Subroto No. 777, Medan',
                'telepon' => '081234567898',
                'email' => 'wali.faisalrahman@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan IPA',
            ],
            [
                'user_id' => $getUserId('wali.diananggraini@sipaduhok.com'),
                'nip' => '198810102019012010',
                'nama_lengkap' => 'Dian Anggraini, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-10-10',
                'alamat' => 'Jl. Malioboro No. 888, Yogyakarta',
                'telepon' => '081234567899',
                'email' => 'wali.diananggraini@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Sejarah',
            ],
            [
                'user_id' => $getUserId('wali.dewilestari@sipaduhok.com'),
                'nip' => '198501012010012001',
                'nama_lengkap' => 'Dewi Lestari, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1985-01-01',
                'alamat' => 'Jl. Merdeka No. 123, Jakarta Selatan',
                'telepon' => '081234567890',
                'email' => 'wali.dewilestari@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Matematika',
            ],
            [
                'user_id' => $getUserId('wali.lilissuryani@sipaduhok.com'),
                'nip' => '199112122021012012',
                'nama_lengkap' => 'Lilis Suryani, S.Paud',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1991-12-12',
                'alamat' => 'Jl. Pandanaran No. 1010, Semarang',
                'telepon' => '081234567801',
                'email' => 'wali.lilissuryani@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Anak Usia Dini',
            ],
            [
                'user_id' => $getUserId('wali.yogapratama@sipaduhok.com'),
                'nip' => '198511112020011011',
                'nama_lengkap' => 'Yoga Pratama, S.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-11-11',
                'alamat' => 'Jl. Dago No. 999, Bandung',
                'telepon' => '081234567800',
                'email' => 'wali.yogapratama@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Guru SD',
            ],
            [
                'user_id' => $getUserId('wali.srimulyani@sipaduhok.com'),
                'nip' => '198003032005012001',
                'nama_lengkap' => 'Sri Mulyani, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1980-03-03',
                'alamat' => 'Jl. Ahmad Yani No. 321, Tangerang',
                'telepon' => '081234567803',
                'email' => 'wali.srimulyani@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Indonesia',
            ],

            // Guru Pengajar - Data asli (5 orang)
            [
                'user_id' => $getUserId('guruberliana@sipaduhok.com'),
                'nip' => '199501012021012001',
                'nama_lengkap' => 'IrenT Berliana Agustin',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1995-01-01',
                'alamat' => 'Jl. Pendidikan No. 5, Jakarta',
                'telepon' => '081234567894',
                'email' => 'guruberliana@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan',
            ],
            [
                'user_id' => $getUserId('gurudelia@sipaduhok.com'),
                'nip' => '199002022021012002',
                'nama_lengkap' => 'Delia Parsauliani S.K.M.',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-02-02',
                'alamat' => 'Jl. Pendidikan No. 6, Jakarta',
                'telepon' => '081234567895',
                'email' => 'gurudelia@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Kesehatan Masyarakat',
            ],
            [
                'user_id' => $getUserId('gurucharol@sipaduhok.com'),
                'nip' => '199103032021012003',
                'nama_lengkap' => 'Charoline Revlecya S. Mat.',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1991-03-03',
                'alamat' => 'Jl. Pendidikan No. 7, Bandung',
                'telepon' => '081234567896',
                'email' => 'gurucharol@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Matematika',
            ],
            [
                'user_id' => $getUserId('gurudyah@sipaduhok.com'),
                'nip' => '199204042021012004',
                'nama_lengkap' => 'Dyah Yossie S. I. Kom,',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1992-04-04',
                'alamat' => 'Jl. Pendidikan No. 8, Surabaya',
                'telepon' => '081234567897',
                'email' => 'gurudyah@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Ilmu Komunikasi',
            ],
            [
                'user_id' => $getUserId('guruhiskia@sipaduhok.com'),
                'nip' => '199305052021011005',
                'nama_lengkap' => 'Hiskia Oktaviandri',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1993-05-05',
                'alamat' => 'Jl. Pendidikan No. 9, Depok',
                'telepon' => '081234567898',
                'email' => 'guruhiskia@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan',
            ],

            // Wakil Kepala Sekolah (Missing)
            [
                'user_id' => $getUserId('wakacharol@sipaduhok.com'),
                'nip' => '199103032021012011',
                'nama_lengkap' => 'Charoline Revlecya S. Mat',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1991-03-03',
                'alamat' => 'Jl. Pahlawan No. 1, Bandung',
                'telepon' => '081234567881',
                'email' => 'wakacharol@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Matematika',
            ],
            [
                'user_id' => $getUserId('wakadelia@sipaduhok.com'),
                'nip' => '199001012021012012',
                'nama_lengkap' => 'Delia Parsauliani S.K.M.',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'alamat' => 'Jl. Pahlawan No. 2, Jakarta',
                'telepon' => '081234567882',
                'email' => 'wakadelia@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Kesehatan Masyarakat',
            ],
            [
                'user_id' => $getUserId('wakameini@sipaduhok.com'),
                'nip' => '198505052010012013',
                'nama_lengkap' => 'Meini',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1985-05-05',
                'alamat' => 'Jl. Pahlawan No. 3, Medan',
                'telepon' => '081234567883',
                'email' => 'wakameini@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan',
            ],
            [
                'user_id' => $getUserId('wakanurul@sipaduhok.com'),
                'nip' => '198808082015012014',
                'nama_lengkap' => 'Eka Nurul',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1988-08-08',
                'alamat' => 'Jl. Pahlawan No. 4, Surabaya',
                'telepon' => '081234567884',
                'email' => 'wakanurul@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan',
            ],

            // Guru Pengajar - Data dummy (5 orang)
            [
                'user_id' => $getUserId('guru.sintadewi@sipaduhok.com'),
                'nip' => '198710102012012003',
                'nama_lengkap' => 'Sinta Dewi, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '1987-10-10',
                'alamat' => 'Jl. Sunset Road No. 1414, Denpasar',
                'telepon' => '081234567809',
                'email' => 'guru.sintadewi@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Bahasa Inggris',
            ],
            [
                'user_id' => $getUserId('guru.yudisantoso@sipaduhok.com'),
                'nip' => '197811112001011004',
                'nama_lengkap' => 'Yudi Santoso, M.Pd',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1978-11-11',
                'alamat' => 'Jl. Pettarani No. 1515, Makassar',
                'telepon' => '081234567810',
                'email' => 'guru.yudisantoso@sipaduhok.com',
                'pendidikan_terakhir' => 'S2 Pendidikan Sejarah',
            ],
            [
                'user_id' => $getUserId('guru.anisusanti@sipaduhok.com'),
                'nip' => '198412122009012004',
                'nama_lengkap' => 'Ani Susanti, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '1984-12-12',
                'alamat' => 'Jl. Ahmad Yani No. 1616, Padang',
                'telepon' => '081234567811',
                'email' => 'guru.anisusanti@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Geografi',
            ],
            [
                'user_id' => $getUserId('guru.budiprasetyo@sipaduhok.com'),
                'nip' => '198001012004011005',
                'nama_lengkap' => 'Budi Prasetyo, S.E',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '1980-01-01',
                'alamat' => 'Jl. Gajah Mada No. 1717, Pontianak',
                'telepon' => '081234567812',
                'email' => 'guru.budiprasetyo@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Ekonomi',
            ],
            [
                'user_id' => $getUserId('guru.mayakartika@sipaduhok.com'),
                'nip' => '198602022011012005',
                'nama_lengkap' => 'Maya Kartika, S.Pd',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Lampung',
                'tanggal_lahir' => '1986-02-02',
                'alamat' => 'Jl. Raden Intan No. 1818, Lampung',
                'telepon' => '081234567813',
                'email' => 'guru.mayakartika@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Pendidikan Kewarganegaraan',
            ],

            // Staff Struktural - Data asli
            [
                'user_id' => $getUserId('ketuafransisda@sipaduhok.com'),
                'nip' => '197501012000011001',
                'nama_lengkap' => 'Fransisda Tiodora Ferdiansyah S. Psi., M. M., Psikolog',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1975-01-01',
                'alamat' => 'Jl. Pendidikan No. 1, Jakarta',
                'telepon' => '081234567888',
                'email' => 'ketuafransisda@sipaduhok.com',
                'pendidikan_terakhir' => 'S2 Manajemen, Psikolog',
            ],
            [
                'user_id' => $getUserId('sekredelia@sipaduhok.com'),
                'nip' => '198001012005012001',
                'nama_lengkap' => 'Delia Parsauliani S. K. M.',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'alamat' => 'Jl. Administrasi No. 2, Tangerang',
                'telepon' => '081234567889',
                'email' => 'sekredelia@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Kesehatan Masyarakat',
            ],
            [
                'user_id' => $getUserId('bendaharalinawati@sipaduhok.com'),
                'nip' => '197805052003011001',
                'nama_lengkap' => 'Linawati Rozali',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1978-05-05',
                'alamat' => 'Jl. Ekonomi No. 3, Tangerang',
                'telepon' => '081234567887',
                'email' => 'bendaharalinawati@sipaduhok.com',
                'pendidikan_terakhir' => 'S1 Ekonomi',
            ],
        ];

        foreach ($tenagaPendidikData as $tenagaPendidik) {
            // Skip jika user_id null (user tidak ditemukan)
            if ($tenagaPendidik['user_id'] !== null) {
                TenagaPendidik::create($tenagaPendidik);
            }
        }
    }
}