@php
    $returnUrl = $isEdit ? url()->previous(route('admin.cabang.index')) : route('admin.cabang.index');
    $formAction = $isEdit ? route('admin.cabang.update', $cabang) : route('admin.cabang.store');
    $fieldClass = 'mt-1.5 h-11 w-full rounded-xl border bg-white px-3 text-sm text-slate-800 outline-none transition focus:ring-2';
    if ($isEdit) {
        $siswaCount = \App\Models\Siswa::where('cabang_id', $cabang->id)->count();
        $kelasCount = \App\Models\Kelas::where('cabang_id', $cabang->id)->count();
        $userCount = \App\Models\User::where('cabang_id', $cabang->id)->where('role', '!=', 'siswa')->count();
    }
@endphp

<div class="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="flex items-center justify-between gap-3 border-b border-slate-200 p-4 sm:p-5"><div><h2 class="text-base font-extrabold text-slate-900"><i class="fas fa-building mr-2 text-brand-600" aria-hidden="true"></i>{{ $isEdit ? 'Ubah Data Cabang' : 'Data Cabang Baru' }}</h2><p class="mt-1 text-xs text-slate-500">Informasi ini dipakai pada data siswa, kelas, dan tenaga pendidik.</p></div><a href="{{ $returnUrl }}" class="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-xl bg-slate-100 px-3 text-xs font-bold text-slate-700 no-underline hover:bg-slate-200"><i class="fas fa-arrow-left" aria-hidden="true"></i><span class="hidden sm:inline">Kembali</span></a></header>
        <form action="{{ $formAction }}" method="POST">@csrf @if($isEdit) @method('PUT') <input type="hidden" name="_return_url" value="{{ $returnUrl }}"> @endif
            <div class="space-y-6 p-4 sm:p-5">
                <section><h3 class="text-xs font-extrabold uppercase tracking-wide text-slate-500">Informasi Dasar</h3><div class="mt-3 grid gap-4 sm:grid-cols-2"><label class="block"><span class="text-xs font-bold text-slate-700">Kode Cabang <span class="text-red-500">*</span></span><input type="text" name="kode_cabang" value="{{ old('kode_cabang', $cabang?->kode_cabang) }}" maxlength="10" placeholder="Contoh: RUKO" required class="uppercase {{ $fieldClass }} {{ $errors->has('kode_cabang') ? 'border-red-400 focus:border-red-500 focus:ring-red-500/20' : 'border-slate-200 focus:border-brand-500 focus:ring-brand-500/20' }}">@error('kode_cabang')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror<p class="mt-1 text-[11px] text-slate-500">Maksimal 10 huruf/angka; akan disimpan kapital.</p></label><label class="block"><span class="text-xs font-bold text-slate-700">Nama Cabang <span class="text-red-500">*</span></span><input type="text" name="nama_cabang" value="{{ old('nama_cabang', $cabang?->nama_cabang) }}" placeholder="Contoh: PKBM HOK - Ruko" required class="{{ $fieldClass }} {{ $errors->has('nama_cabang') ? 'border-red-400 focus:border-red-500 focus:ring-red-500/20' : 'border-slate-200 focus:border-brand-500 focus:ring-brand-500/20' }}">@error('nama_cabang')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label></div></section>
                <section class="border-t border-slate-100 pt-5"><h3 class="text-xs font-extrabold uppercase tracking-wide text-slate-500">Lokasi & Kontak</h3><div class="mt-3 grid gap-4 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="text-xs font-bold text-slate-700">Alamat Lengkap <span class="text-red-500">*</span></span><textarea name="alamat" rows="4" placeholder="Masukkan alamat lengkap cabang..." required class="mt-1.5 w-full resize-y rounded-xl border bg-white px-3 py-3 text-sm text-slate-800 outline-none transition focus:ring-2 {{ $errors->has('alamat') ? 'border-red-400 focus:border-red-500 focus:ring-red-500/20' : 'border-slate-200 focus:border-brand-500 focus:ring-brand-500/20' }}">{{ old('alamat', $cabang?->alamat) }}</textarea>@error('alamat')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label><label class="block"><span class="text-xs font-bold text-slate-700">Nomor Telepon</span><input type="text" name="telepon" value="{{ old('telepon', $cabang?->telepon) }}" placeholder="Contoh: (021) 12345678" class="{{ $fieldClass }} {{ $errors->has('telepon') ? 'border-red-400 focus:border-red-500 focus:ring-red-500/20' : 'border-slate-200 focus:border-brand-500 focus:ring-brand-500/20' }}">@error('telepon')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror<p class="mt-1 text-[11px] text-slate-500">Opsional.</p></label><label class="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><input type="checkbox" name="is_active" value="1" {{ old('is_active', $cabang?->is_active ?? true) ? 'checked' : '' }} class="mt-0.5 h-5 w-5 rounded border-slate-300 text-brand-600 focus:ring-brand-500"><span><strong class="block text-sm text-slate-900">Cabang aktif</strong><span class="mt-1 block text-[11px] leading-4 text-slate-500">Dapat menerima siswa dan dipilih pada data baru.</span></span></label></div></section>
            </div>
            <footer class="flex items-center justify-between gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3 sm:px-5"><div>@if($isEdit)<a href="{{ route('admin.cabang.show', $cabang) }}" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl px-3 text-xs font-bold text-slate-600 no-underline hover:bg-slate-200"><i class="fas fa-eye" aria-hidden="true"></i><span class="hidden sm:inline">Lihat Detail</span></a>@endif</div><div class="flex gap-2"><a href="{{ $returnUrl }}" class="inline-flex h-10 items-center justify-center rounded-xl px-4 text-xs font-bold text-slate-600 no-underline hover:bg-slate-200">Batal</a><button type="submit" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 text-xs font-bold text-white hover:bg-brand-700"><i class="fas fa-save" aria-hidden="true"></i>{{ $isEdit ? 'Simpan Perubahan' : 'Simpan Cabang' }}</button></div></footer>
        </form>
    </section>

    <aside class="space-y-4">
        @if($isEdit)
            <section class="grid grid-cols-3 gap-2">@foreach([['value' => $siswaCount, 'label' => 'Siswa', 'tone' => 'text-blue-700'], ['value' => $kelasCount, 'label' => 'Kelas', 'tone' => 'text-emerald-700'], ['value' => $userCount, 'label' => 'Pendidik', 'tone' => 'text-violet-700']] as $stat)<article class="rounded-xl border border-slate-200 bg-white p-3 text-center shadow-sm"><p class="text-lg font-extrabold {{ $stat['tone'] }}">{{ $stat['value'] }}</p><p class="mt-1 text-[10px] text-slate-500">{{ $stat['label'] }}</p></article>@endforeach</section>
            <section class="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h2 class="text-sm font-extrabold text-amber-900"><i class="fas fa-exclamation-triangle mr-1.5" aria-hidden="true"></i>Data Terhubung</h2><p class="mt-2 text-xs leading-5 text-amber-800">Perubahan nama atau status cabang akan tampil pada semua data terkait. ID dan relasi data tidak berubah.</p></section>
        @else
            <section class="rounded-2xl border border-blue-200 bg-blue-50 p-4"><h2 class="text-sm font-extrabold text-blue-900"><i class="fas fa-route mr-1.5" aria-hidden="true"></i>Urutan Persiapan</h2><ol class="mt-3 space-y-2 text-xs leading-5 text-blue-900"><li class="opacity-70">1. Aktifkan tahun ajaran</li><li><strong>2. Tambahkan cabang</strong></li><li>3. Masukkan pengguna</li><li>4. Buat kelas</li><li>5. Susun mata pelajaran dan jadwal</li></ol></section>
        @endif
        <section class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="text-sm font-extrabold text-slate-900"><i class="fas fa-lightbulb mr-1.5 text-amber-500" aria-hidden="true"></i>Tips</h2><ul class="mt-2 list-disc space-y-1 pl-4 text-xs leading-5 text-slate-600"><li>Gunakan kode yang pendek dan mudah dikenali.</li><li>Pastikan alamat cukup lengkap untuk laporan.</li><li>Nonaktifkan cabang lama tanpa menghapus riwayat.</li></ul></section>
    </aside>
</div>
