@extends('layouts.app')
@section('title', 'Wali Kelas')
@section('page-title', 'Penugasan Wali Kelas')
@section('page-subtitle', 'Pastikan setiap kelas memiliki pendamping yang jelas')

@section('content')
<div class="min-w-0 w-full space-y-4" x-data="{ assignment: { action: '', title: '', current: '' }, waliSearch: '', openAssignment(data) { this.assignment = data; this.waliSearch = ''; this.$refs.assignmentDialog.showModal(); } }">
    <section class="grid grid-cols-2 gap-3 xl:grid-cols-4">@foreach([['Total kelas',$stats['totalKelas'],'fa-school','blue'],['Sudah ada wali',$stats['kelasWithWali'],'fa-user-check','emerald'],['Belum ada wali',$stats['kelasWithoutWali'],'fa-user-clock','amber'],['Wali aktif',$stats['totalWaliKelas'],'fa-users','violet']] as [$label,$value,$icon,$tone])<article class="flex min-w-0 items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span @class(['flex h-11 w-11 shrink-0 items-center justify-center rounded-xl','bg-blue-50 text-blue-600'=>$tone==='blue','bg-emerald-50 text-emerald-600'=>$tone==='emerald','bg-amber-50 text-amber-600'=>$tone==='amber','bg-violet-50 text-violet-600'=>$tone==='violet'])><i class="fas {{ $icon }}"></i></span><div><p class="text-2xl font-extrabold text-slate-950">{{ $value }}</p><p class="text-[10px] font-bold uppercase tracking-wide text-slate-500">{{ $label }}</p></div></article>@endforeach</section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 px-4 py-4 sm:px-5"><div><h2 class="text-lg font-extrabold text-slate-950"><i class="fas fa-user-shield mr-2 text-brand-600"></i>Daftar kelas dan wali</h2><p class="mt-1 text-xs text-slate-500">Pilih kelas untuk menambah atau melepas wali kelas.</p></div><a href="{{ route('admin.wali-kelas.print',request()->query()) }}" target="_blank" class="inline-flex min-h-10 items-center gap-2 rounded-xl bg-slate-100 px-4 text-xs font-bold text-slate-700 no-underline hover:bg-slate-200"><i class="fas fa-print"></i>Cetak</a></header>
        <form action="{{ route('admin.wali-kelas.index') }}" method="GET" class="grid gap-2 border-b border-slate-200 px-4 py-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_190px_150px_190px_160px_auto] sm:px-5"><label class="relative"><i class="fas fa-search absolute left-3.5 top-3.5 text-xs text-slate-400"></i><input type="search" name="search" value="{{ request('search') }}" class="h-11 w-full rounded-xl border border-slate-300 !pl-10 pr-3 text-sm outline-none focus:border-brand-500" placeholder="Cari kelas atau wali..."></label><select name="tahun_ajaran_id" @change="$el.form.submit()" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Semua periode</option>@foreach($tahunAjarans as $tahun)<option value="{{ $tahun->id }}" @selected((string)request('tahun_ajaran_id',$currentTahunAjaran?->id)===(string)$tahun->id)>{{ $tahun->nama_tahun_ajaran }}</option>@endforeach</select><select name="jenjang" @change="$el.form.submit()" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Semua jenjang</option>@foreach($jenjangs as $jenjang)<option value="{{ $jenjang }}" @selected(request('jenjang')===$jenjang)>{{ $jenjang }}</option>@endforeach</select><select name="cabang_id" @change="$el.form.submit()" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Semua cabang</option>@foreach($cabangs as $cabang)<option value="{{ $cabang->id }}" @selected((string)request('cabang_id')===(string)$cabang->id)>{{ $cabang->nama_cabang }}</option>@endforeach</select><select name="status" @change="$el.form.submit()" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Semua status</option><option value="assigned" @selected(request('status')==='assigned')>Sudah ada wali</option><option value="unassigned" @selected(request('status')==='unassigned')>Belum ada wali</option></select><button class="h-11 rounded-xl bg-slate-800 px-4 text-xs font-bold text-white">Cari</button></form>
        @if($kelasList->isEmpty())<div class="px-5 py-14 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-50 text-xl text-brand-600"><i class="fas fa-school-circle-xmark"></i></span><h3 class="mt-4 font-extrabold text-slate-950">Kelas tidak ditemukan</h3><p class="mt-1 text-sm text-slate-500">Ubah filter atau buat data kelas terlebih dahulu.</p></div>@else
<div class="grid gap-3 p-3 md:hidden">@foreach($kelasList as $kelas)<article class="rounded-2xl border border-slate-200 p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h3 class="truncate font-extrabold text-slate-950">{{ $kelas->nama_kelas }} <span class="text-xs text-slate-400">{{ $kelas->jenjang }}</span></h3><p class="mt-1 truncate text-xs text-slate-500">{{ $kelas->cabang->nama_cabang }} · {{ $kelas->siswa_count }} siswa</p></div><span @class(['rounded-full px-2 py-1 text-[10px] font-bold','bg-emerald-50 text-emerald-700'=>$kelas->waliKelasAssignments->isNotEmpty(),'bg-amber-50 text-amber-700'=>$kelas->waliKelasAssignments->isEmpty()])>{{ $kelas->waliKelasAssignments->isNotEmpty() ? 'Ada wali' : 'Belum ada' }}</span></div><p class="mt-3 truncate text-sm font-bold text-slate-700">{{ $kelas->waliKelasAssignments->pluck('tenagaPendidik.nama_lengkap')->join(', ') ?: 'Wali belum ditentukan' }}</p><button type="button" @click="openAssignment(@js(['action' => route('admin.wali-kelas.assign', $kelas), 'title' => $kelas->nama_kelas.' · '.$kelas->cabang->nama_cabang, 'current' => $kelas->waliKelasAssignments->pluck('tenagaPendidik.nama_lengkap')->join(', ')]))" class="mt-3 inline-flex min-h-9 w-full items-center justify-center gap-2 rounded-xl bg-brand-600 text-xs font-bold text-white"><i class="fas fa-user-plus"></i>Atur wali di sini</button></article>@endforeach</div>
        <div class="hidden overflow-x-auto md:block"><table class="w-full table-fixed text-left"><colgroup><col class="w-14"><col class="w-[20%]"><col class="w-[22%]"><col><col class="w-24"><col class="w-28"><col class="w-20"></colgroup><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-3 py-3">No</th><th class="px-3 py-3">Kelas</th><th class="px-3 py-3">Cabang</th><th class="px-3 py-3">Wali kelas</th><th class="px-3 py-3">Siswa</th><th class="px-3 py-3">Status</th><th class="px-3 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($kelasList as $kelas)<tr class="hover:bg-slate-50"><td class="px-3 py-4 text-xs text-slate-500">{{ $kelasList->firstItem()+$loop->index }}</td><td class="px-3 py-4"><strong class="block truncate text-sm text-slate-950">{{ $kelas->nama_kelas }}</strong><span class="text-xs text-slate-500">{{ $kelas->jenjang }}</span></td><td class="px-3 py-4"><p class="truncate text-xs text-slate-600" title="{{ $kelas->cabang->nama_cabang }}">{{ $kelas->cabang->nama_cabang }}</p></td><td class="px-3 py-4"><p class="truncate text-xs font-bold text-slate-700" title="{{ $kelas->waliKelasAssignments->pluck('tenagaPendidik.nama_lengkap')->join(', ') }}">{{ $kelas->waliKelasAssignments->pluck('tenagaPendidik.nama_lengkap')->join(', ') ?: 'Belum ditentukan' }}</p></td><td class="px-3 py-4 text-xs font-bold text-slate-700">{{ $kelas->siswa_count }}</td><td class="px-3 py-4"><span @class(['whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-bold','bg-emerald-50 text-emerald-700'=>$kelas->waliKelasAssignments->isNotEmpty(),'bg-amber-50 text-amber-700'=>$kelas->waliKelasAssignments->isEmpty()])>{{ $kelas->waliKelasAssignments->isNotEmpty() ? 'Ditugaskan' : 'Belum ada' }}</span></td><td class="px-3 py-4"><div class="flex justify-end"><button type="button" aria-label="Atur wali kelas" @click="openAssignment(@js(['action' => route('admin.wali-kelas.assign', $kelas), 'title' => $kelas->nama_kelas.' · '.$kelas->cabang->nama_cabang, 'current' => $kelas->waliKelasAssignments->pluck('tenagaPendidik.nama_lengkap')->join(', ')]))" class="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-100 hover:bg-blue-100"><i class="fas fa-user-plus"></i></button></div></td></tr>@endforeach</tbody></table></div><div class="border-t border-slate-200 px-4 py-3">{{ $kelasList->withQueryString()->links() }}</div>@endif
    </section>

<dialog x-ref="assignmentDialog" class="w-[min(94vw,640px)] max-h-[92vh] overflow-y-auto rounded-2xl border-0 p-0 shadow-2xl backdrop:bg-slate-950/55">
        <form :action="assignment.action" method="POST">
            @csrf
            <header class="flex items-start justify-between gap-3 border-b border-slate-200 px-4 py-4 sm:px-5"><div><p class="text-[10px] font-bold uppercase tracking-wide text-brand-600">Penugasan cepat</p><h3 class="mt-1 font-extrabold text-slate-950" x-text="assignment.title"></h3><p class="mt-1 text-xs text-slate-500">Saat ini: <span class="font-semibold" x-text="assignment.current || 'Belum ada wali kelas'"></span></p></div><button type="button" @click="$refs.assignmentDialog.close()" class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600" aria-label="Tutup"><i class="fas fa-times"></i></button></header>
            <div class="space-y-3 p-4 sm:p-5"><label class="relative block"><span class="sr-only">Cari calon wali kelas</span><i class="fas fa-search pointer-events-none absolute left-3.5 top-3.5 text-xs text-slate-400"></i><input type="search" x-model="waliSearch" class="h-11 w-full rounded-xl border border-slate-300 !pl-10 pr-3 text-sm outline-none focus:border-brand-500" placeholder="Cari nama wali kelas..."></label><div class="max-h-72 space-y-2 overflow-y-auto pr-1">@foreach($waliKelasOptions as $wali)<label x-show="!waliSearch || @js(strtolower($wali->nama_lengkap.' '.($wali->user->cabang->nama_cabang ?? ''))).includes(waliSearch.toLowerCase())" class="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50 has-[:checked]:border-brand-500 has-[:checked]:bg-brand-50"><input type="radio" name="wali_kelas_id" value="{{ $wali->id }}" required class="h-4 w-4 border-slate-300 text-brand-600"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-xs font-extrabold text-violet-700">{{ strtoupper(substr($wali->nama_lengkap, 0, 1)) }}</span><span class="min-w-0 flex-1"><strong class="block truncate text-sm text-slate-900">{{ $wali->nama_lengkap }}</strong><span class="block truncate text-xs text-slate-500">{{ $wali->user->cabang->nama_cabang ?? 'Semua cabang' }} · {{ $wali->waliKelasAssignments->count() }} kelas</span></span></label>@endforeach</div><p class="rounded-xl bg-blue-50 p-3 text-xs leading-5 text-blue-800"><i class="fas fa-circle-info mr-1"></i>Penugasan baru akan ditambahkan. Wali yang sudah aktif tidak otomatis dilepas.</p></div>
            <footer class="flex flex-wrap items-center justify-between gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3 sm:px-5"><a :href="assignment.action.replace('/assign', '')" class="text-xs font-bold text-brand-700 no-underline">Kelola wali aktif</a><div class="flex gap-2"><button type="button" @click="$refs.assignmentDialog.close()" class="h-10 px-4 text-xs font-bold text-slate-600">Batal</button><button type="submit" class="h-10 rounded-xl bg-brand-600 px-4 text-xs font-bold text-white">Tambahkan wali</button></div></footer>
        </form>
    </dialog>
</div>
@endsection
