@extends('layouts.app')
@section('title', 'Wali Kelas ' . $kelas->nama_kelas)
@section('page-title', 'Atur Wali Kelas')
@section('page-subtitle', 'Kelola pendamping dan lihat anggota ' . $kelas->nama_kelas)

@section('content')
<div class="min-w-0 w-full space-y-4"><header class="flex flex-wrap items-start justify-between gap-3"><div class="flex min-w-0 items-start gap-3"><a href="{{ route('admin.wali-kelas.index',['tahun_ajaran_id'=>$kelas->tahun_ajaran_id]) }}" class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 no-underline"><i class="fas fa-arrow-left"></i></a><div><p class="text-xs font-bold uppercase tracking-wide text-brand-600">Wali kelas</p><h2 class="text-xl font-extrabold text-slate-950 sm:text-2xl">{{ $kelas->nama_kelas }}</h2><p class="mt-1 text-sm text-slate-500">{{ $kelas->cabang->nama_cabang }} · {{ $kelas->jenjang }} · {{ $kelas->tahunAjaran->nama_tahun_ajaran }}</p></div></div><a href="{{ route('admin.kelas.show',$kelas) }}" class="inline-flex min-h-10 items-center gap-2 rounded-xl bg-slate-100 px-4 text-xs font-bold text-slate-700 no-underline"><i class="fas fa-school"></i>Detail kelas</a></header>
<section class="grid grid-cols-3 gap-3">@foreach([['Siswa',$stats['totalSiswa'],'fa-users','blue'],['Laki-laki',$stats['siswaLaki'],'fa-mars','cyan'],['Perempuan',$stats['siswaPerempuan'],'fa-venus','pink']] as [$label,$value,$icon,$tone])<article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><i @class(['fas',$icon,'text-blue-600'=>$tone==='blue','text-cyan-600'=>$tone==='cyan','text-pink-600'=>$tone==='pink'])></i><p class="mt-2 text-2xl font-extrabold text-slate-950">{{ $value }}</p><p class="text-[10px] font-bold uppercase text-slate-500">{{ $label }}</p></article>@endforeach</section>
<div class="grid min-w-0 gap-4 xl:grid-cols-[minmax(300px,.8fr)_minmax(0,1.2fr)]"><div class="space-y-4"><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 px-4 py-4"><h3 class="font-extrabold text-slate-950">Wali yang bertugas</h3><p class="mt-1 text-xs text-slate-500">Satu kelas dapat memiliki lebih dari satu wali.</p></header><div class="divide-y divide-slate-100">@forelse($kelas->waliKelasAssignments as $assignment)<article class="flex items-center gap-3 px-4 py-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-xs font-extrabold text-brand-700">{{ strtoupper(substr($assignment->tenagaPendidik->nama_lengkap,0,2)) }}</span><div class="min-w-0 flex-1"><strong class="block truncate text-sm text-slate-950">{{ $assignment->tenagaPendidik->nama_lengkap }}</strong><span class="block truncate text-xs text-slate-500">{{ $assignment->tenagaPendidik->nip ?: 'Tanpa NIP' }}</span></div><form action="{{ route('admin.wali-kelas.remove-assignment',$kelas) }}" method="POST" data-confirm data-confirm-title="Lepas wali kelas?" data-confirm-message="{{ $assignment->tenagaPendidik->nama_lengkap }} akan dilepas dari {{ $kelas->nama_kelas }}." data-confirm-text="Ya, lepas">@csrf @method('DELETE')<input type="hidden" name="wali_kelas_id" value="{{ $assignment->tenaga_pendidik_id }}"><x-cleanflow.table-action type="submit" tone="delete" icon="fas fa-user-minus" label="Lepas wali kelas" /></form></article>@empty<p class="p-8 text-center text-sm text-slate-500">Belum ada wali kelas.</p>@endforelse</div></section>
<section class="rounded-2xl border border-brand-200 bg-brand-50 p-4 shadow-sm"><h3 class="font-extrabold text-slate-950">Tambah wali kelas</h3><p class="mt-1 text-xs text-slate-600">Pilih wali aktif lalu simpan penugasan.</p><form action="{{ route('admin.wali-kelas.assign',$kelas) }}" method="POST" class="mt-4 space-y-3">@csrf<select name="wali_kelas_id" class="h-11 w-full rounded-xl border border-brand-200 bg-white px-3 text-sm" required><option value="">Pilih wali kelas</option>@foreach($waliKelasOptions as $wali)<option value="{{ $wali->id }}">{{ $wali->nama_lengkap }} · {{ $wali->user->cabang->nama_cabang ?? 'Tanpa cabang' }}</option>@endforeach</select><button class="inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 text-xs font-bold text-white"><i class="fas fa-user-plus"></i>Tambahkan wali</button></form></section></div>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 px-4 py-4"><h3 class="font-extrabold text-slate-950">Anggota kelas</h3><p class="mt-1 text-xs text-slate-500">Daftar siswa yang akan didampingi wali kelas.</p></header>@if($kelas->siswa->isEmpty())<p class="p-10 text-center text-sm text-slate-500">Belum ada siswa di kelas ini.</p>@else<div class="grid gap-2 p-3 sm:grid-cols-2">@foreach($kelas->siswa as $siswa)<article class="flex min-w-0 items-center gap-3 rounded-xl border border-slate-200 p-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-xs font-extrabold text-slate-700">{{ strtoupper(substr($siswa->nama_lengkap,0,2)) }}</span><div class="min-w-0"><strong class="block truncate text-sm text-slate-900">{{ $siswa->nama_lengkap }}</strong><span class="block truncate text-xs text-slate-500">{{ $siswa->nis ?: 'Tanpa NIS' }} · {{ $siswa->jenis_kelamin==='L'?'Laki-laki':'Perempuan' }}</span></div></article>@endforeach</div>@endif</section></div></div>
@endsection
