@extends('layouts.print')
@section('title', 'Daftar Jadwal Pelajaran')
@section('back-url', route('admin.jadwal-pelajaran.index', request()->query()))
@section('report-title', 'Daftar Jadwal Pelajaran')
@section('report-meta')
<p class="mt-1 text-xs text-slate-600 print:text-[8pt]">Tahun ajaran {{ $tahunAjaran?->nama_tahun_ajaran ?? 'semua periode' }} · {{ $jadwalList->count() }} sesi</p>
@if(array_filter($filterInfo))<p class="mt-1 text-[10px] text-slate-500 print:text-[7pt]">Filter: {{ collect($filterInfo)->filter()->map(fn ($value, $key) => ucfirst($key) . ' ' . $value)->join(' · ') }}</p>@endif
@endsection

@section('report-content')
<table class="w-full table-fixed border-collapse text-[9px] print:text-[7pt]"><colgroup><col class="w-8"><col class="w-16"><col class="w-20"><col class="w-[16%]"><col class="w-[18%]"><col><col class="w-[20%]"></colgroup><thead><tr class="bg-slate-800 text-white"><th class="border border-slate-500 px-1.5 py-2">No</th><th class="border border-slate-500 px-1.5 py-2">Hari</th><th class="border border-slate-500 px-1.5 py-2">Jam</th><th class="border border-slate-500 px-1.5 py-2">Kelas</th><th class="border border-slate-500 px-1.5 py-2">Cabang</th><th class="border border-slate-500 px-1.5 py-2">Mata pelajaran</th><th class="border border-slate-500 px-1.5 py-2">Guru</th></tr></thead><tbody>@forelse($jadwalList as $jadwal)<tr><td class="border border-slate-300 px-1.5 py-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 px-1.5 py-2 font-bold">{{ $jadwal->hari }}</td><td class="whitespace-nowrap border border-slate-300 px-1.5 py-2">{{ $jadwal->jam_mulai->format('H:i') }}–{{ $jadwal->jam_selesai->format('H:i') }}</td><td class="border border-slate-300 px-1.5 py-2">{{ $jadwal->kelas->pluck('nama_kelas')->join(', ') }}</td><td class="border border-slate-300 px-1.5 py-2">{{ $jadwal->kelas->pluck('cabang.nama_cabang')->unique()->join(', ') }}</td><td class="border border-slate-300 px-1.5 py-2 font-bold">{{ $jadwal->mataPelajaran->nama_mapel }}</td><td class="border border-slate-300 px-1.5 py-2">{{ $jadwal->guru->nama_lengkap ?? '-' }}</td></tr>@empty<tr><td colspan="7" class="border border-slate-300 p-8 text-center text-slate-500">Tidak ada data jadwal.</td></tr>@endforelse</tbody></table>
@if($pengaturanIstirahat->isNotEmpty())<div class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-[9px] print:text-[7pt]"><p class="font-extrabold text-amber-900">Referensi waktu istirahat</p><p class="mt-1 text-amber-800">{{ $pengaturanIstirahat->map(fn ($item) => $item->jenjang . ': ' . substr($item->jam_mulai, 0, 5) . '–' . substr($item->jam_selesai, 0, 5))->join(' · ') }}</p></div>@endif
@endsection
