@extends('layouts.app')
@section('title', 'Jadwal ' . $kelas->nama_kelas)
@section('page-title', 'Jadwal Pelajaran')
@section('page-subtitle', $kelas->nama_kelas . ' · ' . $kelas->cabang->nama_cabang)

@section('content')
<div class="min-w-0 w-full space-y-4">
    <header class="flex min-w-0 flex-wrap items-start justify-between gap-3"><div class="flex min-w-0 items-start gap-3"><a href="{{ route('admin.jadwal-pelajaran.index', ['tahun_ajaran_id' => $currentTahunAjaran->id]) }}" class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 no-underline hover:border-brand-300 hover:text-brand-700"><i class="fas fa-arrow-left"></i></a><div class="min-w-0"><p class="text-xs font-bold uppercase tracking-wider text-brand-600">Jadwal per kelas</p><h2 class="truncate text-xl font-extrabold text-slate-950 sm:text-2xl">{{ $kelas->nama_kelas }}</h2><p class="mt-1 text-sm text-slate-500">{{ $kelas->cabang->nama_cabang }} · {{ $kelas->jenjang }} · {{ $currentTahunAjaran->nama_tahun_ajaran }}</p></div></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.jadwal-pelajaran.create', ['tahun_ajaran_id' => $currentTahunAjaran->id, 'kelas_id' => $kelas->id]) }}" class="inline-flex min-h-10 items-center gap-2 rounded-xl bg-brand-600 px-4 text-xs font-bold text-white no-underline hover:bg-brand-700"><i class="fas fa-plus"></i>Tambah</a><a href="{{ route('admin.jadwal-pelajaran.preview-print', ['kelas' => $kelas->id, 'tahun_ajaran_id' => $currentTahunAjaran->id]) }}" target="_blank" class="inline-flex min-h-10 items-center gap-2 rounded-xl bg-slate-100 px-4 text-xs font-bold text-slate-700 no-underline hover:bg-slate-200"><i class="fas fa-print"></i>Pratinjau</a></div></header>
    <section class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">Total jadwal</p><p class="mt-2 text-2xl font-extrabold text-slate-950">{{ $jadwalByHari->flatten()->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">Hari belajar</p><p class="mt-2 text-2xl font-extrabold text-slate-950">{{ $jadwalByHari->filter(fn ($items) => $items->isNotEmpty())->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">Wali kelas</p><p class="mt-2 truncate text-sm font-extrabold text-slate-950">{{ $kelas->waliKelas->nama_lengkap ?? 'Belum ditentukan' }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">Status</p><p class="mt-2 text-sm font-extrabold text-emerald-700">Jadwal aktif</p></div></section>
    @if($jadwalByHari->flatten()->isEmpty())
        <section class="rounded-2xl border border-dashed border-slate-300 bg-white px-5 py-12 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-50 text-xl text-brand-600"><i class="fas fa-calendar-week"></i></span><h3 class="mt-4 font-extrabold text-slate-950">Belum ada jadwal</h3><p class="mt-1 text-sm text-slate-500">Tambahkan jadwal pertama untuk kelas ini.</p></section>
    @else
        <section class="grid min-w-0 gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($hariList as $hari)<article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="flex items-center justify-between border-b border-slate-200 px-4 py-3"><h3 class="font-extrabold text-slate-950">{{ $hari }}</h3><span class="rounded-lg bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">{{ $jadwalByHari[$hari]->count() }} sesi</span></header><div class="divide-y divide-slate-100">@forelse($jadwalByHari[$hari] as $jadwal)<a href="{{ route('admin.jadwal-pelajaran.edit', $jadwal) }}" class="flex items-start gap-3 px-4 py-3 no-underline hover:bg-slate-50"><time class="whitespace-nowrap rounded-lg bg-brand-50 px-2 py-1 text-xs font-extrabold text-brand-700">{{ $jadwal->jam_mulai->format('H:i') }}</time><span class="min-w-0 flex-1"><strong class="block truncate text-sm text-slate-950">{{ $jadwal->mataPelajaran->nama_mapel }}</strong><span class="mt-0.5 block truncate text-xs text-slate-500">{{ $jadwal->guru->nama_lengkap ?? 'Belum ada guru' }} · sampai {{ $jadwal->jam_selesai->format('H:i') }}</span></span>@if($jadwal->status === 'kosong')<span class="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">Kosong</span>@endif</a>@empty<p class="px-4 py-8 text-center text-xs text-slate-400">Tidak ada sesi</p>@endforelse</div></article>@endforeach</section>
    @endif
</div>
@endsection
