@extends('layouts.app')

@section('title', 'Dashboard Ketua PKBM')
@section('page-title', 'Dashboard Ketua PKBM')
@section('page-subtitle', 'Pantau keputusan, aktivitas, dan kondisi operasional PKBM')

@section('content')
<div class="min-w-0 w-full space-y-5">
    <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-wide text-brand-600">Ringkasan eksekutif</p><h2 class="mt-1 text-xl font-extrabold text-slate-950 sm:text-2xl">Kondisi PKBM hari ini</h2><p class="mt-1 text-sm text-slate-500">Data operasional untuk pengawasan dan pengambilan keputusan.</p></div><time class="inline-flex min-h-10 items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-700 shadow-sm sm:self-auto"><i class="fas fa-calendar-day text-brand-600" aria-hidden="true"></i>{{ now()->locale('id')->translatedFormat('d F Y') }}</time></header>

    <section class="grid grid-cols-2 gap-3 xl:grid-cols-4">
        @foreach([
            ['Siswa aktif', $totalSiswa, 'Terdaftar dan sedang belajar', 'fa-user-graduate', 'bg-brand-50 text-brand-700'],
            ['Tenaga pendidik', $totalGuru, 'Seluruh guru dan staf akademik', 'fa-chalkboard-teacher', 'bg-emerald-50 text-emerald-700'],
            ['Kelas aktif', $totalKelas, 'Pada tahun ajaran berjalan', 'fa-school', 'bg-cyan-50 text-cyan-700'],
            ['Dispensasi pending', $pendingDispensasi, 'Perlu keputusan Ketua', 'fa-hourglass-half', $pendingDispensasi > 0 ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'],
        ] as [$label, $value, $description, $icon, $tone])
            <article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><strong class="block text-xl font-extrabold text-slate-950 sm:text-2xl">{{ number_format($value) }}</strong><span class="mt-1 block truncate text-[10px] font-bold uppercase tracking-wide text-slate-500">{{ $label }}</span></div><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl {{ $tone }}"><i class="fas {{ $icon }}" aria-hidden="true"></i></span></div><p class="mt-3 truncate border-t border-slate-100 pt-3 text-[11px] text-slate-500" title="{{ $description }}">{{ $description }}</p></article>
        @endforeach
    </section>

    <section class="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-800"><div class="flex items-start gap-3"><i class="fas fa-shield-halved mt-0.5 text-brand-700" aria-hidden="true"></i><p><strong class="text-blue-950">Mode pengawasan:</strong> gunakan halaman monitoring untuk analisis. Perubahan data operasional tetap dilakukan oleh petugas pada modul masing-masing.</p></div></section>

    <div class="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]">
        <section class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="flex items-center justify-between gap-3 border-b border-slate-200 p-4 sm:p-5"><div><h2 class="flex items-center gap-2 text-base font-extrabold text-slate-950"><i class="fas fa-clock-rotate-left text-brand-600" aria-hidden="true"></i>Aktivitas login terbaru</h2><p class="mt-1 text-xs text-slate-500">Lima pengguna terakhir yang mengakses sistem.</p></div><a href="{{ route('ketua.monitoring.pengguna') }}" class="inline-flex min-h-9 shrink-0 items-center rounded-xl bg-brand-50 px-3 text-xs font-bold text-brand-700 no-underline hover:bg-brand-100">Lihat semua</a></header><div class="divide-y divide-slate-100">@forelse($recent_logins as $login)<article class="flex min-w-0 items-center gap-3 px-4 py-3 sm:px-5"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-xs font-extrabold text-slate-700">{{ strtoupper(substr($login->name,0,1)) }}</span><div class="min-w-0 flex-1"><h3 class="truncate text-sm font-bold text-slate-900">{{ $login->name }}</h3><p class="mt-0.5 truncate text-[11px] text-slate-500">{{ $login->role_label }}</p></div><time class="shrink-0 text-[10px] text-slate-400">{{ \Carbon\Carbon::parse($login->last_login_at)->locale('id')->diffForHumans() }}</time></article>@empty<div class="p-12 text-center text-sm text-slate-500"><i class="fas fa-inbox mb-3 block text-4xl text-slate-300" aria-hidden="true"></i>Belum ada aktivitas terekam.</div>@endforelse</div></section>

        <section class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" x-data="{ tab: 'approval' }"><header class="border-b border-slate-200 p-4 sm:p-5"><h2 class="flex items-center gap-2 text-base font-extrabold text-slate-950"><i class="fas fa-grid-2 text-brand-600" aria-hidden="true"></i>Akses modul utama</h2><div class="mt-4 grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1" role="tablist">@foreach(['approval'=>'Keputusan','monitoring'=>'Monitoring','laporan'=>'Laporan'] as $key=>$label)<button type="button" @click="tab='{{ $key }}'" :class="tab==='{{ $key }}'?'bg-white text-brand-700 shadow-sm':'text-slate-500 hover:text-slate-800'" class="min-h-9 rounded-lg px-2 text-[10px] font-bold transition" role="tab">{{ $label }}</button>@endforeach</div></header><div class="p-4 sm:p-5">
            <div x-show="tab==='approval'" x-cloak class="grid gap-2">@foreach([[route('ketua.kenaikan-kelas.approval.index'),'fa-check-double','Dispensasi kenaikan','Putuskan izin naik kelas','text-emerald-700 bg-emerald-50'],[route('ketua.validasi-rapor.index'),'fa-certificate','Validasi rapor','Review rapor dari wali kelas','text-brand-700 bg-brand-50'],[route('ketua.dispensasi.index'),'fa-hand-holding-heart','Dispensasi keuangan','Akses ujian dan rapor','text-amber-700 bg-amber-50']] as [$url,$icon,$title,$desc,$tone])<a href="{{ $url }}" class="group flex items-center gap-3 rounded-xl border border-slate-200 p-3 no-underline hover:border-brand-200 hover:bg-brand-50/30"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl {{ $tone }}"><i class="fas {{ $icon }}" aria-hidden="true"></i></span><span class="min-w-0 flex-1"><strong class="block truncate text-sm text-slate-900">{{ $title }}</strong><small class="block truncate text-slate-500">{{ $desc }}</small></span><i class="fas fa-arrow-right text-xs text-slate-300 group-hover:text-brand-600" aria-hidden="true"></i></a>@endforeach</div>
            <div x-show="tab==='monitoring'" x-cloak class="grid gap-2">@foreach([[route('ketua.monitoring.siswa'),'fa-user-graduate','Aktivitas siswa'],[route('ketua.monitoring.wali-kelas'),'fa-user-tie','Wali kelas'],[route('ketua.monitoring.guru-pengajar'),'fa-chalkboard-teacher','Guru pengajar'],[route('ketua.monitoring.lms.index'),'fa-laptop','Konten LMS']] as [$url,$icon,$title])<a href="{{ $url }}" class="group flex min-h-12 items-center gap-3 rounded-xl border border-slate-200 px-3 no-underline hover:border-brand-200 hover:bg-brand-50/30"><i class="fas {{ $icon }} w-5 text-center text-brand-600" aria-hidden="true"></i><strong class="min-w-0 flex-1 truncate text-sm text-slate-800">{{ $title }}</strong><i class="fas fa-arrow-right text-xs text-slate-300 group-hover:text-brand-600" aria-hidden="true"></i></a>@endforeach</div>
            <div x-show="tab==='laporan'" x-cloak class="grid gap-2">@foreach([[route('ketua.laporan.index'),'fa-print','Cetak laporan','Laporan operasional dan akademik'],[route('ketua.catatan.index'),'fa-message','Catatan','Komunikasi tindak lanjut']] as [$url,$icon,$title,$desc])<a href="{{ $url }}" class="group flex items-center gap-3 rounded-xl border border-slate-200 p-3 no-underline hover:border-brand-200 hover:bg-brand-50/30"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><i class="fas {{ $icon }}" aria-hidden="true"></i></span><span class="min-w-0 flex-1"><strong class="block truncate text-sm text-slate-900">{{ $title }}</strong><small class="block truncate text-slate-500">{{ $desc }}</small></span><i class="fas fa-arrow-right text-xs text-slate-300 group-hover:text-brand-600" aria-hidden="true"></i></a>@endforeach</div>
        </div></section>
    </div>
</div>
@endsection
