@extends('layouts.app')
@section('title', 'Guru Pengajar')
@section('page-title', 'Guru Pengajar')
@section('page-subtitle', 'Pantau guru, kelas, dan mata pelajaran yang berasal dari jadwal')

@section('content')
<div class="min-w-0 w-full space-y-4">
    <section class="grid grid-cols-2 gap-3 xl:grid-cols-4">@foreach([['Guru aktif',$stats['totalGuru'],'fa-user-tie','blue'],['Sudah ditugaskan',$stats['guruWithAssignment'],'fa-user-check','emerald'],['Total penugasan',$stats['totalPenugasan'],'fa-link','amber'],['Mata pelajaran',$stats['totalMataPelajaran'],'fa-book','violet']] as [$label,$value,$icon,$tone])<article class="flex min-w-0 items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span @class(['flex h-11 w-11 shrink-0 items-center justify-center rounded-xl','bg-blue-50 text-blue-600'=>$tone==='blue','bg-emerald-50 text-emerald-600'=>$tone==='emerald','bg-amber-50 text-amber-600'=>$tone==='amber','bg-violet-50 text-violet-600'=>$tone==='violet'])><i class="fas {{ $icon }}"></i></span><div><p class="text-2xl font-extrabold text-slate-950">{{ $value }}</p><p class="text-[10px] font-bold uppercase tracking-wide text-slate-500">{{ $label }}</p></div></article>@endforeach</section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 px-4 py-4 sm:px-5"><div><h2 class="text-lg font-extrabold text-slate-950"><i class="fas fa-chalkboard-teacher mr-2 text-brand-600"></i>Daftar guru pengajar</h2><p class="mt-1 text-xs text-slate-500">Penugasan dibentuk otomatis dari jadwal pelajaran.</p></div><div class="flex flex-wrap gap-2"><form action="{{ route('admin.guru-pengajar.rebuild') }}" method="POST" data-confirm data-confirm-title="Sinkronkan penugasan guru?" data-confirm-message="Daftar penugasan akan disusun ulang berdasarkan jadwal pada periode terpilih." data-confirm-text="Ya, sinkronkan">@csrf<input type="hidden" name="tahun_ajaran_id" value="{{ request('tahun_ajaran_id', $currentTahunAjaran?->id) }}"><button type="submit" class="inline-flex min-h-10 items-center gap-2 rounded-xl bg-amber-50 px-3 text-xs font-bold text-amber-700 hover:bg-amber-100"><i class="fas fa-rotate"></i>Sinkronkan</button></form><a href="{{ route('admin.guru-pengajar.print', request()->query()) }}" target="_blank" class="inline-flex min-h-10 items-center gap-2 rounded-xl bg-slate-100 px-3 text-xs font-bold text-slate-700 no-underline hover:bg-slate-200"><i class="fas fa-print"></i>Cetak</a></div></header>
        <form action="{{ route('admin.guru-pengajar.index') }}" method="GET" class="grid gap-2 border-b border-slate-200 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_220px_180px_auto] sm:px-5"><label class="relative"><i class="fas fa-search absolute left-3.5 top-3.5 text-xs text-slate-400"></i><input type="search" name="search" value="{{ request('search') }}" class="h-11 w-full rounded-xl border border-slate-300 !pl-10 pr-3 text-sm outline-none focus:border-brand-500" placeholder="Cari nama, NIP, atau email..."></label><select name="tahun_ajaran_id" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm" @change="$el.form.submit()"><option value="">Semua tahun ajaran</option>@foreach($tahunAjarans as $tahun)<option value="{{ $tahun->id }}" @selected((string) request('tahun_ajaran_id', $currentTahunAjaran?->id) === (string) $tahun->id)>{{ $tahun->nama_tahun_ajaran }}{{ $tahun->is_active ? ' (Aktif)' : '' }}</option>@endforeach</select><select name="status" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm" @change="$el.form.submit()"><option value="">Guru aktif</option><option value="inactive" @selected(request('status')==='inactive')>Tidak aktif</option><option value="active" @selected(request('status')==='active')>Aktif</option></select><button class="h-11 rounded-xl bg-slate-800 px-4 text-xs font-bold text-white">Cari</button></form>
        @if($guruList->isEmpty())<div class="px-5 py-14 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-50 text-xl text-brand-600"><i class="fas fa-user-slash"></i></span><h3 class="mt-4 font-extrabold text-slate-950">Guru tidak ditemukan</h3><p class="mt-1 text-sm text-slate-500">Ubah filter atau susun jadwal guru terlebih dahulu.</p></div>@else
        <div class="grid gap-3 p-3 md:hidden">@foreach($guruList as $guru)<article class="rounded-2xl border border-slate-200 p-4"><div class="flex items-start gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-sm font-extrabold text-brand-700">{{ strtoupper(substr($guru->nama_lengkap,0,2)) }}</span><div class="min-w-0 flex-1"><h3 class="truncate text-sm font-extrabold text-slate-950">{{ $guru->nama_lengkap }}</h3><p class="truncate text-xs text-slate-500">{{ $guru->nip ?: 'Tanpa NIP' }} · {{ $guru->user->email }}</p><p class="mt-2 text-xs font-bold text-brand-700">{{ $guru->guruKelas->pluck('kelas_id')->unique()->count() }} kelas · {{ $guru->guruKelas->count() }} penugasan</p></div></div><a href="{{ route('admin.guru-pengajar.show',['guruPengajar'=>$guru,'tahun_ajaran_id'=>request('tahun_ajaran_id')]) }}" class="mt-3 inline-flex min-h-9 w-full items-center justify-center gap-2 rounded-xl bg-brand-50 text-xs font-bold text-brand-700 no-underline"><i class="fas fa-eye"></i>Lihat penugasan</a></article>@endforeach</div>
        <div class="hidden overflow-x-auto md:block"><table class="w-full table-fixed text-left"><colgroup><col class="w-16"><col class="w-[28%]"><col class="w-[20%]"><col><col class="w-28"><col class="w-28"><col class="w-20"></colgroup><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-3 py-3">No</th><th class="px-3 py-3">Guru</th><th class="px-3 py-3">NIP</th><th class="px-3 py-3">Email</th><th class="px-3 py-3">Kelas</th><th class="px-3 py-3">Penugasan</th><th class="px-3 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($guruList as $guru)<tr class="hover:bg-slate-50"><td class="px-3 py-4 text-xs text-slate-500">{{ $guruList->firstItem()+$loop->index }}</td><td class="px-3 py-4"><div class="flex min-w-0 items-center gap-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-xs font-extrabold text-brand-700">{{ strtoupper(substr($guru->nama_lengkap,0,2)) }}</span><strong class="truncate text-sm text-slate-950" title="{{ $guru->nama_lengkap }}">{{ $guru->nama_lengkap }}</strong></div></td><td class="px-3 py-4 text-xs text-slate-600"><span class="whitespace-nowrap">{{ $guru->nip ?: '—' }}</span></td><td class="px-3 py-4"><p class="truncate text-xs text-slate-600" title="{{ $guru->user->email }}">{{ $guru->user->email }}</p></td><td class="px-3 py-4 text-xs font-bold text-slate-700">{{ $guru->guruKelas->pluck('kelas_id')->unique()->count() }}</td><td class="px-3 py-4 text-xs font-bold text-slate-700">{{ $guru->guruKelas->count() }}</td><td class="px-3 py-4"><div class="flex justify-end"><x-cleanflow.table-action href="{{ route('admin.guru-pengajar.show',['guruPengajar'=>$guru,'tahun_ajaran_id'=>request('tahun_ajaran_id')]) }}" tone="view" icon="fas fa-eye" label="Lihat penugasan" /></div></td></tr>@endforeach</tbody></table></div>
        <div class="border-t border-slate-200 px-4 py-3">{{ $guruList->withQueryString()->links() }}</div>@endif
    </section>
</div>
@endsection
