@extends('layouts.app')
@section('title', 'Guru Kelas ' . $kelas->nama_kelas)
@section('page-title', 'Guru Pengajar per Kelas')
@section('page-subtitle', 'Ringkasan penugasan dan jadwal untuk ' . $kelas->nama_kelas)

@section('content')
<div class="min-w-0 w-full space-y-4"><header class="flex min-w-0 items-start gap-3"><a href="{{ route('admin.guru-pengajar.index') }}" class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 no-underline"><i class="fas fa-arrow-left"></i></a><div><p class="text-xs font-bold uppercase tracking-wide text-brand-600">Penugasan per kelas</p><h2 class="text-xl font-extrabold text-slate-950 sm:text-2xl">{{ $kelas->nama_kelas }}</h2><p class="mt-1 text-sm text-slate-500">{{ $kelas->cabang->nama_cabang }} · {{ $kelas->jenjang }} · {{ $kelas->tahunAjaran->nama_tahun_ajaran }}</p></div></header>
<div class="grid min-w-0 gap-4 xl:grid-cols-2"><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 px-4 py-4"><h3 class="font-extrabold text-slate-950">Guru dan mata pelajaran</h3><p class="mt-1 text-xs text-slate-500">{{ $kelas->guruPengajar->count() }} penugasan tercatat.</p></header><div class="divide-y divide-slate-100">@forelse($kelas->guruPengajar as $assignment)<article class="flex items-start gap-3 px-4 py-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-xs font-extrabold text-brand-700">{{ strtoupper(substr($assignment->tenagaPendidik->nama_lengkap,0,2)) }}</span><div class="min-w-0"><strong class="block truncate text-sm text-slate-950">{{ $assignment->tenagaPendidik->nama_lengkap }}</strong><span class="block truncate text-xs text-slate-500">{{ $assignment->mataPelajaran->nama_mapel }}</span></div></article>@empty<p class="p-8 text-center text-sm text-slate-500">Belum ada guru yang ditugaskan.</p>@endforelse</div></section><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="flex items-center justify-between border-b border-slate-200 px-4 py-4"><div><h3 class="font-extrabold text-slate-950">Jadwal kelas</h3><p class="mt-1 text-xs text-slate-500">Sumber utama penugasan guru.</p></div><a href="{{ route('admin.jadwal-pelajaran.show',['kelas'=>$kelas->id,'tahun_ajaran_id'=>$kelas->tahun_ajaran_id]) }}" class="text-xs font-bold text-brand-700 no-underline">Lihat lengkap</a></header><div class="divide-y divide-slate-100">@forelse($jadwalList as $jadwal)<article class="flex items-start gap-3 px-4 py-3"><time class="whitespace-nowrap rounded-lg bg-brand-50 px-2 py-1 text-[10px] font-extrabold text-brand-700">{{ $jadwal->hari }} {{ $jadwal->jam_mulai->format('H:i') }}</time><div class="min-w-0"><strong class="block truncate text-sm text-slate-950">{{ $jadwal->mataPelajaran->nama_mapel }}</strong><span class="block truncate text-xs text-slate-500">{{ $jadwal->guru->nama_lengkap ?? 'Belum ada guru' }} · sampai {{ $jadwal->jam_selesai->format('H:i') }}</span></div></article>@empty<p class="p-8 text-center text-sm text-slate-500">Belum ada jadwal kelas.</p>@endforelse</div></section></div></div>
@endsection
