@extends('layouts.app')
@section('title', 'Penugasan ' . $guruPengajar->nama_lengkap)
@section('page-title', 'Detail Guru Pengajar')
@section('page-subtitle', 'Kelas, mata pelajaran, dan jadwal mengajar pada periode terpilih')

@section('content')
<div class="min-w-0 w-full space-y-4"><header class="flex flex-wrap items-start justify-between gap-3"><div class="flex min-w-0 items-start gap-3"><a href="{{ route('admin.guru-pengajar.index',['tahun_ajaran_id'=>$currentTahunAjaran?->id]) }}" class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 no-underline"><i class="fas fa-arrow-left"></i></a><div class="min-w-0"><p class="text-xs font-bold uppercase tracking-wide text-brand-600">Guru pengajar</p><h2 class="truncate text-xl font-extrabold text-slate-950 sm:text-2xl">{{ $guruPengajar->nama_lengkap }}</h2><p class="mt-1 truncate text-sm text-slate-500">{{ $guruPengajar->nip ?: 'Tanpa NIP' }} · {{ $guruPengajar->user->email }}</p></div></div><form action="{{ route('admin.guru-pengajar.show',$guruPengajar) }}" method="GET"><select name="tahun_ajaran_id" @change="$el.form.submit()" class="h-10 rounded-xl border border-slate-300 bg-white px-3 text-xs font-bold">@foreach($tahunAjarans as $tahun)<option value="{{ $tahun->id }}" @selected($currentTahunAjaran?->id===$tahun->id)>{{ $tahun->nama_tahun_ajaran }}</option>@endforeach</select></form></header>
<section class="grid grid-cols-3 gap-3">@foreach([['Kelas',$stats['totalKelas'],'fa-school'],['Mata pelajaran',$stats['totalMapel'],'fa-book'],['Penugasan',$stats['totalPenugasan'],'fa-link']] as [$label,$value,$icon])<article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><i class="fas {{ $icon }} text-brand-600"></i><p class="mt-2 text-2xl font-extrabold text-slate-950">{{ $value }}</p><p class="text-[10px] font-bold uppercase text-slate-500">{{ $label }}</p></article>@endforeach</section>
<div class="grid min-w-0 gap-4 xl:grid-cols-2"><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 px-4 py-4"><h3 class="font-extrabold text-slate-950">Penugasan kelas dan mapel</h3><p class="mt-1 text-xs text-slate-500">Berasal dari jadwal pelajaran.</p></header><div class="divide-y divide-slate-100">@forelse($guruPengajar->guruKelas as $assignment)<article class="flex min-w-0 items-center gap-3 px-4 py-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><i class="fas fa-school"></i></span><div class="min-w-0 flex-1"><strong class="block truncate text-sm text-slate-950">{{ $assignment->kelas->nama_kelas }} · {{ $assignment->mataPelajaran->nama_mapel }}</strong><span class="block truncate text-xs text-slate-500">{{ $assignment->kelas->cabang->nama_cabang ?? '-' }} · {{ $assignment->kelas->jenjang }}</span></div></article>@empty<p class="p-8 text-center text-sm text-slate-500">Belum ada penugasan pada periode ini.</p>@endforelse</div></section>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="flex items-center justify-between border-b border-slate-200 px-4 py-4"><div><h3 class="font-extrabold text-slate-950">Jadwal mengajar</h3><p class="mt-1 text-xs text-slate-500">Urutan hari dan waktu belajar.</p></div><a href="{{ route('admin.jadwal-pelajaran.index',['guru_id'=>$guruPengajar->id,'tahun_ajaran_id'=>$currentTahunAjaran?->id]) }}" class="text-xs font-bold text-brand-700 no-underline">Buka jadwal</a></header><div class="divide-y divide-slate-100">@forelse($jadwalList as $jadwal)<article class="flex items-start gap-3 px-4 py-3"><time class="whitespace-nowrap rounded-lg bg-brand-50 px-2 py-1 text-[10px] font-extrabold text-brand-700">{{ $jadwal->hari }} {{ $jadwal->jam_mulai->format('H:i') }}</time><div class="min-w-0"><strong class="block truncate text-sm text-slate-950">{{ $jadwal->mataPelajaran->nama_mapel }}</strong><span class="block truncate text-xs text-slate-500">{{ $jadwal->kelas->pluck('nama_kelas')->join(', ') }} · sampai {{ $jadwal->jam_selesai->format('H:i') }}</span></div></article>@empty<p class="p-8 text-center text-sm text-slate-500">Belum ada jadwal mengajar.</p>@endforelse</div></section></div></div>
@endsection
