@extends('layouts.app')

@section('title', 'Monitoring Guru Pengajar')
@section('page-title', 'Monitoring Guru Pengajar')
@section('page-subtitle', 'Pantau konten LMS, koreksi, dan kelengkapan nilai')

@section('content')
@php
    $routeName=request()->routeIs('ketua.*')?'ketua.monitoring.guru-pengajar':'admin.monitoring.guru-pengajar';
    $rows=$guruPengajar->getCollection();
    $avgProgress=$rows->isNotEmpty()?round($rows->avg('progress_nilai'),1):0;
    $totalKonten=$rows->sum('materi_dibuat')+$rows->sum('tugas_dibuat')+$rows->sum('ujian_dibuat');
@endphp
<div class="min-w-0 w-full space-y-4">
    <header><p class="text-xs font-bold uppercase tracking-wide text-brand-600">Pantau pengajar</p><h2 class="text-xl font-extrabold text-slate-950 sm:text-2xl">Aktivitas guru dan kelengkapan nilai</h2><p class="mt-1 text-sm text-slate-500">Ringkasan mengikuti penugasan pada tahun ajaran aktif dan cabang yang dipilih.</p></header>
    <section class="grid grid-cols-2 gap-3 lg:grid-cols-4">@foreach([['value'=>$guruPengajar->total(),'label'=>'Guru pengajar','icon'=>'fas fa-chalkboard-teacher','tone'=>'bg-blue-50 text-blue-700'],['value'=>$rows->sum('total_kelas_mapel'),'label'=>'Kelas dan mapel','icon'=>'fas fa-layer-group','tone'=>'bg-violet-50 text-violet-700'],['value'=>$totalKonten,'label'=>'Konten LMS','icon'=>'fas fa-book-open','tone'=>'bg-emerald-50 text-emerald-700'],['value'=>number_format($avgProgress,1).'%','label'=>$rows->sum('tugas_perlu_koreksi').' perlu koreksi','icon'=>'fas fa-clipboard-check','tone'=>'bg-amber-50 text-amber-700']] as $stat)<article class="flex min-w-0 items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl {{ $stat['tone'] }}"><i class="{{ $stat['icon'] }}"></i></span><div class="min-w-0"><strong class="block truncate text-xl font-extrabold text-slate-950">{{ $stat['value'] }}</strong><span class="block truncate text-[10px] font-bold uppercase tracking-wide text-slate-500">{{ $stat['label'] }}</span></div></article>@endforeach</section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="border-b border-slate-200 p-4 sm:p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-extrabold text-slate-950"><i class="fas fa-chart-column mr-2 text-brand-600"></i>Aktivitas guru pengajar</h3><p class="mt-1 text-xs text-slate-500">Materi, tugas, ujian, pertemuan, dan nilai dalam satu ringkasan.</p></div>@if(request()->anyFilled(['search','cabang_id','tahun_ajaran_id']))<a href="{{ route($routeName) }}" class="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700 no-underline">Reset filter</a>@endif</div><form action="{{ route($routeName) }}" method="GET" class="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_220px_170px_auto]"><label class="relative sm:col-span-2 xl:col-span-1"><i class="fas fa-search absolute left-3.5 top-3.5 text-xs text-slate-400"></i><input name="search" value="{{ request('search') }}" placeholder="Cari guru..." class="h-11 w-full rounded-xl border border-slate-300 !pl-10 pr-3 text-sm"></label><select name="cabang_id" @change="$el.form.submit()" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Semua cabang</option>@foreach($cabangs as $cabang)<option value="{{ $cabang->id }}" @selected((string)request('cabang_id')===(string)$cabang->id)>{{ $cabang->nama_cabang }}</option>@endforeach</select><select name="tahun_ajaran_id" @change="$el.form.submit()" class="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm">@foreach($tahunAjarans as $tahun)<option value="{{ $tahun->id }}" @selected((int)$taFilterId===$tahun->id)>{{ $tahun->nama_tahun_ajaran }}{{ $tahun->is_active?' (Aktif)':'' }}</option>@endforeach</select><button class="h-11 rounded-xl bg-slate-800 px-4 text-xs font-bold text-white">Cari</button></form></header>
        <div class="divide-y divide-slate-100 xl:hidden">
            @forelse($guruPengajar as $guru)
                @php $assignments=$guru->visible_guru_kelas??$guru->guruKelas; $progress=$guru->progress_nilai??0; @endphp
                <article class="p-4"><div class="flex items-start gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-xs font-extrabold text-blue-700">{{ strtoupper(substr($guru->nama_lengkap,0,1)) }}</span><div class="min-w-0 flex-1"><strong class="block truncate text-sm text-slate-950">{{ $guru->nama_lengkap }}</strong><span class="block truncate text-xs text-slate-500">{{ $guru->nip ?: 'NIP belum diisi' }} &middot; {{ $assignments->count() }} penugasan</span></div><span class="rounded-full px-2 py-1 text-[10px] font-bold {{ $progress>=75?'bg-emerald-50 text-emerald-700':($progress>=50?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700') }}">{{ number_format($progress,1) }}%</span></div><div class="mt-3 flex flex-wrap gap-1">@forelse($assignments->take(4) as $assignment)<span class="max-w-full truncate rounded-full bg-brand-50 px-2 py-1 text-[10px] font-bold text-brand-700">{{ $assignment->kelas->nama_kelas??'-' }} - {{ $assignment->mataPelajaran->nama_mapel??'-' }}</span>@empty<span class="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">Belum ada penugasan</span>@endforelse @if($assignments->count()>4)<span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">+{{ $assignments->count()-4 }}</span>@endif</div><div class="mt-3 grid grid-cols-4 gap-2 text-center">@foreach([['Materi',$guru->materi_dibuat??0],['Tugas',$guru->tugas_dibuat??0],['Ujian',$guru->ujian_dibuat??0],['Meeting',$guru->meeting_dibuat??0]] as [$label,$value])<div class="rounded-xl bg-slate-50 p-2"><strong class="block text-sm text-slate-900">{{ $value }}</strong><span class="text-[9px] text-slate-400">{{ $label }}</span></div>@endforeach</div><div class="mt-3 rounded-xl border border-slate-200 p-3"><div class="flex justify-between text-[10px] font-bold text-slate-500"><span>Progress nilai</span><span>{{ $guru->nilai_sudah_diisi??0 }} dinilai &middot; {{ $guru->total_nilai_harus_diisi??0 }} belum</span></div><progress max="100" value="{{ min($progress,100) }}" class="mt-2 h-2 w-full accent-brand-600"></progress>@if(($guru->tugas_perlu_koreksi??0)>0)<p class="mt-1 text-[10px] font-bold text-amber-700">{{ $guru->tugas_perlu_koreksi }} tugas menunggu koreksi</p>@endif</div></article>
            @empty<p class="p-10 text-center text-sm text-slate-500">Belum ada data guru pengajar.</p>@endforelse
        </div>
        <div class="hidden overflow-x-auto xl:block"><table class="w-full table-fixed text-left text-sm"><colgroup><col class="w-[23%]"><col class="w-[25%]"><col class="w-[19%]"><col><col class="w-[16%]"></colgroup><thead class="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Guru</th><th class="px-3 py-3">Kelas dan mapel</th><th class="px-3 py-3">Konten LMS</th><th class="px-3 py-3">Koreksi</th><th class="px-5 py-3">Progress nilai</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($guruPengajar as $guru)@php $assignments=$guru->visible_guru_kelas??$guru->guruKelas; $progress=$guru->progress_nilai??0; @endphp<tr><td class="px-5 py-3"><strong class="block truncate text-slate-950">{{ $guru->nama_lengkap }}</strong><span class="block truncate text-xs text-slate-500">{{ $guru->nip ?: 'NIP belum diisi' }}</span></td><td class="px-3 py-3"><div class="flex flex-wrap gap-1">@forelse($assignments->take(2) as $assignment)<span class="max-w-full truncate rounded-full bg-brand-50 px-2 py-1 text-[10px] font-bold text-brand-700">{{ $assignment->kelas->nama_kelas??'-' }} - {{ $assignment->mataPelajaran->nama_mapel??'-' }}</span>@empty<span class="text-xs text-slate-400">Belum ditugaskan</span>@endforelse @if($assignments->count()>2)<span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">+{{ $assignments->count()-2 }}</span>@endif</div></td><td class="px-3 py-3"><div class="grid grid-cols-4 gap-1 text-center">@foreach([['M',$guru->materi_dibuat??0],['T',$guru->tugas_dibuat??0],['U',$guru->ujian_dibuat??0],['V',$guru->meeting_dibuat??0]] as [$label,$value])<span class="rounded-lg bg-slate-50 p-1 text-[9px] text-slate-400"><strong class="block text-xs text-slate-800">{{ $value }}</strong>{{ $label }}</span>@endforeach</div></td><td class="px-3 py-3"><span class="block text-xs text-emerald-700">{{ $guru->nilai_sudah_diisi??0 }} dinilai</span><span class="block text-xs text-red-600">{{ $guru->total_nilai_harus_diisi??0 }} belum nilai</span><span class="block text-xs text-amber-600">{{ $guru->tugas_perlu_koreksi??0 }} perlu koreksi</span></td><td class="px-5 py-3"><div class="flex justify-between text-[10px] text-slate-500"><span>{{ number_format($progress,1) }}%</span><span>{{ $progress>=100?'Lengkap':'Berjalan' }}</span></div><progress max="100" value="{{ min($progress,100) }}" class="mt-1 h-2 w-full accent-brand-600"></progress></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-sm text-slate-500">Belum ada data guru pengajar.</td></tr>@endforelse</tbody></table></div>
        @if($guruPengajar->hasPages())<footer class="border-t border-slate-200 p-4">{{ $guruPengajar->withQueryString()->links() }}</footer>@endif
    </section>
    <div class="flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs text-blue-700"><i class="fas fa-circle-info mt-0.5"></i><p>Konten mengikuti LMS guru: materi, tugas, ujian, dan virtual class. Progress nilai hanya memakai penugasan pada periode terpilih.</p></div>
</div>
@endsection
