@extends('layouts.app')

@section('title', 'Presensi Siswa')
@section('page-title', 'Presensi Siswa')
@section('page-subtitle', $kelas ? 'Kelas '.$kelas->nama_kelas : 'Kelola kehadiran siswa')

@section('content')
<div class="min-w-0 w-full space-y-4" x-data="{ semester: @js($semester ?? '') }">
    @if($error ?? false)
        <p class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert">{{ $error }}</p>
    @endif

    @if(session('import_errors'))
        <div class="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900" role="alert">
            <p class="font-bold">Baris yang perlu diperbaiki</p>
            <ul class="mt-2 list-disc space-y-1 pl-5">@foreach(session('import_errors') as $issue)<li>{{ $issue }}</li>@endforeach</ul>
        </div>
    @endif

    @if($kelas)
        <header class="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white px-4 py-4 shadow-sm lg:flex-row lg:items-center lg:justify-between">
            <div class="min-w-0"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-sky-700">Kehadiran siswa</p><h1 class="mt-1 text-lg font-extrabold text-slate-900">Presensi Kelas {{ $kelas->nama_kelas }}</h1><p class="mt-0.5 text-xs text-slate-500">Pilih tanggal, catat kehadiran, lalu simpan seluruh kelas.</p></div>
            <div class="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">
                <a href="{{ route('wali.presensi.validasi-izin') }}" class="inline-flex min-h-9 items-center justify-center gap-1.5 whitespace-nowrap rounded-lg bg-amber-50 px-3 text-xs font-bold text-amber-800 hover:bg-amber-100"><i class="fas fa-check-circle" aria-hidden="true"></i>Validasi izin</a>
                <button type="button" @click="$refs.importDialog.showModal()" class="inline-flex min-h-9 items-center justify-center gap-1.5 whitespace-nowrap rounded-lg bg-emerald-50 px-3 text-xs font-bold text-emerald-800 hover:bg-emerald-100"><i class="fas fa-file-excel" aria-hidden="true"></i>Impor Excel</button>
                <a href="{{ route('wali.presensi.print-rekap', ['bulan' => $bulan, 'tahun' => $tahun, 'semester' => $semester ?? null]) }}" target="_blank" rel="noopener" class="inline-flex min-h-9 items-center justify-center gap-1.5 whitespace-nowrap rounded-lg bg-slate-100 px-3 text-xs font-bold text-slate-700 hover:bg-slate-200"><i class="fas fa-print" aria-hidden="true"></i>Cetak rekap</a>
                <a href="{{ route('wali.presensi.riwayat') }}" class="inline-flex min-h-9 items-center justify-center gap-1.5 whitespace-nowrap rounded-lg bg-sky-50 px-3 text-xs font-bold text-sky-800 hover:bg-sky-100"><i class="fas fa-clock-rotate-left" aria-hidden="true"></i>Riwayat & edit</a>
            </div>
        </header>

        <section class="rounded-xl border border-slate-200 bg-white px-4 py-4 shadow-sm" aria-labelledby="filter-presensi-title">
            <h2 id="filter-presensi-title" class="text-sm font-extrabold text-slate-900"><i class="fas fa-filter mr-2 text-sky-700" aria-hidden="true"></i>Periode dan tanggal</h2>
            <form action="{{ route('wali.presensi.index') }}" method="GET" class="mt-3 grid min-w-0 grid-cols-2 gap-3 lg:grid-cols-[minmax(140px,1.2fr)_repeat(3,minmax(120px,1fr))_auto] lg:items-end">
                <label class="min-w-0 text-xs font-bold text-slate-600">Tanggal input<input type="date" name="tanggal" value="{{ $tanggal }}" class="mt-1 block h-10 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-2.5 text-sm font-medium text-slate-800 focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-100"></label>
                <label class="min-w-0 text-xs font-bold text-slate-600">Semester<select name="semester" x-model="semester" class="mt-1 block h-10 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-2.5 text-sm font-medium text-slate-800 focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-100"><option value="">Per bulan</option><option value="ganjil">Ganjil</option><option value="genap">Genap</option></select></label>
                <label class="min-w-0 text-xs font-bold text-slate-600">Bulan<select name="bulan" :disabled="!!semester" class="mt-1 block h-10 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-2.5 text-sm font-medium text-slate-800 disabled:bg-slate-100 disabled:text-slate-400">@for($month = 1; $month <= 12; $month++)<option value="{{ $month }}" @selected($bulan == $month)>{{ \Carbon\Carbon::create(now()->year, $month, 1)->locale('id')->translatedFormat('F') }}</option>@endfor</select></label>
                <label class="min-w-0 text-xs font-bold text-slate-600">Tahun<select name="tahun" :disabled="!!semester" class="mt-1 block h-10 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-2.5 text-sm font-medium text-slate-800 disabled:bg-slate-100 disabled:text-slate-400">@for($year = now()->year - 2; $year <= now()->year + 1; $year++)<option value="{{ $year }}" @selected($tahun == $year)>{{ $year }}</option>@endfor</select></label>
                <div class="col-span-2 flex gap-2 lg:col-span-1"><button type="submit" class="inline-flex h-10 flex-1 items-center justify-center gap-1.5 rounded-lg bg-sky-700 px-3 text-xs font-bold text-white hover:bg-sky-800"><i class="fas fa-check" aria-hidden="true"></i>Terapkan</button><a href="{{ route('wali.presensi.index') }}" class="inline-flex h-10 items-center justify-center rounded-lg border border-slate-300 px-3 text-xs font-bold text-slate-600 hover:bg-slate-50" aria-label="Reset filter"><i class="fas fa-rotate-left" aria-hidden="true"></i></a></div>
            </form>
        </section>

        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm" aria-labelledby="input-presensi-title" x-data>
            <div class="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-3"><div><h2 id="input-presensi-title" class="text-sm font-extrabold text-slate-900">Input presensi</h2><p class="mt-0.5 text-xs text-slate-500">{{ \Carbon\Carbon::parse($tanggal)->locale('id')->translatedFormat('l, d F Y') }}</p></div><span class="rounded-full bg-sky-50 px-2.5 py-1 text-xs font-bold text-sky-800">{{ $siswaList->count() }} siswa</span></div>
            <form x-ref="presensiForm" action="{{ route('wali.presensi.input-harian') }}" method="POST" @submit.prevent="$refs.confirmDialog.showModal()">
                @csrf
                <input type="hidden" name="kelas_id" value="{{ $kelas->id }}"><input type="hidden" name="tanggal" value="{{ $tanggal }}">
                <div class="hidden grid-cols-[48px_minmax(0,1fr)_160px_256px] bg-slate-50 px-4 py-2 text-[11px] font-bold uppercase tracking-wide text-slate-500 lg:grid"><span>No</span><span>Siswa</span><span>Status</span><span>Keterangan</span></div>
                <div class="divide-y divide-slate-100">
                    @forelse($siswaList as $index => $siswa)
                        @php($presensi = $presensiData[$siswa->id] ?? null)
                        <div class="grid min-w-0 grid-cols-2 gap-2 px-4 py-3 lg:grid-cols-[48px_minmax(0,1fr)_160px_256px] lg:items-center lg:gap-0 lg:py-2.5">
                            <span class="hidden text-xs text-slate-500 lg:block">{{ $index + 1 }}</span>
                            <div class="col-span-2 min-w-0 lg:col-span-1"><p class="truncate text-sm font-bold text-slate-900" title="{{ $siswa->nama_lengkap }}">{{ $siswa->nama_lengkap }}</p><p class="text-[11px] text-slate-500">NIS: {{ $siswa->nis ?? $siswa->nisn ?? '-' }}</p></div>
                            <input type="hidden" name="presensi[{{ $index }}][siswa_id]" value="{{ $siswa->id }}">
                            <label class="text-[11px] font-bold text-slate-600 lg:pr-3"><span class="lg:sr-only">Status</span><select name="presensi[{{ $index }}][status]" aria-label="Status {{ $siswa->nama_lengkap }}" required class="mt-1 h-9 w-full rounded-lg border border-slate-300 bg-white px-2 text-xs font-semibold text-slate-800 lg:mt-0"><option value="hadir" @selected(($presensi->status ?? 'hadir') === 'hadir')>Hadir</option><option value="sakit" @selected(($presensi->status ?? '') === 'sakit')>Sakit</option><option value="izin" @selected(($presensi->status ?? '') === 'izin')>Izin</option><option value="alpha" @selected(($presensi->status ?? '') === 'alpha')>Alpha</option></select></label>
                            <label class="min-w-0 text-[11px] font-bold text-slate-600"><span class="lg:sr-only">Keterangan</span><input type="text" name="presensi[{{ $index }}][keterangan]" aria-label="Keterangan {{ $siswa->nama_lengkap }}" value="{{ $presensi->keterangan ?? '' }}" placeholder="Opsional" class="mt-1 h-9 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-2 text-xs font-medium text-slate-800 lg:mt-0"></label>
                        </div>
                    @empty
                        <p class="px-4 py-8 text-center text-sm text-slate-500">Belum ada siswa aktif di kelas ini.</p>
                    @endforelse
                </div>
                <div class="flex justify-end border-t border-slate-100 px-4 py-3"><button type="submit" @disabled($siswaList->isEmpty()) class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-sky-700 px-4 text-xs font-bold text-white hover:bg-sky-800 disabled:cursor-not-allowed disabled:bg-slate-300"><i class="fas fa-floppy-disk" aria-hidden="true"></i>Simpan presensi</button></div>
            </form>
            <dialog x-ref="confirmDialog" class="w-[calc(100%-2rem)] max-w-md rounded-2xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-950/50" @click.self="$el.close()"><div class="px-5 py-5"><h3 class="text-base font-extrabold text-slate-900">Simpan presensi?</h3><p class="mt-2 text-sm leading-6 text-slate-600">Data {{ $siswaList->count() }} siswa untuk {{ \Carbon\Carbon::parse($tanggal)->translatedFormat('d F Y') }} akan disimpan. Data yang sudah ada pada tanggal ini akan diperbarui.</p><div class="mt-5 flex justify-end gap-2"><button type="button" @click="$refs.confirmDialog.close()" class="min-h-10 rounded-lg border border-slate-300 px-4 text-xs font-bold text-slate-700">Batal</button><button type="button" @click="$refs.presensiForm.submit()" class="min-h-10 rounded-lg bg-sky-700 px-4 text-xs font-bold text-white">Ya, simpan</button></div></div></dialog>
        </section>

        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm" aria-labelledby="rekap-presensi-title">
            <div class="border-b border-slate-100 px-4 py-3"><h2 id="rekap-presensi-title" class="text-sm font-extrabold text-slate-900">Rekap kehadiran</h2><p class="mt-0.5 text-xs text-slate-500">{{ ($semester ?? false) ? 'Semester '.ucfirst($semester).' · '.($tahunAjaran->nama_tahun_ajaran ?? '') : \Carbon\Carbon::create($tahun, $bulan, 1)->locale('id')->translatedFormat('F Y') }}</p></div>
            <div class="divide-y divide-slate-100 lg:hidden">@forelse($siswaList as $siswa)@php($rekap = $rekapBulan[$siswa->id])<div class="px-4 py-3"><p class="text-xs font-bold text-slate-900">{{ $siswa->nama_lengkap }}</p><div class="mt-2 flex flex-wrap gap-1.5 text-[11px] font-bold"><span class="rounded-md bg-emerald-50 px-2 py-1 text-emerald-800">H {{ $rekap['hadir'] }}</span><span class="rounded-md bg-amber-50 px-2 py-1 text-amber-800">S {{ $rekap['sakit'] }}</span><span class="rounded-md bg-sky-50 px-2 py-1 text-sky-800">I {{ $rekap['izin'] }}</span><span class="rounded-md bg-rose-50 px-2 py-1 text-rose-800">A {{ $rekap['alpha'] }}</span><span class="rounded-md bg-slate-100 px-2 py-1 text-slate-700">Total {{ array_sum($rekap) }}</span></div></div>@empty<p class="px-4 py-8 text-center text-sm text-slate-500">Belum ada siswa untuk direkap.</p>@endforelse</div>
            <div class="hidden overflow-x-auto lg:block"><table class="w-full table-fixed text-left text-xs"><colgroup><col class="w-12"><col><col class="w-16"><col class="w-16"><col class="w-16"><col class="w-16"><col class="w-20"></colgroup><thead class="bg-slate-50 text-[11px] font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-2">No</th><th class="px-3 py-2">Siswa</th><th class="px-2 py-2 text-center">Hadir</th><th class="px-2 py-2 text-center">Sakit</th><th class="px-2 py-2 text-center">Izin</th><th class="px-2 py-2 text-center">Alpha</th><th class="px-2 py-2 text-center">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($siswaList as $index => $siswa)@php($rekap = $rekapBulan[$siswa->id])<tr><td class="px-4 py-2.5 text-slate-500">{{ $index + 1 }}</td><td class="truncate px-3 py-2.5 font-semibold text-slate-900" title="{{ $siswa->nama_lengkap }}">{{ $siswa->nama_lengkap }}</td><td class="px-2 py-2.5 text-center font-bold text-emerald-700">{{ $rekap['hadir'] }}</td><td class="px-2 py-2.5 text-center font-bold text-amber-700">{{ $rekap['sakit'] }}</td><td class="px-2 py-2.5 text-center font-bold text-sky-700">{{ $rekap['izin'] }}</td><td class="px-2 py-2.5 text-center font-bold text-rose-700">{{ $rekap['alpha'] }}</td><td class="px-2 py-2.5 text-center font-extrabold text-slate-900">{{ array_sum($rekap) }}</td></tr>@empty<tr><td colspan="7" class="px-4 py-8 text-center text-slate-500">Belum ada siswa untuk direkap.</td></tr>@endforelse</tbody></table></div>
        </section>

        <dialog x-ref="importDialog" class="w-[calc(100%-2rem)] max-w-lg rounded-2xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-950/50" @click.self="$el.close()">
            <div class="border-b border-slate-100 px-5 py-4"><div class="flex items-center justify-between gap-3"><h2 class="text-base font-extrabold text-slate-900">Impor presensi Excel</h2><button type="button" @click="$refs.importDialog.close()" class="flex h-8 w-8 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label="Tutup"><i class="fas fa-xmark" aria-hidden="true"></i></button></div><p class="mt-1 text-xs text-slate-500">Gunakan template sesuai siswa di kelas ini.</p></div>
            <form action="{{ route('wali.presensi.import-excel') }}" method="POST" enctype="multipart/form-data" class="space-y-4 px-5 py-4">@csrf<input type="hidden" name="kelas_id" value="{{ $kelas->id }}"><ol class="list-decimal space-y-1 rounded-lg bg-sky-50 px-6 py-3 text-xs leading-5 text-sky-900"><li>Unduh template yang sudah memuat NIS siswa.</li><li>Isi status: hadir, sakit, izin, atau alpha; keterangan opsional.</li><li>Jangan mengubah NIS, lalu unggah file yang telah diisi.</li></ol><label class="block text-xs font-bold text-slate-700">Tanggal presensi<input type="date" name="tanggal" value="{{ $tanggal }}" required class="mt-1 block h-10 w-full rounded-lg border border-slate-300 px-3 text-sm"></label><a href="{{ route('wali.presensi.download-template', ['tanggal' => $tanggal]) }}" class="inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-lg border border-emerald-300 bg-emerald-50 px-3 text-xs font-bold text-emerald-800 hover:bg-emerald-100"><i class="fas fa-download" aria-hidden="true"></i>Unduh template Excel</a><label class="block text-xs font-bold text-slate-700">File Excel atau CSV<input type="file" name="file_excel" accept=".csv,.xlsx,.xls" required class="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2 text-xs file:mr-3 file:rounded-md file:border-0 file:bg-slate-100 file:px-3 file:py-1.5 file:font-bold"></label><p class="text-xs text-slate-500">Format .csv, .xlsx, .xls; maksimal 2 MB.</p>@error('file_excel')<p class="text-xs text-rose-700">{{ $message }}</p>@enderror<div class="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" @click="$refs.importDialog.close()" class="min-h-10 rounded-lg border border-slate-300 px-4 text-xs font-bold text-slate-700">Batal</button><button type="submit" class="min-h-10 rounded-lg bg-emerald-700 px-4 text-xs font-bold text-white">Impor sekarang</button></div></form>
        </dialog>
    @endif
</div>
@endsection
