@startuml
title Sequence Diagram - UC24: Melihat Prediksi Kenaikan Kelas
autonumber

actor "Wali Kelas" as Wali
boundary "UI_PrediksiKenaikan" as UI
control "Control_Promotion" as Control
entity "T_Siswa" as E_Siswa
entity "T_Tagihan" as E_Tagihan
entity "T_Rapor" as E_Rapor

== Skenario: Menampilkan Laporan Prediksi Kenaikan ==

Wali -> UI : 1. Mengakses Menu "Prediksi Kenaikan Kelas"
activate UI
UI -> Control : 2. RequestPrediksiSiswa(Kelas)
activate Control

Control -> E_Siswa : 3. AmbilDaftarSiswaAktif()
activate E_Siswa
E_Siswa --> Control : 4. DataSiswaDitemukan(Array_ID)
deactivate E_Siswa

Control -> Control : 5. Memulai Evaluasi Kelayakan (Loop per Siswa)

par Evaluasi Status Keuangan
    Control -> E_Tagihan : 6. KalkulasiTotalTunggakan(ID_Siswa)
    activate E_Tagihan
    E_Tagihan --> Control : 7. Hasil(Lunas / Ada Tunggakan)
    deactivate E_Tagihan

    alt Jika Ada Tunggakan
        Control -> E_Tagihan : 8. CekDispensasiKhusus(ID_Siswa)
        activate E_Tagihan
        E_Tagihan --> Control : 9. StatusDispensasi(Disetujui / Kosong)
        deactivate E_Tagihan
    end
else Evaluasi Status Akademik
    Control -> E_Rapor : 10. TarikRataRataAkhir(ID_Siswa)
    activate E_Rapor
    E_Rapor --> Control : 11. DataNilaiSiswa()
    deactivate E_Rapor

    Control -> Control : 12. Cocokkan KKM & Hitung % Tuntas
end

Control -> Control : 13. Kalkulasi Kelayakan Akhir & Berikan Label (Aman / Rawan)

Control --> UI : 14. TampilkanTabelPrediksi(Data)
deactivate Control
UI --> Wali : 15. Halaman Laporan Terbuka (Tabel Analisis)
deactivate UI

== Skenario: Memfilter / Mencari Data ==

Wali -> UI : 16. Memasukkan Nama / Memilih Filter Status (Aman/Rawan)
activate UI
UI -> Control : 17. FilterDataPrediksi(Keyword, FilterStatus)
activate Control

Control -> E_Siswa : 18. ProsesPencarianNama(Keyword)
activate E_Siswa
E_Siswa --> Control : 19. HasilPencarian()
deactivate E_Siswa

Control -> Control : 20. FilterStatusOnMemory(FilterStatus)

Control --> UI : 21. TampilkanDataSesuaiFilter(Data)
deactivate Control
UI --> Wali : 22. Tabel Diperbarui Sesuai Filter
deactivate UI

@enduml
