@extends('layouts.app')

@section('title', isset($kalender) ? 'Edit Kegiatan' : 'Tambah Kegiatan')
@section('page-title', isset($kalender) ? 'Edit Kegiatan' : 'Tambah Kegiatan')
@section('page-subtitle', 'Jadwalkan agenda dan informasi kalender akademik')

@section('content')
@php
    $routeBase = request()->routeIs('sekretaris.*') ? 'sekretaris' : 'admin.akademik';
    $isEdit = isset($kalender);
    $types = ['field_trip' => 'Field Trip', 'outing' => 'Outing', 'live_in' => 'Live In', 'hokfest' => 'HOK Fest', 'pts' => 'PTS (Penilaian Tengah Semester)', 'pas' => 'PAS (Penilaian Akhir Semester)', 'libur' => 'Libur', 'ujian' => 'Ujian', 'acara_sekolah' => 'Acara Sekolah'];
    $storedType = old('jenis_kegiatan', $kalender->jenis_kegiatan ?? '');
    $selectedType = array_key_exists($storedType, $types) ? $storedType : ($storedType !== '' ? 'lainnya' : '');
    $customType = old('custom_jenis_kegiatan', $selectedType === 'lainnya' ? $storedType : '');
    $inputClass = 'mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20';
@endphp

<div class="min-w-0 w-full">
    <div class="mb-4 flex items-center gap-3"><a href="{{ url()->previous(route($routeBase . '.kalender.index')) }}" class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-700 no-underline hover:bg-slate-200" aria-label="Kembali"><i class="fas fa-arrow-left" aria-hidden="true"></i></a><div class="min-w-0"><h2 class="text-base font-extrabold text-slate-900">{{ $isEdit ? 'Perbarui kegiatan' : 'Kegiatan baru' }}</h2><p class="mt-0.5 text-xs text-slate-500">Kolom bertanda bintang wajib diisi.</p></div></div>

    @if($errors->any())<section class="mb-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-xs text-red-800"><p class="font-extrabold"><i class="fas fa-exclamation-circle mr-1.5" aria-hidden="true"></i>Periksa kembali data berikut:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif

    <form action="{{ $isEdit ? route($routeBase . '.kalender.update', $kalender->id) : route($routeBase . '.kalender.store') }}" method="POST" enctype="multipart/form-data" class="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_320px]" x-data="{ type: @js($selectedType) }">
        @csrf
        @if($isEdit) @method('PUT') @endif
        <input type="hidden" name="_return_url" value="{{ url()->previous(route($routeBase . '.kalender.index')) }}">

        <section class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <header class="border-b border-slate-200 p-4 sm:p-5"><h3 class="flex items-center gap-2 text-sm font-extrabold text-slate-900"><i class="fas fa-calendar-plus text-brand-600" aria-hidden="true"></i>Informasi kegiatan</h3><p class="mt-1 text-xs text-slate-500">Tanggal dan status menentukan kapan agenda terlihat pada kalender.</p></header>
            <div class="grid gap-5 p-4 sm:p-5">
                <label class="block text-xs font-bold text-slate-700">Nama kegiatan <span class="text-red-500">*</span><input type="text" name="nama_kegiatan" value="{{ old('nama_kegiatan', $kalender->nama_kegiatan ?? '') }}" maxlength="255" required placeholder="Contoh: Field Trip ke Museum" class="{{ $inputClass }} @error('nama_kegiatan') !border-red-400 @enderror">@error('nama_kegiatan')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label>

                <div class="grid gap-4 sm:grid-cols-2"><label class="block text-xs font-bold text-slate-700">Jenis kegiatan <span class="text-red-500">*</span><select name="jenis_kegiatan" x-model="type" required class="{{ $inputClass }} @error('jenis_kegiatan') !border-red-400 @enderror"><option value="">Pilih jenis kegiatan</option>@foreach($types as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach<option value="lainnya">Lainnya</option></select>@error('jenis_kegiatan')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label><label x-show="type === 'lainnya'" x-cloak class="block text-xs font-bold text-slate-700">Jenis kegiatan kustom <span class="text-red-500">*</span><input type="text" name="custom_jenis_kegiatan" value="{{ $customType }}" maxlength="50" :required="type === 'lainnya'" placeholder="Contoh: Pelatihan Guru" class="{{ $inputClass }} @error('custom_jenis_kegiatan') !border-red-400 @enderror">@error('custom_jenis_kegiatan')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label></div>

                <div class="grid gap-4 sm:grid-cols-2"><label class="block text-xs font-bold text-slate-700">Tanggal mulai <span class="text-red-500">*</span><input type="date" name="tanggal_mulai" value="{{ old('tanggal_mulai', $isEdit ? $kalender->tanggal_mulai?->format('Y-m-d') : request('tanggal')) }}" required class="{{ $inputClass }} @error('tanggal_mulai') !border-red-400 @enderror">@error('tanggal_mulai')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label><label class="block text-xs font-bold text-slate-700">Tanggal selesai <span class="font-normal text-slate-400">(opsional)</span><input type="date" name="tanggal_selesai" value="{{ old('tanggal_selesai', $isEdit ? $kalender->tanggal_selesai?->format('Y-m-d') : '') }}" class="{{ $inputClass }} @error('tanggal_selesai') !border-red-400 @enderror"><span class="mt-1.5 block text-[11px] font-normal text-slate-500">Kosongkan untuk kegiatan satu hari.</span>@error('tanggal_selesai')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label></div>

                <div class="grid gap-4 sm:grid-cols-2"><label class="block text-xs font-bold text-slate-700">Waktu mulai <span class="font-normal text-slate-400">(opsional)</span><input type="time" name="waktu_mulai" value="{{ old('waktu_mulai', $kalender->waktu_mulai ?? '') }}" class="{{ $inputClass }} @error('waktu_mulai') !border-red-400 @enderror">@error('waktu_mulai')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label><label class="block text-xs font-bold text-slate-700">Waktu selesai <span class="font-normal text-slate-400">(opsional)</span><input type="time" name="waktu_selesai" value="{{ old('waktu_selesai', $kalender->waktu_selesai ?? '') }}" class="{{ $inputClass }} @error('waktu_selesai') !border-red-400 @enderror">@error('waktu_selesai')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label></div>

                <label class="block text-xs font-bold text-slate-700">Keterangan <span class="font-normal text-slate-400">(opsional)</span><textarea name="keterangan" rows="4" placeholder="Lokasi, peserta, atau informasi tambahan..." class="mt-1.5 min-h-28 w-full resize-y rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm text-slate-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 @error('keterangan') !border-red-400 @enderror">{{ old('keterangan', $kalender->keterangan ?? '') }}</textarea>@error('keterangan')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label>

                <label class="block text-xs font-bold text-slate-700">Lampiran surat <span class="font-normal text-slate-400">(PDF, maks. 5 MB)</span>@if($isEdit && $kalender->lampiran_surat)<a href="{{ asset('storage/' . $kalender->lampiran_surat) }}" target="_blank" class="mt-2 flex w-fit items-center gap-2 rounded-lg bg-brand-50 px-3 py-2 text-[11px] font-bold text-brand-700 no-underline hover:bg-brand-100"><i class="fas fa-file-pdf" aria-hidden="true"></i>Lihat lampiran saat ini</a>@endif<input type="file" name="lampiran_surat" accept=".pdf,application/pdf" class="mt-2 block w-full rounded-xl border border-slate-200 bg-white text-xs text-slate-600 file:mr-3 file:border-0 file:bg-slate-100 file:px-4 file:py-3 file:text-xs file:font-bold file:text-slate-700 hover:file:bg-slate-200 @error('lampiran_surat') !border-red-400 @enderror">@error('lampiran_surat')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label>

                <label class="block text-xs font-bold text-slate-700 sm:max-w-xs">Status <span class="text-red-500">*</span><select name="status" required class="{{ $inputClass }} @error('status') !border-red-400 @enderror">@foreach(['aktif' => 'Aktif', 'draft' => 'Draft', 'selesai' => 'Selesai'] as $value => $label)<option value="{{ $value }}" {{ old('status', $kalender->status ?? 'aktif') === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select>@error('status')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label>
            </div>
            <footer class="flex flex-col-reverse gap-2 border-t border-slate-200 bg-slate-50/70 p-4 sm:flex-row sm:justify-end"><a href="{{ url()->previous(route($routeBase . '.kalender.index')) }}" class="inline-flex h-11 items-center justify-center rounded-xl bg-white px-5 text-xs font-bold text-slate-700 no-underline ring-1 ring-inset ring-slate-200 hover:bg-slate-100">Batal</a><button type="submit" class="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-brand-600 px-5 text-xs font-bold text-white hover:bg-brand-700"><i class="fas fa-save" aria-hidden="true"></i>{{ $isEdit ? 'Simpan perubahan' : 'Simpan kegiatan' }}</button></footer>
        </section>

        <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5 xl:sticky xl:top-24"><h3 class="flex items-center gap-2 text-sm font-extrabold text-slate-900"><i class="fas fa-lightbulb text-amber-500" aria-hidden="true"></i>Alur publikasi</h3><ol class="mt-4 space-y-4 text-xs leading-5 text-slate-600"><li class="flex gap-3"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-brand-50 text-[10px] font-extrabold text-brand-700">1</span><span>Isi agenda dan pilih Draft bila tanggal belum final.</span></li><li class="flex gap-3"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-brand-50 text-[10px] font-extrabold text-brand-700">2</span><span>Status Aktif menampilkan kegiatan pada kalender pengguna.</span></li><li class="flex gap-3"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-brand-50 text-[10px] font-extrabold text-brand-700">3</span><span>Pengumuman pengingat dapat dibuat otomatis tiga hari sebelum kegiatan.</span></li></ol><div class="mt-5 rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-800"><i class="fas fa-clock mr-1" aria-hidden="true"></i>Kosongkan jam untuk kegiatan sepanjang hari.</div></aside>
    </form>
</div>
@endsection
