@extends('layouts.print')
@section('title', 'Rekap Statistik Sekolah')
@section('back-url', route($backRoute ?? 'admin.laporan.index'))
@section('document-width', 'min-w-[900px]')
@section('report-title', 'Rekap Statistik Sekolah')
@section('report-meta')<p class="mt-1 text-[10px] text-slate-600 print:text-[8pt]">Tahun Ajaran <strong>{{ $tahunAjaran->nama_tahun_ajaran ?? '-' }}</strong></p>@endsection
@section('report-content')
<section class="mb-5 grid grid-cols-3 divide-x divide-slate-300 border border-slate-300 text-center print:mb-4">@foreach([['Siswa aktif',$summary['total_siswa']],['Tenaga pendidik',$summary['total_guru']],['Kelas aktif',$summary['total_kelas']]] as [$label,$value])<div class="p-3"><strong class="block text-base">{{ $value }}</strong><span class="text-[9px] uppercase text-slate-500">{{ $label }}</span></div>@endforeach</section>
<h2 class="mb-2 border-b border-slate-300 pb-1 text-[10px] font-extrabold uppercase">Rekap per cabang</h2><table class="w-full table-fixed border-collapse text-[9px] print:text-[7pt]"><colgroup><col class="w-8"><col><col class="w-20"><col class="w-20"><col class="w-20"><col class="w-20"></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 p-2">No</th><th class="border border-slate-400 p-2 text-left">Cabang</th><th class="border border-slate-400 p-2">Kelas</th><th class="border border-slate-400 p-2">L</th><th class="border border-slate-400 p-2">P</th><th class="border border-slate-400 p-2">Siswa</th></tr></thead><tbody>@foreach($cabangs as $branch)<tr><td class="border border-slate-300 p-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 p-2 font-bold">{{ $branch->nama_cabang }}</td><td class="border border-slate-300 p-2 text-center">{{ $branch->total_kelas }}</td><td class="border border-slate-300 p-2 text-center">{{ $branch->siswa_l }}</td><td class="border border-slate-300 p-2 text-center">{{ $branch->siswa_p }}</td><td class="border border-slate-300 p-2 text-center font-bold">{{ $branch->total_siswa }}</td></tr>@endforeach</tbody></table>
<h2 class="mb-2 mt-5 border-b border-slate-300 pb-1 text-[10px] font-extrabold uppercase">Rekap per jenjang</h2><table class="w-full table-fixed border-collapse text-[9px] print:text-[7pt]"><colgroup><col class="w-8"><col><col class="w-20"><col class="w-20"><col class="w-20"><col class="w-20"></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 p-2">No</th><th class="border border-slate-400 p-2 text-left">Jenjang</th><th class="border border-slate-400 p-2">Kelas</th><th class="border border-slate-400 p-2">L</th><th class="border border-slate-400 p-2">P</th><th class="border border-slate-400 p-2">Siswa</th></tr></thead><tbody>@foreach($jenjangStats as $level => $item)<tr><td class="border border-slate-300 p-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 p-2 font-bold">{{ $level }}</td><td class="border border-slate-300 p-2 text-center">{{ $item['total_kelas'] }}</td><td class="border border-slate-300 p-2 text-center">{{ $item['siswa_l'] }}</td><td class="border border-slate-300 p-2 text-center">{{ $item['siswa_p'] }}</td><td class="border border-slate-300 p-2 text-center font-bold">{{ $item['total_siswa'] }}</td></tr>@endforeach</tbody></table>
@endsection
