@extends('layouts.print')
@section('title', 'Rekap Akademik per Tahun Ajaran')
@section('back-url', route($backRoute ?? 'admin.cetak-laporan.index'))
@section('document-width', 'min-w-[1020px]')
@section('report-title', 'Rekap Akademik per Tahun Ajaran')
@section('report-meta')<p class="mt-1 text-[10px] text-slate-600 print:text-[8pt]">Tahun Ajaran <strong>{{ $tahunAjaran->nama_tahun_ajaran }}</strong> · {{ $cabang ? $cabang->nama_cabang : 'Semua cabang' }}</p>@endsection
@section('report-content')
<section class="mb-5 grid grid-cols-5 divide-x divide-slate-300 border border-slate-300 text-center print:mb-4">@foreach([['Total',$stats['total']],['Naik kelas',$stats['naik']],['Tidak naik',$stats['tidak_naik']],['Lulus',$stats['lulus']],['Dispensasi',$stats['dispensasi']]] as [$label,$value])<div class="p-2"><strong class="block text-sm">{{ $value }}</strong><span class="text-[8px] uppercase text-slate-500">{{ $label }}</span></div>@endforeach</section>
@php $sections = ['NAIK_KELAS' => 'Naik Kelas', 'NAIK_KELAS_TUNGGAKAN' => 'Naik Kelas via Dispensasi/Tunggakan', 'TIDAK_NAIK_KELAS' => 'Tidak Naik Kelas', 'LULUS' => 'Lulus', 'LULUS_TUNGGAKAN' => 'Lulus via Dispensasi/Tunggakan']; @endphp
@foreach($sections as $status => $label)@php $rows = $byStatus->get($status, collect()); $withDispensation = in_array($status, ['NAIK_KELAS_TUNGGAKAN','LULUS_TUNGGAKAN']); @endphp<section class="mb-5 break-inside-avoid"><h2 class="mb-2 border-b border-slate-300 pb-1 text-[10px] font-extrabold uppercase">{{ $label }} ({{ $rows->count() }})</h2>@if($rows->isEmpty())<p class="border border-slate-200 bg-slate-50 p-3 text-center text-[9px] text-slate-500">Tidak ada siswa pada kategori ini.</p>@else<table class="w-full table-fixed border-collapse text-[8px] print:text-[6.5pt]"><colgroup><col class="w-8"><col><col class="w-28"><col class="w-40"><col class="w-16"><col class="w-24">@if($withDispensation)<col class="w-16">@endif</colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 p-2">No</th><th class="border border-slate-400 p-2 text-left">Nama</th><th class="border border-slate-400 p-2">NIS / NISN</th><th class="border border-slate-400 p-2">Kelas asal → tujuan</th><th class="border border-slate-400 p-2">Tuntas</th><th class="border border-slate-400 p-2">Pembayaran</th>@if($withDispensation)<th class="border border-slate-400 p-2">Dispensasi</th>@endif</tr></thead><tbody>@foreach($rows as $row)<tr><td class="border border-slate-300 p-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 p-2 font-bold">{{ $row->siswa?->nama_lengkap ?? '-' }}</td><td class="border border-slate-300 p-2 text-center">{{ $row->siswa?->nis ?? '-' }}<span class="block text-slate-500">{{ $row->siswa?->nisn ?? '' }}</span></td><td class="border border-slate-300 p-2 text-center">{{ $row->kelas_asal ?? '-' }}{{ $row->kelas_tujuan ? ' → '.$row->kelas_tujuan : '' }}</td><td class="border border-slate-300 p-2 text-center">{{ number_format((float) ($row->persentase_nilai_tuntas ?? 0), 1) }}%</td><td class="border border-slate-300 p-2 text-center">{{ $row->status_pembayaran ?? '-' }}</td>@if($withDispensation)<td class="border border-slate-300 p-2 text-center">{{ $row->izin_khusus_ketua ? 'Ya' : '-' }}</td>@endif</tr>@endforeach</tbody></table>@endif</section>@endforeach
@endsection
