@extends('layouts.print')
@section('title', 'Daftar Kelas')
@section('back-url', route($backRoute ?? 'admin.laporan.index'))
@section('document-width', 'min-w-[940px]')
@section('report-title', 'Daftar Kelas')
@section('report-meta')<p class="mt-1 text-[10px] text-slate-600 print:text-[8pt]">Tahun Ajaran <strong>{{ $tahunAjaran->nama_tahun_ajaran ?? '-' }}</strong> · {{ $cabang ? $cabang->nama_cabang : 'Semua cabang' }}</p>@endsection
@section('report-content')
<table class="w-full table-fixed border-collapse text-[9px] leading-4 print:text-[7pt]"><colgroup><col class="w-8"><col class="w-[14%]"><col class="w-[13%]"><col class="w-[19%]"><col><col class="w-14"><col class="w-14"></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 px-2 py-2">No</th><th class="border border-slate-400 px-2 py-2">Kode</th><th class="border border-slate-400 px-2 py-2">Kelas</th><th class="border border-slate-400 px-2 py-2 text-left">Cabang</th><th class="border border-slate-400 px-2 py-2 text-left">Wali kelas</th><th class="border border-slate-400 px-2 py-2">Siswa</th><th class="border border-slate-400 px-2 py-2">Kuota</th></tr></thead><tbody>@forelse($kelasList as $class)<tr class="break-inside-avoid"><td class="border border-slate-300 px-2 py-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $class->kode_kelas }}</td><td class="border border-slate-300 px-2 py-2 text-center font-bold">{{ $class->nama_kelas }} · {{ $class->jenjang }}</td><td class="border border-slate-300 px-2 py-2">{{ $class->cabang->nama_cabang ?? '-' }}</td><td class="border border-slate-300 px-2 py-2">{{ $class->waliKelas->nama_lengkap ?? '-' }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $class->siswa_count }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $class->kuota_siswa }}</td></tr>@empty<tr><td colspan="7" class="border border-slate-300 px-3 py-8 text-center text-slate-500">Tidak ada data kelas.</td></tr>@endforelse</tbody></table>
<p class="mt-4 border border-slate-300 bg-slate-50 p-3 text-[9px] print:text-[7pt]"><strong>{{ $kelasList->count() }}</strong> kelas · {{ $kelasList->sum('siswa_count') }} siswa · kapasitas {{ $kelasList->sum('kuota_siswa') }}</p>
@endsection
