@extends('layouts.print')
@section('title', 'Daftar Guru Pengajar')
@section('back-url', route($backRoute ?? 'admin.laporan.index'))
@section('document-width', 'min-w-[940px]')
@section('report-title', 'Daftar Guru Pengajar')
@section('report-meta')<p class="mt-1 text-[10px] text-slate-600 print:text-[8pt]">Tahun Ajaran <strong>{{ $tahunAjaran->nama_tahun_ajaran ?? '-' }}</strong></p>@endsection
@section('report-content')
<table class="w-full table-fixed border-collapse text-[9px] leading-4 print:text-[7pt]"><colgroup><col class="w-8"><col class="w-[24%]"><col class="w-28"><col class="w-28"><col></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 px-2 py-2">No</th><th class="border border-slate-400 px-2 py-2 text-left">Nama guru</th><th class="border border-slate-400 px-2 py-2">NIP</th><th class="border border-slate-400 px-2 py-2">Telepon</th><th class="border border-slate-400 px-2 py-2 text-left">Penugasan kelas · mata pelajaran</th></tr></thead><tbody>@forelse($guruList as $teacher)<tr class="break-inside-avoid"><td class="border border-slate-300 px-2 py-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 px-2 py-2 font-bold">{{ $teacher->nama_lengkap }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $teacher->nip ?: '-' }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $teacher->telepon ?: '-' }}</td><td class="border border-slate-300 px-2 py-2">@forelse($teacher->guruKelas as $assignment)<span class="block">{{ $assignment->kelas->nama_kelas ?? '-' }} · {{ $assignment->mataPelajaran->nama_mapel ?? '-' }}</span>@empty<span class="italic text-slate-500">Belum ada penugasan</span>@endforelse</td></tr>@empty<tr><td colspan="5" class="border border-slate-300 px-3 py-8 text-center text-slate-500">Tidak ada data guru pengajar.</td></tr>@endforelse</tbody></table>
<p class="mt-4 border border-slate-300 bg-slate-50 p-3 text-[9px] print:text-[7pt]"><strong>{{ $guruList->count() }}</strong> guru · {{ $guruList->sum(fn ($teacher) => $teacher->guruKelas->count()) }} penugasan</p>
@endsection
