@extends('layouts.print')
@section('title', 'Daftar Tenaga Pendidik')
@section('back-url', route($backRoute ?? 'admin.laporan.index'))
@section('document-width', 'min-w-[940px]')
@section('report-title', 'Daftar Tenaga Pendidik')
@section('report-meta')<p class="mt-1 text-[10px] text-slate-600 print:text-[8pt]">{{ $roleFilter ? 'Peran '.ucwords(str_replace('_', ' ', $roleFilter)) : 'Semua peran' }}</p>@endsection
@section('report-content')
<table class="w-full table-fixed border-collapse text-[9px] leading-4 print:text-[7pt]"><colgroup><col class="w-8"><col class="w-28"><col class="w-[24%]"><col class="w-9"><col class="w-28"><col class="w-[18%]"><col class="w-[16%]"></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 px-2 py-2">No</th><th class="border border-slate-400 px-2 py-2">NIP</th><th class="border border-slate-400 px-2 py-2 text-left">Nama lengkap</th><th class="border border-slate-400 px-2 py-2">JK</th><th class="border border-slate-400 px-2 py-2">Telepon</th><th class="border border-slate-400 px-2 py-2">Pendidikan</th><th class="border border-slate-400 px-2 py-2">Peran</th></tr></thead><tbody>@forelse($guruList as $teacher)<tr class="break-inside-avoid"><td class="border border-slate-300 px-2 py-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $teacher->nip ?: '-' }}</td><td class="border border-slate-300 px-2 py-2 font-bold">{{ $teacher->nama_lengkap }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $teacher->jenis_kelamin }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $teacher->telepon ?: '-' }}</td><td class="border border-slate-300 px-2 py-2">{{ $teacher->pendidikan_terakhir ?: '-' }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ ucwords(str_replace('_', ' ', $teacher->user->role ?? '-')) }}</td></tr>@empty<tr><td colspan="7" class="border border-slate-300 px-3 py-8 text-center text-slate-500">Tidak ada data tenaga pendidik.</td></tr>@endforelse</tbody></table>
<p class="mt-4 border border-slate-300 bg-slate-50 p-3 text-[9px] print:text-[7pt]"><strong>{{ $guruList->count() }}</strong> tenaga pendidik · {{ $guruList->where('jenis_kelamin', 'L')->count() }} laki-laki · {{ $guruList->where('jenis_kelamin', 'P')->count() }} perempuan</p>
@endsection
