@extends('layouts.print')
@section('title', 'Daftar Siswa')
@section('back-url', route($backRoute ?? 'admin.laporan.index'))
@section('document-width', 'min-w-[980px]')
@section('report-title', 'Daftar Siswa')
@section('report-meta')
<p class="mt-1 text-[10px] text-slate-600 print:text-[8pt]">Tahun Ajaran <strong>{{ $tahunAjaran->nama_tahun_ajaran ?? '-' }}</strong> · {{ $kelas ? 'Kelas '.$kelas->nama_kelas : 'Semua kelas' }} · {{ $cabang ? $cabang->nama_cabang : 'Semua cabang' }}</p>
@if($isHistorical ?? false)<p class="mt-1 text-[9px] font-bold text-amber-700 print:text-[7pt]">Data historis berdasarkan snapshot tahun ajaran terpilih.</p>@endif
@endsection
@section('report-content')
<table class="w-full table-fixed border-collapse text-[9px] leading-4 print:text-[7pt]"><colgroup><col class="w-8"><col class="w-28"><col class="w-24"><col class="w-[23%]"><col class="w-9"><col class="w-[22%]">@unless($kelas)<col class="w-[14%]">@endunless</colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 px-2 py-2">No</th><th class="border border-slate-400 px-2 py-2">NISN</th><th class="border border-slate-400 px-2 py-2">NIS</th><th class="border border-slate-400 px-2 py-2 text-left">Nama lengkap</th><th class="border border-slate-400 px-2 py-2">JK</th><th class="border border-slate-400 px-2 py-2 text-left">Tempat, tanggal lahir</th>@unless($kelas)<th class="border border-slate-400 px-2 py-2">Kelas</th>@endunless</tr></thead><tbody>
@forelse($siswaList as $student)@php $className = ($isHistorical ?? false) ? ($student->kelas_snapshot_nama ?? '-') : ($student->kelas->nama_kelas ?? '-'); @endphp<tr class="break-inside-avoid"><td class="border border-slate-300 px-2 py-2 text-center">{{ $loop->iteration }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $student->nisn ?: '-' }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $student->nis ?: '-' }}</td><td class="border border-slate-300 px-2 py-2 font-bold">{{ $student->nama_lengkap }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $student->jenis_kelamin }}</td><td class="border border-slate-300 px-2 py-2">{{ $student->tempat_lahir ?: '-' }}, {{ $student->tanggal_lahir?->format('d/m/Y') ?? '-' }}</td>@unless($kelas)<td class="border border-slate-300 px-2 py-2 text-center">{{ $className }}@if($isHistorical ?? false)<span class="block text-[7px] text-slate-500">{{ str_replace('_', ' ', $student->status_kelulusan_snapshot ?? '') }}</span>@endif</td>@endunless</tr>@empty<tr><td colspan="{{ $kelas ? 6 : 7 }}" class="border border-slate-300 px-3 py-8 text-center text-slate-500">Tidak ada data siswa sesuai filter.</td></tr>@endforelse
</tbody></table>
<section class="mt-4 grid grid-cols-3 divide-x divide-slate-300 border border-slate-300 text-center text-[9px] print:text-[7pt]"><div class="p-2"><span class="block text-slate-500">Total</span><strong>{{ $siswaList->count() }}</strong></div><div class="p-2"><span class="block text-slate-500">Laki-laki</span><strong>{{ $siswaList->where('jenis_kelamin', 'L')->count() }}</strong></div><div class="p-2"><span class="block text-slate-500">Perempuan</span><strong>{{ $siswaList->where('jenis_kelamin', 'P')->count() }}</strong></div></section>
@endsection
