@extends('layouts.print')

@section('title', 'Rekap Tagihan per Kelas')
@section('back-url', route(request()->routeIs('bendahara.*') ? 'bendahara.laporan.rekap-tagihan' : 'admin.keuangan.laporan.rekap-tagihan'))
@section('document-width', 'min-w-[940px]')
@section('report-title', 'Rekap Tagihan per Kelas')

@section('report-meta')
    <p class="mt-1 text-[10px] text-slate-600 print:text-[8pt]">Tahun Ajaran <strong>{{ $tahunAjaran->nama_tahun_ajaran ?? '-' }}</strong></p>
@endsection

@section('report-content')
    <section class="mb-5 grid grid-cols-3 divide-x divide-slate-300 border border-slate-300 print:mb-4">@foreach([['Total tagihan',$grandTotal['tagihan']],['Total terbayar',$grandTotal['bayar']],['Total sisa',$grandTotal['sisa']]] as [$label,$value])<div class="p-3"><span class="block text-[9px] font-bold uppercase text-slate-500">{{ $label }}</span><strong class="mt-1 block text-sm tabular-nums">Rp {{ number_format($value, 0, ',', '.') }}</strong></div>@endforeach</section>
    <table class="w-full table-fixed border-collapse text-[9px] leading-4 print:text-[7pt]"><colgroup><col class="w-8"><col class="w-[12%]"><col class="w-[18%]"><col class="w-[9%]"><col class="w-[14%]"><col class="w-[14%]"><col class="w-[14%]"><col class="w-[10%]"></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 px-2 py-2">No</th><th class="border border-slate-400 px-2 py-2">Kelas</th><th class="border border-slate-400 px-2 py-2 text-left">Cabang</th><th class="border border-slate-400 px-2 py-2">Siswa</th><th class="border border-slate-400 px-2 py-2 text-right">Tagihan</th><th class="border border-slate-400 px-2 py-2 text-right">Terbayar</th><th class="border border-slate-400 px-2 py-2 text-right">Sisa</th><th class="border border-slate-400 px-2 py-2">Progres</th></tr></thead><tbody>@forelse($kelasList as $index => $kelas)<tr class="break-inside-avoid"><td class="border border-slate-300 px-2 py-2 text-center">{{ $index + 1 }}</td><td class="border border-slate-300 px-2 py-2 text-center font-bold">{{ $kelas->nama_kelas }} · {{ $kelas->jenjang }}</td><td class="border border-slate-300 px-2 py-2">{{ $kelas->cabang->nama_cabang ?? '-' }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $kelas->total_siswa }}</td><td class="border border-slate-300 px-2 py-2 text-right tabular-nums">Rp {{ number_format($kelas->total_tagihan, 0, ',', '.') }}</td><td class="border border-slate-300 px-2 py-2 text-right tabular-nums">Rp {{ number_format($kelas->total_bayar, 0, ',', '.') }}</td><td class="border border-slate-300 px-2 py-2 text-right font-bold tabular-nums">Rp {{ number_format($kelas->sisa_tagihan, 0, ',', '.') }}</td><td class="border border-slate-300 px-2 py-2 text-center font-bold">{{ $kelas->persentase }}%</td></tr>@empty<tr><td colspan="8" class="border border-slate-300 px-3 py-8 text-center text-slate-500">Belum ada data kelas pada periode aktif.</td></tr>@endforelse</tbody><tfoot class="bg-slate-100"><tr><th colspan="4" class="border border-slate-400 px-2 py-2 text-right">GRAND TOTAL</th><td class="border border-slate-400 px-2 py-2 text-right font-extrabold tabular-nums">Rp {{ number_format($grandTotal['tagihan'], 0, ',', '.') }}</td><td class="border border-slate-400 px-2 py-2 text-right font-extrabold tabular-nums">Rp {{ number_format($grandTotal['bayar'], 0, ',', '.') }}</td><td class="border border-slate-400 px-2 py-2 text-right font-extrabold tabular-nums">Rp {{ number_format($grandTotal['sisa'], 0, ',', '.') }}</td><td class="border border-slate-400"></td></tr></tfoot></table>
@endsection
