@extends('layouts.print')

@section('title', 'Laporan Siswa Belum Lunas')
@section('back-url', route(request()->routeIs('bendahara.*') ? 'bendahara.laporan.belum-lunas' : 'admin.keuangan.laporan.belum-lunas', request()->query()))
@section('document-width', 'min-w-[980px]')
@section('report-title', 'Laporan Siswa Belum Lunas')

@section('report-meta')
    <div class="mt-1 text-[10px] leading-4 text-slate-600 print:text-[8pt]"><p>Tahun Ajaran: <strong>{{ $tahunAjaran->nama_tahun_ajaran ?? '-' }}</strong></p><p>Kelas: <strong>{{ $kelas ? $kelas->nama_kelas.' · '.$kelas->jenjang : 'Semua kelas' }}</strong></p></div>
@endsection

@section('report-content')
    @php $totalTagihan = $siswaList->sum('total_tagihan'); $totalBayar = $siswaList->sum('total_bayar'); $totalSisa = $siswaList->sum('sisa_tagihan'); @endphp
    <section class="mb-5 grid grid-cols-4 divide-x divide-slate-300 border border-slate-300 print:mb-4"><div class="p-3"><span class="block text-[9px] font-bold uppercase text-slate-500">Jumlah siswa</span><strong class="mt-1 block text-sm">{{ $siswaList->count() }} siswa</strong></div>@foreach([['Total tagihan',$totalTagihan],['Total terbayar',$totalBayar],['Total sisa',$totalSisa]] as [$label,$value])<div class="p-3"><span class="block text-[9px] font-bold uppercase text-slate-500">{{ $label }}</span><strong class="mt-1 block text-sm tabular-nums">Rp {{ number_format($value, 0, ',', '.') }}</strong></div>@endforeach</section>
    <table class="w-full table-fixed border-collapse text-[9px] leading-4 print:text-[7pt]"><colgroup><col class="w-8"><col class="w-[19%]"><col class="w-[12%]"><col class="w-[10%]"><col class="w-[18%]"><col class="w-[14%]"><col class="w-[14%]"><col class="w-[14%]"></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 px-2 py-2">No</th><th class="border border-slate-400 px-2 py-2 text-left">Siswa</th><th class="border border-slate-400 px-2 py-2">NISN</th><th class="border border-slate-400 px-2 py-2">Kelas</th><th class="border border-slate-400 px-2 py-2 text-left">Cabang</th><th class="border border-slate-400 px-2 py-2 text-right">Tagihan</th><th class="border border-slate-400 px-2 py-2 text-right">Terbayar</th><th class="border border-slate-400 px-2 py-2 text-right">Sisa</th></tr></thead><tbody>@forelse($siswaList as $index => $student)<tr class="break-inside-avoid"><td class="border border-slate-300 px-2 py-2 text-center">{{ $index + 1 }}</td><td class="border border-slate-300 px-2 py-2 font-bold">{{ $student->nama_lengkap }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $student->nisn ?: '-' }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $student->kelas->nama_kelas ?? '-' }}</td><td class="border border-slate-300 px-2 py-2">{{ $student->cabang->nama_cabang ?? '-' }}</td><td class="border border-slate-300 px-2 py-2 text-right tabular-nums">Rp {{ number_format($student->total_tagihan, 0, ',', '.') }}</td><td class="border border-slate-300 px-2 py-2 text-right tabular-nums">Rp {{ number_format($student->total_bayar, 0, ',', '.') }}</td><td class="border border-slate-300 px-2 py-2 text-right font-extrabold tabular-nums text-red-700">Rp {{ number_format($student->sisa_tagihan, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="8" class="border border-slate-300 px-3 py-8 text-center text-slate-500">Tidak ada siswa dengan sisa tagihan.</td></tr>@endforelse</tbody><tfoot class="bg-slate-100"><tr><th colspan="5" class="border border-slate-400 px-2 py-2 text-right">GRAND TOTAL</th><td class="border border-slate-400 px-2 py-2 text-right font-extrabold tabular-nums">Rp {{ number_format($totalTagihan, 0, ',', '.') }}</td><td class="border border-slate-400 px-2 py-2 text-right font-extrabold tabular-nums">Rp {{ number_format($totalBayar, 0, ',', '.') }}</td><td class="border border-slate-400 px-2 py-2 text-right font-extrabold tabular-nums">Rp {{ number_format($totalSisa, 0, ',', '.') }}</td></tr></tfoot></table>
@endsection
