@extends('layouts.print')

@section('title', 'Laporan Pembayaran '.$namaBulan.' '.$tahun)
@section('back-url', route(request()->routeIs('bendahara.*') ? 'bendahara.laporan.index' : 'admin.keuangan.laporan.index', request()->query()))
@section('document-width', 'min-w-[980px]')
@section('report-title', 'Laporan Pembayaran Bulanan')

@section('report-meta')
    <div class="mt-1 text-[10px] leading-4 text-slate-600 print:text-[8pt]"><p>Periode: <strong>{{ $namaBulan }} {{ $tahun }}</strong></p><p>Kelas: <strong>{{ $kelas ? $kelas->nama_kelas.' · '.$kelas->jenjang : 'Semua kelas' }}</strong></p></div>
@endsection

@section('report-content')
    <section class="mb-5 grid grid-cols-2 divide-x divide-slate-300 border border-slate-300 print:mb-4"><div class="p-3"><span class="block text-[9px] font-bold uppercase text-slate-500">Transaksi disetujui</span><strong class="mt-1 block text-sm">{{ $pembayaranList->count() }} transaksi</strong></div><div class="p-3"><span class="block text-[9px] font-bold uppercase text-slate-500">Total penerimaan</span><strong class="mt-1 block text-sm tabular-nums">Rp {{ number_format($totalBulanIni, 0, ',', '.') }}</strong></div></section>
    <table class="w-full table-fixed border-collapse text-[9px] leading-4 print:text-[7pt]"><colgroup><col class="w-8"><col class="w-20"><col class="w-[18%]"><col class="w-[9%]"><col class="w-[17%]"><col class="w-[13%]"><col class="w-[12%]"><col class="w-[13%]"></colgroup><thead class="bg-slate-100"><tr><th class="border border-slate-400 px-2 py-2">No</th><th class="border border-slate-400 px-2 py-2">Tanggal</th><th class="border border-slate-400 px-2 py-2 text-left">Siswa</th><th class="border border-slate-400 px-2 py-2">Kelas</th><th class="border border-slate-400 px-2 py-2 text-left">Jenis tagihan</th><th class="border border-slate-400 px-2 py-2 text-right">Jumlah</th><th class="border border-slate-400 px-2 py-2">Metode</th><th class="border border-slate-400 px-2 py-2 text-left">Validator</th></tr></thead><tbody>@forelse($pembayaranList as $index => $payment)<tr class="break-inside-avoid"><td class="border border-slate-300 px-2 py-2 text-center">{{ $index + 1 }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $payment->tanggal_bayar?->format('d/m/Y') ?? '-' }}</td><td class="border border-slate-300 px-2 py-2 font-bold">{{ $payment->siswa->nama_lengkap ?? '-' }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $payment->siswa->kelas->nama_kelas ?? '-' }}</td><td class="border border-slate-300 px-2 py-2">{{ $payment->tagihan ? ucwords(str_replace('_', ' ', $payment->tagihan->jenis_tagihan)) : '-' }}</td><td class="border border-slate-300 px-2 py-2 text-right font-bold tabular-nums">Rp {{ number_format($payment->jumlah_bayar, 0, ',', '.') }}</td><td class="border border-slate-300 px-2 py-2 text-center">{{ $payment->payment_channel_label }}</td><td class="border border-slate-300 px-2 py-2">{{ $payment->validator->name ?? '-' }}</td></tr>@empty<tr><td colspan="8" class="border border-slate-300 px-3 py-8 text-center text-slate-500">Tidak ada pembayaran pada periode ini.</td></tr>@endforelse</tbody><tfoot class="bg-slate-100"><tr><th colspan="5" class="border border-slate-400 px-2 py-2 text-right">TOTAL</th><td class="border border-slate-400 px-2 py-2 text-right font-extrabold tabular-nums">Rp {{ number_format($totalBulanIni, 0, ',', '.') }}</td><td colspan="2" class="border border-slate-400"></td></tr></tfoot></table>
@endsection
