@extends('layouts.app')

@section('title', 'Laporan Pembayaran')
@section('page-title', 'Laporan Pembayaran Bulanan')
@section('page-subtitle', 'Rekap pembayaran periode ' . $bulanList[$bulan] . ' ' . $tahun)

@section('content')
@php
    $methodLabels = ['tunai' => 'Tunai', 'transfer' => 'Direct Transfer', 'paywuz' => 'Kanal Pembayaran'];
    $classOptions = $kelasList->map(fn ($kelas) => [
        'id' => (string) $kelas->id,
        'name' => $kelas->nama_kelas,
        'level' => $kelas->jenjang,
        'branchId' => (string) $kelas->cabang_id,
        'branch' => $kelas->cabang->nama_cabang ?? 'Cabang belum diatur',
    ])->values();
    $maxDaily = max(1, (float) $pembayaranPerHari->max());
@endphp

<div
    data-finance-report-index
    class="min-w-0 w-full space-y-5"
    x-data="{
        classes: @js($classOptions),
        branch: @js((string) request('cabang_id', '')),
        level: @js((string) request('jenjang', '')),
        classFilter: @js((string) request('kelas_id', '')),
        get availableLevels() { return [...new Set(this.classes.filter(item => !this.branch || item.branchId === this.branch).map(item => item.level))].sort(); },
        get availableClasses() { return this.classes.filter(item => (!this.branch || item.branchId === this.branch) && (!this.level || item.level === this.level)); },
        resetLevel() { this.level = ''; this.classFilter = ''; },
        resetClass() { this.classFilter = ''; }
    }"
>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="border-b border-slate-200 p-4 sm:p-5"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><i class="fas fa-sliders-h"></i></span><div><h2 class="text-lg font-extrabold text-slate-950">Filter laporan</h2><p class="mt-1 text-sm text-slate-500">Saring periode, kanal pembayaran, dan lokasi sekolah.</p></div></div></header>
        <form action="{{ route('admin.keuangan.laporan.index') }}" method="GET" class="p-4 sm:p-5">
            <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
                <label><span class="mb-1 block text-xs font-bold text-slate-600">Tahun</span><select name="tahun" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100">@for($year = date('Y'); $year >= date('Y') - 5; $year--)<option value="{{ $year }}" @selected($tahun == $year)>{{ $year }}</option>@endfor</select></label>
                <label><span class="mb-1 block text-xs font-bold text-slate-600">Bulan</span><select name="bulan" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100">@foreach($bulanList as $key => $nama)<option value="{{ $key }}" @selected($bulan == $key)>{{ $nama }}</option>@endforeach</select></label>
                <label><span class="mb-1 block text-xs font-bold text-slate-600">Metode</span><select name="metode" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"><option value="">Semua metode</option><option value="tunai" @selected(request('metode') === 'tunai')>Tunai</option><option value="transfer" @selected(request('metode') === 'transfer')>Direct Transfer</option><option value="paywuz" @selected(request('metode') === 'paywuz')>Kanal Pembayaran</option></select></label>
                <label><span class="mb-1 block text-xs font-bold text-slate-600">Cabang</span><select name="cabang_id" x-model="branch" @change="resetLevel" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"><option value="">Semua cabang</option>@foreach($cabangList as $cabang)<option value="{{ $cabang->id }}">{{ $cabang->nama_cabang }}</option>@endforeach</select></label>
                <label><span class="mb-1 block text-xs font-bold text-slate-600">Jenjang</span><select name="jenjang" x-model="level" @change="resetClass" :disabled="!branch" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none disabled:bg-slate-100 disabled:text-slate-400 focus:border-brand-500 focus:ring-2 focus:ring-brand-100"><option value="">Semua jenjang</option><template x-for="item in availableLevels" :key="item"><option :value="item" x-text="item"></option></template></select></label>
                <label><span class="mb-1 block text-xs font-bold text-slate-600">Kelas</span><select name="kelas_id" x-model="classFilter" :disabled="!level" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none disabled:bg-slate-100 disabled:text-slate-400 focus:border-brand-500 focus:ring-2 focus:ring-brand-100"><option value="">Semua kelas</option><template x-for="item in availableClasses" :key="item.id"><option :value="item.id" x-text="`${item.name} · ${item.level} · ${item.branch}`"></option></template></select></label>
            </div>
            <div class="mt-4 grid grid-cols-3 gap-2 sm:flex sm:items-center"><button type="submit" class="inline-flex min-h-10 min-w-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-xl bg-brand-600 px-2 text-[11px] font-bold text-white hover:bg-brand-700 sm:px-4 sm:text-sm"><i class="fas fa-filter"></i>Terapkan</button><a href="{{ route('admin.keuangan.laporan.index') }}" class="inline-flex min-h-10 min-w-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-xl border border-slate-300 px-2 text-[11px] font-bold text-slate-700 no-underline hover:bg-slate-50 sm:px-4 sm:text-sm"><i class="fas fa-undo"></i>Reset</a><a href="{{ route('admin.keuangan.laporan.cetak', request()->query()) }}" target="_blank" class="inline-flex min-h-10 min-w-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-xl bg-emerald-50 px-2 text-[11px] font-bold text-emerald-700 no-underline hover:bg-emerald-100 sm:ml-auto sm:px-4 sm:text-sm"><i class="fas fa-print"></i><span>Cetak<span class="hidden min-[360px]:inline"> laporan</span></span></a></div>
            @if(request('cabang_id') || request('jenjang') || request('kelas_id') || request('metode'))
                <div class="mt-4 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-4"><span class="text-xs font-bold text-slate-500">Filter aktif:</span>@if(request('metode'))<span class="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{{ $methodLabels[request('metode')] ?? ucfirst(request('metode')) }}</span>@endif @if(request('cabang_id'))@php $branchName = $cabangList->firstWhere('id', request('cabang_id'))?->nama_cabang; @endphp @if($branchName)<span class="rounded-lg bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{{ $branchName }}</span>@endif @endif @if(request('jenjang'))<span class="rounded-lg bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">{{ request('jenjang') }}</span>@endif @if(request('kelas_id'))@php $className = $kelasList->firstWhere('id', request('kelas_id'))?->nama_kelas; @endphp @if($className)<span class="rounded-lg bg-violet-50 px-2.5 py-1 text-xs font-bold text-violet-700">{{ $className }}</span>@endif @endif</div>
            @endif
        </form>
    </section>

    <section class="grid grid-cols-2 gap-3 xl:grid-cols-4">
        <article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><span class="text-[10px] font-bold uppercase tracking-wide text-slate-500">Total pembayaran</span><strong class="mt-2 block truncate text-lg tabular-nums text-slate-950 sm:text-xl">Rp {{ number_format($totalPembayaran, 0, ',', '.') }}</strong></div><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><i class="fas fa-wallet"></i></span></div><p class="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-500">{{ $bulanList[$bulan] }} {{ $tahun }}</p></article>
        <article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between gap-3"><div><span class="text-[10px] font-bold uppercase tracking-wide text-slate-500">Transaksi</span><strong class="mt-2 block text-xl text-slate-950">{{ $jumlahTransaksi }}</strong></div><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><i class="fas fa-exchange-alt"></i></span></div><p class="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-500">Pembayaran disetujui</p></article>
        <article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><span class="text-[10px] font-bold uppercase tracking-wide text-slate-500">Pembayaran tunai</span><strong class="mt-2 block truncate text-lg tabular-nums text-slate-950 sm:text-xl">Rp {{ number_format($totalTunai, 0, ',', '.') }}</strong></div><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><i class="fas fa-money-bill-wave"></i></span></div><p class="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-500">{{ $jumlahTunai }} transaksi kasir</p></article>
        <article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><span class="text-[10px] font-bold uppercase tracking-wide text-slate-500">Pembayaran daring</span><strong class="mt-2 block truncate text-lg tabular-nums text-slate-950 sm:text-xl">Rp {{ number_format($totalNonTunai, 0, ',', '.') }}</strong></div><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-cyan-50 text-cyan-700"><i class="fas fa-university"></i></span></div><p class="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-500">{{ $jumlahNonTunai }} transaksi daring</p></article>
    </section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 p-4 sm:p-5"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-50 text-cyan-700"><i class="fas fa-chart-column"></i></span><div><h2 class="text-lg font-extrabold text-slate-950">Arus kas harian</h2><p class="mt-1 text-sm text-slate-500">Perbandingan pembayaran yang disetujui setiap tanggal.</p></div></div></header><div class="overflow-x-auto p-4 sm:p-5"><div class="flex h-52 min-w-[720px] items-end gap-2 border-b border-slate-200 px-1">@foreach($pembayaranPerHari as $day => $amount)@php $height = $amount > 0 ? max(5, round(($amount / $maxDaily) * 100, 2)) : 2; @endphp<div class="group flex h-full min-w-4 flex-1 flex-col items-center justify-end" title="Tanggal {{ $day }}: Rp {{ number_format($amount, 0, ',', '.') }}"><span class="mb-1 hidden whitespace-nowrap rounded bg-slate-900 px-1.5 py-1 text-[9px] text-white group-hover:block">Rp {{ number_format($amount, 0, ',', '.') }}</span><svg viewBox="0 0 20 100" preserveAspectRatio="none" class="min-h-0 w-full flex-1 text-brand-500" aria-hidden="true"><rect x="1" y="{{ 100 - $height }}" width="18" height="{{ $height }}" rx="2" class="fill-current"></rect></svg><span class="mt-2 text-[9px] font-semibold text-slate-500">{{ $day }}</span></div>@endforeach</div></div></section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4 sm:p-5"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><i class="fas fa-receipt"></i></span><div><h2 class="text-lg font-extrabold text-slate-950">Rincian transaksi</h2><p class="mt-1 text-sm text-slate-500">Pembayaran tervalidasi pada periode terpilih.</p></div></div><span class="rounded-xl bg-brand-50 px-3 py-2 text-xs font-bold text-brand-700">{{ $pembayaran->total() }} transaksi</span></header>
        @if($pembayaran->count())
            <div class="divide-y divide-slate-100 lg:hidden">@foreach($pembayaran as $index => $payment)<article class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><strong class="block text-sm text-slate-950">{{ $payment->siswa->nama_lengkap ?? '-' }}</strong><span class="mt-1 block text-xs text-slate-500">{{ $payment->tanggal_bayar->format('d/m/Y') }} · {{ $payment->siswa->kelas->nama_kelas ?? '-' }} · {{ $payment->siswa->cabang->nama_cabang ?? '-' }}</span></div><strong class="shrink-0 text-sm tabular-nums text-slate-950">Rp {{ number_format($payment->jumlah_bayar, 0, ',', '.') }}</strong></div><div class="mt-3 flex flex-wrap items-center gap-2"><x-payment-method-badge :payment="$payment" /><span class="rounded-lg bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600">{{ $payment->kode_pembayaran }}</span><span class="text-[10px] text-slate-500">{{ $payment->validator->name ?? 'Validator -' }}</span></div></article>@endforeach</div>
            <div class="hidden overflow-x-auto lg:block"><table class="w-full table-fixed border-collapse text-left"><colgroup><col class="w-12"><col class="w-24"><col class="w-32"><col class="w-[20%]"><col class="w-[10%]"><col class="w-[18%]"><col class="w-32"><col class="w-36"><col class="w-[13%]"></colgroup><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-3 py-3 text-center">No</th><th class="px-3 py-3">Tanggal</th><th class="px-3 py-3">Kode</th><th class="px-3 py-3">Siswa</th><th class="px-3 py-3">Kelas</th><th class="px-3 py-3">Jenis tagihan</th><th class="px-3 py-3 text-right">Jumlah</th><th class="px-3 py-3 text-center">Metode</th><th class="px-3 py-3">Validator</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($pembayaran as $index => $payment)<tr class="hover:bg-slate-50"><td class="px-3 py-4 text-center text-xs text-slate-500">{{ $pembayaran->firstItem() + $index }}</td><td class="px-3 py-4 text-xs font-semibold text-slate-700">{{ $payment->tanggal_bayar->format('d/m/Y') }}</td><td class="px-3 py-4"><code class="text-[10px] font-bold text-brand-700">{{ $payment->kode_pembayaran }}</code></td><td class="px-3 py-4"><strong class="block truncate text-sm text-slate-950">{{ $payment->siswa->nama_lengkap ?? '-' }}</strong><span class="mt-1 block truncate text-xs text-slate-500">{{ $payment->siswa->nisn ?? '-' }}</span></td><td class="px-3 py-4 text-xs font-semibold text-slate-700">{{ $payment->siswa->kelas->nama_kelas ?? '-' }}</td><td class="px-3 py-4 text-xs text-slate-600">{{ $payment->tagihan ? ($jenisTagihan[$payment->tagihan->jenis_tagihan] ?? ucwords(str_replace('_', ' ', $payment->tagihan->jenis_tagihan))) : '-' }}</td><td class="px-3 py-4 text-right text-sm font-extrabold tabular-nums text-slate-950">Rp {{ number_format($payment->jumlah_bayar, 0, ',', '.') }}</td><td class="px-3 py-4 text-center"><x-payment-method-badge :payment="$payment" /></td><td class="px-3 py-4 text-xs font-semibold text-slate-700"><i class="fas fa-user-check mr-1 text-emerald-600"></i>{{ $payment->validator->name ?? '-' }}</td></tr>@endforeach</tbody><tfoot><tr class="bg-slate-50"><td colspan="6" class="px-3 py-3 text-right text-xs font-bold text-slate-600">Total halaman</td><td class="px-3 py-3 text-right text-sm font-extrabold tabular-nums text-brand-700">Rp {{ number_format($pembayaran->sum('jumlah_bayar'), 0, ',', '.') }}</td><td colspan="2"></td></tr></tfoot></table></div>
            <footer class="flex flex-col gap-3 border-t border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><span class="text-xs text-slate-500">Menampilkan {{ $pembayaran->firstItem() ?? 0 }}–{{ $pembayaran->lastItem() ?? 0 }} dari {{ $pembayaran->total() }} transaksi</span><div>{{ $pembayaran->withQueryString()->links() }}</div></footer>
        @else
            <div class="flex min-h-60 flex-col items-center justify-center p-8 text-center"><span class="flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-xl text-slate-400"><i class="fas fa-folder-open"></i></span><h3 class="mt-4 text-base font-extrabold text-slate-950">Belum ada transaksi</h3><p class="mt-1 text-sm text-slate-500">Tidak ada pembayaran disetujui pada periode dan filter ini.</p></div>
        @endif
    </section>

    <section class="grid gap-3 md:grid-cols-3"><article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span class="text-[10px] font-bold uppercase text-slate-500">Kasir (tunai)</span><strong class="mt-2 block text-lg tabular-nums text-slate-950">Rp {{ number_format($totalTunai, 0, ',', '.') }}</strong><p class="mt-1 text-xs text-slate-500">{{ $jumlahTunai }} transaksi</p></article><article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span class="text-[10px] font-bold uppercase text-slate-500">Direct Transfer</span><strong class="mt-2 block text-lg tabular-nums text-slate-950">Rp {{ number_format($totalTransfer, 0, ',', '.') }}</strong><p class="mt-1 text-xs text-slate-500">{{ $jumlahTransfer }} transaksi</p></article><article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span class="text-[10px] font-bold uppercase text-slate-500">Kanal Pembayaran</span><strong class="mt-2 block text-lg tabular-nums text-slate-950">Rp {{ number_format($totalDigital, 0, ',', '.') }}</strong><p class="mt-1 text-xs text-slate-500">{{ $jumlahDigital }} transaksi</p></article></section>
</div>
@endsection
