@extends('layouts.app')

@section('title', 'Data Tenaga Pendidik')
@section('page-title', 'Tenaga Pendidik')
@section('page-subtitle', 'Kelola pengurus, guru, wali kelas, dan staf sekolah')

@section('content')
@php $hasFilters = request()->filled('search') || request()->filled('role'); @endphp
<div class="min-w-0 space-y-5">
    @if(session('import_warnings'))<section class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900"><p class="font-extrabold"><i class="fas fa-exclamation-triangle mr-1.5" aria-hidden="true"></i>Beberapa data import dilewati</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach(session('import_warnings') as $warning)<li>{{ $warning }}</li>@endforeach</ul></section>@endif
    <section class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="border-b border-slate-200 p-4 sm:p-5"><div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div class="flex min-w-0 items-center gap-3"><a href="{{ route('admin.users.index') }}" class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600 no-underline hover:bg-slate-200"><i class="fas fa-arrow-left" aria-hidden="true"></i></a><div class="min-w-0"><h2 class="text-base font-extrabold text-slate-900">Daftar Tenaga Pendidik</h2><p class="mt-1 text-xs text-slate-500">{{ $tenagaPendidik->total() }} akun ditemukan</p></div></div><div class="grid grid-cols-4 gap-2 sm:flex"><a href="{{ route('admin.users.tenaga-pendidik.print') }}?{{ http_build_query(request()->all()) }}" target="_blank" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-100 px-3 text-xs font-bold text-slate-700 no-underline" title="Cetak"><i class="fas fa-print" aria-hidden="true"></i><span class="hidden sm:inline">Cetak</span></a><a href="{{ route('admin.users.tenaga-pendidik-template') }}" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-cyan-50 px-3 text-xs font-bold text-cyan-700 no-underline" title="Template"><i class="fas fa-download" aria-hidden="true"></i><span class="hidden sm:inline">Template</span></a><a href="{{ route('admin.users.import-tenaga-pendidik') }}" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-emerald-50 px-3 text-xs font-bold text-emerald-700 no-underline" title="Import"><i class="fas fa-file-import" aria-hidden="true"></i><span class="hidden sm:inline">Import</span></a><a href="{{ route('admin.users.create-tenaga-pendidik') }}" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-brand-600 px-3 text-xs font-bold text-white no-underline"><i class="fas fa-plus" aria-hidden="true"></i><span class="hidden sm:inline">Tambah</span></a></div></div>
            <form action="{{ route('admin.users.tenaga-pendidik') }}" method="GET" class="mt-4 grid gap-2 sm:grid-cols-[minmax(240px,1fr)_220px_auto]"><label class="relative"><span class="sr-only">Cari tenaga pendidik</span><i class="fas fa-search pointer-events-none absolute left-3 top-3.5 text-xs text-slate-400" aria-hidden="true"></i><input type="search" name="search" value="{{ request('search') }}" placeholder="Nama, username, email, atau NIP..." class="h-10 w-full rounded-xl border border-slate-200 !pl-10 pr-3 text-xs outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20"></label><select name="role" data-auto-submit class="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs text-slate-700"><option value="">Semua Jabatan</option>@foreach($roles as $roleKey => $roleLabel)<option value="{{ $roleKey }}" {{ request('role') === $roleKey ? 'selected' : '' }}>{{ $roleLabel }}</option>@endforeach</select><div class="flex gap-2"><button type="submit" class="inline-flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-slate-800 px-4 text-xs font-bold text-white"><i class="fas fa-search" aria-hidden="true"></i>Cari</button>@if($hasFilters)<a href="{{ route('admin.users.tenaga-pendidik') }}" class="inline-flex h-10 items-center justify-center rounded-xl bg-red-50 px-3 text-red-700 no-underline"><i class="fas fa-times" aria-hidden="true"></i></a>@endif</div></form></header>

        <div class="flex items-center justify-between gap-3 border-b border-slate-100 bg-slate-50 px-4 py-2.5"><label class="flex cursor-pointer items-center gap-2 text-[11px] font-bold text-slate-600"><input type="checkbox" data-bulk-select-all="teacher-bulk-form" class="h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-500">Pilih semua halaman ini</label><form id="teacher-bulk-form" action="{{ route('admin.users.bulk-delete-tenaga-pendidik') }}" method="POST" data-confirm data-confirm-title="Hapus akun terpilih?" data-confirm-message="Akun yang masih memiliki data terkait akan dilewati." data-confirm-text="Ya, hapus data">@csrf<button type="submit" data-bulk-submit="teacher-bulk-form" disabled class="inline-flex h-8 items-center justify-center gap-1.5 rounded-lg bg-red-600 px-3 text-[10px] font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><i class="fas fa-trash" aria-hidden="true"></i>Hapus (<span data-bulk-count>0</span>)</button></form></div>

        <div class="divide-y divide-slate-100 md:hidden">@forelse($tenagaPendidik as $tp)<article class="p-4"><div class="flex items-start gap-3"><input type="checkbox" name="ids[]" value="{{ $tp->id }}" form="teacher-bulk-form" data-bulk-item class="mt-1 h-4 w-4 shrink-0 rounded border-slate-300 text-brand-600"><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><h3 class="truncate text-sm font-extrabold text-slate-900">{{ $tp->name }}</h3><p class="mt-1 truncate text-[11px] text-slate-500">{{ $tp->email }}</p></div><span class="rounded-full px-2.5 py-1 text-[9px] font-bold {{ $tp->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $tp->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><div class="mt-3 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-[11px]"><div><p class="text-slate-400">Jabatan</p><p class="mt-0.5 truncate font-semibold text-slate-700">{{ $roles[$tp->role] ?? ucwords(str_replace('_', ' ', $tp->role)) }}</p></div><div><p class="text-slate-400">NIP / Telepon</p><p class="mt-0.5 truncate font-semibold text-slate-700">{{ $tp->tenagaPendidik->nip ?? '-' }} · {{ $tp->tenagaPendidik->telepon ?? $tp->phone ?? '-' }}</p></div></div><div class="mt-3 grid grid-cols-3 gap-2"><a href="{{ route('admin.users.show-tenaga-pendidik', $tp->id) }}" class="inline-flex h-9 items-center justify-center gap-1 rounded-lg bg-blue-50 text-xs font-bold text-blue-700 no-underline"><i class="fas fa-eye" aria-hidden="true"></i>Detail</a><a href="{{ route('admin.users.edit-tenaga-pendidik', $tp->id) }}" class="inline-flex h-9 items-center justify-center gap-1 rounded-lg bg-amber-50 text-xs font-bold text-amber-700 no-underline"><i class="fas fa-edit" aria-hidden="true"></i>Edit</a><form action="{{ route('admin.users.delete-tenaga-pendidik', $tp->id) }}" method="POST" data-confirm data-confirm-title="Hapus tenaga pendidik?" data-confirm-message="{{ $tp->name }} dan akun loginnya akan dihapus." data-confirm-text="Ya, hapus">@csrf @method('DELETE')<button type="submit" class="h-9 w-full rounded-lg bg-red-50 text-xs font-bold text-red-700"><i class="fas fa-trash mr-1" aria-hidden="true"></i>Hapus</button></form></div></div></div></article>@empty<div class="p-12 text-center text-xs text-slate-500"><i class="fas fa-chalkboard-teacher mb-3 block text-3xl text-slate-300" aria-hidden="true"></i>{{ $hasFilters ? 'Tidak ada data yang sesuai filter.' : 'Belum ada tenaga pendidik.' }}</div>@endforelse</div>

        @if($tenagaPendidik->isNotEmpty())<div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3"></th><th class="px-4 py-3">No</th><th class="px-4 py-3">Nama</th><th class="px-4 py-3">NIP</th><th class="px-4 py-3">Jabatan</th><th class="px-4 py-3">Email</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($tenagaPendidik as $index => $tp)<tr class="hover:bg-slate-50/80"><td class="px-4 py-3"><input type="checkbox" name="ids[]" value="{{ $tp->id }}" form="teacher-bulk-form" data-bulk-item class="h-4 w-4 rounded border-slate-300 text-brand-600"></td><td class="px-4 py-3 text-xs text-slate-400">{{ $tenagaPendidik->firstItem() + $index }}</td><td class="max-w-xs px-4 py-3"><p class="truncate font-bold text-slate-800">{{ $tp->name }}</p><p class="mt-0.5 text-[11px] text-slate-500">{{ $tp->tenagaPendidik->telepon ?? $tp->phone ?? '-' }}</p></td><td class="px-4 py-3 text-xs text-slate-600">{{ $tp->tenagaPendidik->nip ?? '-' }}</td><td class="px-4 py-3"><span class="rounded-full bg-violet-50 px-2.5 py-1 text-[9px] font-bold text-violet-700">{{ $roles[$tp->role] ?? ucwords(str_replace('_', ' ', $tp->role)) }}</span></td><td class="max-w-[210px] px-4 py-3 text-xs text-slate-600"><p class="truncate">{{ $tp->email }}</p></td><td class="px-4 py-3"><span class="rounded-full px-2.5 py-1 text-[9px] font-bold {{ $tp->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $tp->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="px-4 py-3"><div class="flex justify-end gap-1.5"><x-cleanflow.table-action href="{{ route('admin.users.show-tenaga-pendidik', $tp->id) }}" tone="view" icon="fas fa-eye" label="Detail tenaga pendidik" /><x-cleanflow.table-action href="{{ route('admin.users.edit-tenaga-pendidik', $tp->id) }}" tone="edit" icon="fas fa-edit" label="Edit tenaga pendidik" /><form action="{{ route('admin.users.delete-tenaga-pendidik', $tp->id) }}" method="POST" data-confirm data-confirm-title="Hapus tenaga pendidik?" data-confirm-message="{{ $tp->name }} dan akun loginnya akan dihapus." data-confirm-text="Ya, hapus">@csrf @method('DELETE')<x-cleanflow.table-action type="submit" tone="delete" icon="fas fa-trash" label="Hapus tenaga pendidik" /></form></div></td></tr>@endforeach</tbody></table></div>@endif
        @if($tenagaPendidik->hasPages())<footer class="border-t border-slate-200 px-4 py-3">{{ $tenagaPendidik->appends(request()->only(['search', 'role']))->links() }}</footer>@endif
    </section>
</div>
@endsection
