@extends('layouts.app')

@section('title', 'Pengaturan Kenaikan Kelas')
@section('page-title', 'Pengaturan Kenaikan Kelas')
@section('page-subtitle', 'Tentukan ambang akademik dan jadwal proses otomatis')

@section('content')
@php
    $routePrefix = request()->routeIs('waka.*') ? 'waka.kenaikan-kelas' : 'admin.akademik.kenaikan-kelas';
    $tahunLabel = $tahun->nama_tahun_ajaran ?? $tahun->nama ?? $tahun->tahun_ajaran ?? '-';
    $tanggalRapor = old('tanggal_pengambilan_rapor', $setting && $setting->tanggal_pengambilan_rapor ? \Carbon\Carbon::parse($setting->tanggal_pengambilan_rapor)->format('Y-m-d') : '');
    $tanggalEksekusi = old('tanggal_eksekusi', $setting && $setting->tanggal_eksekusi ? \Carbon\Carbon::parse($setting->tanggal_eksekusi)->format('Y-m-d') : '');
    $waktuEksekusi = old('waktu_eksekusi', $setting && $setting->tanggal_eksekusi ? \Carbon\Carbon::parse($setting->tanggal_eksekusi)->format('H:i') : '02:00');
    $minimalTuntas = old('persentase_minimal_tuntas', $setting->persentase_minimal_tuntas ?? 70);
    $inputClass = 'mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400';
@endphp

<div class="min-w-0 w-full space-y-5">
    @if(!$promotionReadiness['hasNextTA'])
        <section class="flex items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-900"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-red-100 text-red-600"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i></span><div class="min-w-0"><h2 class="font-extrabold">Tahun ajaran berikutnya belum dibuat</h2><p class="mt-1 text-xs leading-5 text-red-700">Jadwal otomatis baru dapat diaktifkan setelah tahun ajaran tujuan tersedia.</p><a href="{{ route('admin.tahun-ajaran.create') }}" class="mt-2 inline-flex items-center gap-1 text-xs font-extrabold text-red-800 no-underline hover:underline">Buat Tahun Ajaran <i class="fas fa-arrow-right" aria-hidden="true"></i></a></div></section>
    @elseif($promotionReadiness['kelasBaruCount'] == 0)
        <section class="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-600"><i class="fas fa-exclamation-circle" aria-hidden="true"></i></span><div class="min-w-0"><h2 class="font-extrabold">Kelas tujuan belum dibuat</h2><p class="mt-1 text-xs leading-5 text-amber-700">Tambahkan kelas pada tahun ajaran {{ $promotionReadiness['nextTA']->nama_tahun_ajaran }} sebelum mengaktifkan jadwal otomatis.</p><a href="{{ route('admin.kelas.index') }}" class="mt-2 inline-flex items-center gap-1 text-xs font-extrabold text-amber-800 no-underline hover:underline">Kelola Kelas <i class="fas fa-arrow-right" aria-hidden="true"></i></a></div></section>
    @else
        <section class="flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-100 text-emerald-600"><i class="fas fa-circle-check" aria-hidden="true"></i></span><div><h2 class="text-sm font-extrabold text-emerald-900">Tujuan kenaikan kelas siap</h2><p class="mt-1 text-xs text-emerald-700">{{ $promotionReadiness['nextTA']->nama_tahun_ajaran }} memiliki {{ $promotionReadiness['kelasBaruCount'] }} kelas tujuan.</p></div></section>
    @endif

    @if($errors->any())<section class="rounded-2xl border border-red-200 bg-red-50 p-4 text-xs text-red-800"><p class="font-extrabold">Periksa kembali pengaturan berikut:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif

    <div class="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
        <form action="{{ route($routePrefix . '.settings.store') }}" method="POST" class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            @csrf
            <input type="hidden" name="tahun_ajaran_id" value="{{ $tahun->id }}">
            <header class="border-b border-slate-200 p-4 sm:p-5"><h2 class="flex items-center gap-2 text-base font-extrabold text-slate-900"><i class="fas fa-sliders text-brand-600" aria-hidden="true"></i>Konfigurasi utama</h2><p class="mt-1 text-xs text-slate-500">Digunakan oleh simulasi, eksekusi manual, dan jadwal otomatis.</p></header>
            <div class="grid gap-5 p-4 sm:p-5">
                <label class="block text-xs font-bold text-slate-700">Tahun ajaran aktif<input type="text" value="{{ $tahunLabel }}" disabled class="{{ $inputClass }}"></label>
                <label class="block text-xs font-bold text-slate-700 sm:max-w-md">Tanggal pembagian rapor <span class="text-red-500">*</span><input type="date" name="tanggal_pengambilan_rapor" value="{{ $tanggalRapor }}" required class="{{ $inputClass }} @error('tanggal_pengambilan_rapor') !border-red-400 @enderror"><span class="mt-1.5 block text-[11px] font-normal text-slate-500">Tanggal resmi rapor diterima siswa.</span>@error('tanggal_pengambilan_rapor')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label>
                <fieldset class="rounded-2xl border border-slate-200 bg-slate-50 p-4"><legend class="px-1 text-xs font-extrabold text-slate-800">Jadwal eksekusi otomatis</legend><div class="mt-1 grid gap-4 sm:grid-cols-2"><label class="block text-xs font-bold text-slate-700">Tanggal<input type="date" name="tanggal_eksekusi" value="{{ $tanggalEksekusi }}" {{ $promotionReadiness['isReady'] ? '' : 'disabled' }} class="{{ $inputClass }} @error('tanggal_eksekusi') !border-red-400 @enderror">@error('tanggal_eksekusi')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label><label class="block text-xs font-bold text-slate-700">Waktu (WIB)<input type="time" name="waktu_eksekusi" value="{{ $waktuEksekusi }}" {{ $promotionReadiness['isReady'] ? '' : 'disabled' }} class="{{ $inputClass }} @error('waktu_eksekusi') !border-red-400 @enderror">@error('waktu_eksekusi')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label></div><p class="mt-3 text-[11px] leading-5 {{ $promotionReadiness['isReady'] ? 'text-slate-500' : 'font-semibold text-red-600' }}">{{ $promotionReadiness['isReady'] ? 'Kosongkan tanggal jika proses hanya akan dijalankan manual.' : 'Dinonaktifkan sampai tahun ajaran dan kelas tujuan siap. Jadwal lama yang tersimpan tidak akan terhapus.' }}</p></fieldset>
                <label class="block text-xs font-bold text-slate-700 sm:max-w-md">Persentase minimal tuntas <span class="text-red-500">*</span><span class="relative mt-1.5 block"><input type="number" name="persentase_minimal_tuntas" value="{{ $minimalTuntas }}" min="0" max="100" required class="h-11 w-full rounded-xl border border-slate-200 bg-white pl-3 pr-10 text-sm text-slate-800 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 @error('persentase_minimal_tuntas') !border-red-400 @enderror"><span class="pointer-events-none absolute right-3 top-3 text-sm font-bold text-slate-400">%</span></span><span class="mt-1.5 block text-[11px] font-normal leading-5 text-slate-500">Persentase mata pelajaran yang harus memenuhi KKM agar siswa tuntas secara akademik.</span>@error('persentase_minimal_tuntas')<span class="mt-1 block text-[11px] font-semibold text-red-600">{{ $message }}</span>@enderror</label>
            </div>
            <footer class="flex justify-end border-t border-slate-200 bg-slate-50/70 p-4"><button type="submit" class="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-brand-600 px-5 text-xs font-bold text-white hover:bg-brand-700 sm:w-auto"><i class="fas fa-save" aria-hidden="true"></i>Simpan pengaturan</button></footer>
        </form>

        <aside class="h-fit overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:sticky xl:top-24"><header class="border-b border-slate-200 p-4 sm:p-5"><h2 class="flex items-center gap-2 text-sm font-extrabold text-slate-900"><i class="fas fa-circle-info text-brand-600" aria-hidden="true"></i>Syarat yang diperiksa</h2></header><div class="space-y-3 p-4 sm:p-5">@foreach([['icon'=>'fas fa-wallet','title'=>'Keuangan','text'=>'Tagihan lunas atau memiliki dispensasi yang sah.','tone'=>'bg-emerald-50 text-emerald-600'],['icon'=>'fas fa-graduation-cap','title'=>'Akademik','text'=>'Nilai mata pelajaran memenuhi ambang ketuntasan.','tone'=>'bg-brand-50 text-brand-600'],['icon'=>'fas fa-bullseye','title'=>'KKM','text'=>'KKM harus tersedia sebelum simulasi akhir dijalankan.','tone'=>'bg-amber-50 text-amber-600']] as $item)<div class="flex gap-3 rounded-xl bg-slate-50 p-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg {{ $item['tone'] }}"><i class="{{ $item['icon'] }}" aria-hidden="true"></i></span><div><h3 class="text-xs font-extrabold text-slate-800">{{ $item['title'] }}</h3><p class="mt-1 text-[11px] leading-5 text-slate-500">{{ $item['text'] }}</p></div></div>@endforeach<a href="{{ route($routePrefix . '.kkm.index') }}" class="inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-brand-50 px-4 text-xs font-bold text-brand-700 no-underline hover:bg-brand-100"><i class="fas fa-sliders" aria-hidden="true"></i>Buka Pengaturan KKM</a></div></aside>
    </div>
</div>
@endsection
