@extends('layouts.app')

@section('title', 'Riwayat Pembayaran Siswa')
@section('page-title', 'Riwayat Pembayaran')
@section('page-subtitle', 'Jejak transaksi dan posisi tagihan siswa')

@section('content')
@php
    $isBendahara = request()->routeIs('bendahara.*');
    $pembayaranRoute = $isBendahara ? 'bendahara.pembayaran' : 'admin.keuangan.pembayaran';
    $tagihanRoute = $isBendahara ? 'bendahara.tagihan' : 'admin.keuangan.tagihan';
@endphp
<div class="min-w-0 w-full space-y-5" data-payment-history>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5">
            <div class="flex min-w-0 items-center gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-sm font-extrabold text-brand-700">{{ strtoupper(substr($siswa->nama_lengkap, 0, 1)) }}</span><div class="min-w-0"><p class="text-[10px] font-bold uppercase tracking-wide text-brand-600">Riwayat siswa</p><h2 class="truncate text-lg font-extrabold text-slate-950" title="{{ $siswa->nama_lengkap }}">{{ $siswa->nama_lengkap }}</h2><p class="mt-0.5 truncate text-xs text-slate-500">{{ $siswa->nisn ?: 'NISN belum tersedia' }}</p></div></div>
            <div class="grid grid-cols-2 gap-2 sm:flex"><a href="{{ route($tagihanRoute.'.show', $siswa->id) }}" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 text-xs font-bold text-slate-700 no-underline hover:bg-slate-200"><i class="fas fa-arrow-left" aria-hidden="true"></i>Kembali</a><a href="{{ route($pembayaranRoute.'.create', $siswa->id) }}" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 text-xs font-bold text-white no-underline hover:bg-brand-700"><i class="fas fa-plus" aria-hidden="true"></i>Input pembayaran</a></div>
        </div>
        <dl class="grid border-t border-slate-200 text-xs sm:grid-cols-3"><div class="border-slate-200 p-4 sm:border-r"><dt class="text-[9px] font-bold uppercase tracking-wide text-slate-400">Kelas</dt><dd class="mt-1 font-extrabold text-slate-800">{{ $siswa->kelas->nama_kelas ?? '-' }} <span class="font-semibold text-slate-500">{{ $siswa->kelas->jenjang ?? '' }}</span></dd></div><div class="border-slate-200 p-4 sm:border-r"><dt class="text-[9px] font-bold uppercase tracking-wide text-slate-400">Cabang</dt><dd class="mt-1 break-words font-extrabold text-slate-800">{{ $siswa->cabang->nama_cabang ?? '-' }}</dd></div><div class="p-4"><dt class="text-[9px] font-bold uppercase tracking-wide text-slate-400">Tahun ajaran aktif</dt><dd class="mt-1 font-extrabold text-slate-800">{{ $tahunAjaran->nama_tahun_ajaran ?? 'Belum ditetapkan' }}</dd></div></dl>
    </section>

    <section class="grid grid-cols-2 gap-3 xl:grid-cols-4">
        @foreach([
            ['Total tagihan', $totalTagihan, 'Seluruh nominal tagihan', 'fa-file-invoice-dollar', 'bg-brand-50 text-brand-600'],
            ['Total terbayar', $totalTerbayar, 'Pembayaran disetujui', 'fa-circle-check', 'bg-emerald-50 text-emerald-600'],
            ['Menunggu', $totalPending, 'Belum selesai divalidasi', 'fa-hourglass-half', 'bg-amber-50 text-amber-600'],
            ['Sisa tagihan', $sisaTagihan, 'Nominal belum terbayar', 'fa-money-bill-wave', 'bg-red-50 text-red-600'],
        ] as [$label, $value, $description, $icon, $tone])
            <article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><p class="truncate text-base font-extrabold text-slate-950 sm:text-lg" title="Rp {{ number_format($value, 0, ',', '.') }}">Rp {{ number_format($value, 0, ',', '.') }}</p><p class="mt-1 truncate text-[10px] font-bold uppercase tracking-wide text-slate-500">{{ $label }}</p></div><span class="hidden h-10 w-10 shrink-0 items-center justify-center rounded-xl sm:flex {{ $tone }}"><i class="fas {{ $icon }}" aria-hidden="true"></i></span></div><p class="mt-3 truncate border-t border-slate-100 pt-3 text-[11px] text-slate-500">{{ $description }}</p></article>
        @endforeach
    </section>

    <section class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="border-b border-slate-200 p-4 sm:p-5"><h2 class="flex items-center gap-2 text-base font-extrabold text-slate-950"><i class="fas fa-receipt text-brand-600" aria-hidden="true"></i>Daftar transaksi pembayaran</h2><p class="mt-1 text-xs text-slate-500">{{ number_format($pembayaran->total()) }} transaksi tercatat untuk siswa ini.</p></header>

        @if($pembayaran->isEmpty())
            <div class="px-5 py-14 text-center text-sm text-slate-500"><i class="fas fa-receipt mb-3 block text-4xl text-slate-300" aria-hidden="true"></i>Belum ada riwayat pembayaran.</div>
        @else
            <div class="divide-y divide-slate-100 lg:hidden">
                @foreach($pembayaran as $bayar)
                    <article class="p-4"><div class="flex min-w-0 items-start justify-between gap-3"><div class="min-w-0"><code class="block truncate font-mono text-[11px] font-bold text-brand-700">{{ $bayar->kode_pembayaran }}</code><p class="mt-1 break-words text-sm font-extrabold text-slate-900">{{ $bayar->tagihan ? ($jenisTagihan[$bayar->tagihan->jenis_tagihan] ?? ucwords(str_replace('_', ' ', $bayar->tagihan->jenis_tagihan))) : '-' }}</p></div><x-payment-status-badge :payment="$bayar" class="shrink-0 text-[9px]" /></div><dl class="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-xs"><div><dt class="text-[9px] font-bold uppercase text-slate-400">Jumlah</dt><dd class="mt-1 whitespace-nowrap font-extrabold text-slate-900">Rp {{ number_format($bayar->jumlah_bayar, 0, ',', '.') }}</dd></div><div><dt class="text-[9px] font-bold uppercase text-slate-400">Tanggal</dt><dd class="mt-1 whitespace-nowrap font-bold text-slate-700">{{ $bayar->tanggal_bayar?->format('d/m/Y') ?? '-' }}</dd></div><div class="col-span-2"><dt class="text-[9px] font-bold uppercase text-slate-400">Metode</dt><dd class="mt-1"><x-payment-method-badge :payment="$bayar" /></dd></div>@if($bayar->tanggal_validasi)<div class="col-span-2"><dt class="text-[9px] font-bold uppercase text-slate-400">Divalidasi</dt><dd class="mt-1 text-slate-600">{{ $bayar->tanggal_validasi->format('d/m/Y H:i') }} oleh {{ $bayar->validator->name ?? '-' }}</dd></div>@endif</dl><div class="mt-3 grid {{ $bayar->status_validasi === 'disetujui' ? 'grid-cols-2' : 'grid-cols-1' }} gap-2"><a href="{{ route($pembayaranRoute.'.show', $bayar->id) }}" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-blue-50 text-xs font-bold text-blue-700 no-underline ring-1 ring-inset ring-blue-100"><i class="fas fa-eye" aria-hidden="true"></i>Detail</a>@if($bayar->status_validasi === 'disetujui')<a href="{{ route($pembayaranRoute.'.cetak-kwitansi', $bayar->id) }}" target="_blank" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-emerald-50 text-xs font-bold text-emerald-700 no-underline ring-1 ring-inset ring-emerald-100"><i class="fas fa-print" aria-hidden="true"></i>Cetak kwitansi</a>@endif</div></article>
                @endforeach
            </div>

            <div class="hidden overflow-x-auto lg:block"><table class="w-full min-w-[980px] table-fixed text-left text-xs"><colgroup><col class="w-44"><col class="w-28"><col><col class="w-36"><col class="w-44"><col class="w-40"><col class="w-44"><col class="w-28"></colgroup><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Kode</th><th class="px-3 py-3">Tanggal</th><th class="px-3 py-3">Jenis tagihan</th><th class="px-3 py-3 text-right">Jumlah</th><th class="px-3 py-3">Metode</th><th class="px-3 py-3">Status</th><th class="px-3 py-3">Divalidasi</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                @foreach($pembayaran as $bayar)<tr class="hover:bg-slate-50/70"><td class="px-4 py-4"><code class="block truncate font-mono text-[11px] font-bold text-brand-700" title="{{ $bayar->kode_pembayaran }}">{{ $bayar->kode_pembayaran }}</code>@if($bayar->order_id && $bayar->group_transactions_count > 1)<span class="mt-1 inline-flex whitespace-nowrap rounded-full bg-violet-50 px-2 py-1 text-[9px] font-bold text-violet-700"><i class="fas fa-layer-group mr-1" aria-hidden="true"></i>{{ $bayar->group_transactions_count }} item</span>@endif</td><td class="whitespace-nowrap px-3 py-4 font-semibold text-slate-600">{{ $bayar->tanggal_bayar?->format('d/m/Y') ?? '-' }}</td><td class="px-3 py-4"><p class="line-clamp-2 font-bold leading-5 text-slate-800">{{ $bayar->tagihan ? ($jenisTagihan[$bayar->tagihan->jenis_tagihan] ?? ucwords(str_replace('_', ' ', $bayar->tagihan->jenis_tagihan))) : '-' }}</p></td><td class="whitespace-nowrap px-3 py-4 text-right font-extrabold text-slate-900">Rp {{ number_format($bayar->jumlah_bayar, 0, ',', '.') }}</td><td class="px-3 py-4"><x-payment-method-badge :payment="$bayar" /></td><td class="px-3 py-4"><x-payment-status-badge :payment="$bayar" /></td><td class="px-3 py-4">@if($bayar->tanggal_validasi)<p class="whitespace-nowrap font-semibold text-slate-700">{{ $bayar->tanggal_validasi->format('d/m/Y H:i') }}</p><p class="mt-1 truncate text-[10px] text-slate-400">{{ $bayar->validator->name ?? '-' }}</p>@else<span class="text-slate-400">—</span>@endif</td><td class="px-4 py-4"><div class="flex justify-end gap-1.5"><x-cleanflow.table-action href="{{ route($pembayaranRoute.'.show', $bayar->id) }}" tone="view" icon="fas fa-eye" label="Detail pembayaran" />@if($bayar->status_validasi === 'disetujui')<x-cleanflow.table-action href="{{ route($pembayaranRoute.'.cetak-kwitansi', $bayar->id) }}" tone="success" icon="fas fa-print" label="Cetak kwitansi" target="_blank" />@endif</div></td></tr>@endforeach
            </tbody></table></div>
            @if($pembayaran->hasPages())<footer class="border-t border-slate-200 px-4 py-3 sm:px-5">{{ $pembayaran->links() }}</footer>@endif
        @endif
    </section>

    @if($pembayaran->isNotEmpty())
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 p-4 sm:p-5"><h2 class="flex items-center gap-2 text-base font-extrabold text-slate-950"><i class="fas fa-clock-rotate-left text-emerald-600" aria-hidden="true"></i>Aktivitas pembayaran terbaru</h2><p class="mt-1 text-xs text-slate-500">Maksimal 10 transaksi dari halaman yang sedang dilihat.</p></header><ol class="divide-y divide-slate-100">@foreach($pembayaran->take(10) as $bayar)<li class="flex gap-3 px-4 py-4 sm:px-5"><span class="mt-1 h-3 w-3 shrink-0 rounded-full {{ $bayar->status_validasi === 'disetujui' ? 'bg-emerald-500' : ($bayar->status_validasi === 'ditolak' ? 'bg-red-500' : 'bg-amber-500') }} ring-4 ring-slate-100"></span><div class="min-w-0 flex-1"><div class="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p class="font-extrabold text-slate-900">Rp {{ number_format($bayar->jumlah_bayar, 0, ',', '.') }} <span class="font-medium text-slate-500">via {{ $bayar->payment_channel_label }}</span></p><time class="shrink-0 text-[11px] text-slate-500">{{ $bayar->tanggal_bayar?->format('d M Y') ?? '-' }}</time></div>@if($bayar->tagihan)<p class="mt-1 truncate text-xs text-slate-500">{{ $jenisTagihan[$bayar->tagihan->jenis_tagihan] ?? ucwords(str_replace('_', ' ', $bayar->tagihan->jenis_tagihan)) }}</p>@endif</div></li>@endforeach</ol></section>
    @endif
</div>
@endsection
