<dialog x-ref="noteDialog" class="m-auto w-[calc(100%-2rem)] max-w-xl overflow-hidden rounded-2xl bg-white p-0 shadow-2xl backdrop:bg-slate-950/60" @click.self="$el.close()" @close="submittingNote = false">
    <form method="POST" action="{{ route($baseRoute.'.catatan') }}" @submit="submittingNote = true">
        @csrf
        <input type="hidden" name="konten_type" :value="note.type">
        <input type="hidden" name="konten_id" :value="note.id">
        <header class="flex items-start justify-between gap-4 border-b border-slate-200 p-4 sm:p-5"><div class="min-w-0"><p class="text-[10px] font-bold uppercase tracking-wide text-brand-600">Catatan monitoring</p><h2 class="mt-1 flex items-center gap-2 text-base font-extrabold text-slate-950"><i class="fas fa-comment-dots text-brand-600" aria-hidden="true"></i>Kirim catatan untuk guru</h2><p class="mt-1 truncate text-xs text-slate-500" x-text="note.title ? `${note.label}: ${note.title}` : 'Pilih konten yang ingin diberi catatan'"></p></div><button type="button" @click="$refs.noteDialog.close()" class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-500 hover:bg-slate-200" aria-label="Tutup dialog"><i class="fas fa-xmark" aria-hidden="true"></i></button></header>
        <div class="space-y-4 p-4 sm:p-5">
            <div class="flex items-start gap-3 rounded-xl border border-blue-100 bg-blue-50 p-3 text-xs leading-5 text-blue-800"><i class="fas fa-circle-info mt-0.5 shrink-0 text-blue-600" aria-hidden="true"></i><p>Catatan dikirim sebagai notifikasi kepada guru pembuat konten. Tuliskan masalah dan perbaikan yang diharapkan secara jelas.</p></div>
            <label class="block"><span class="text-xs font-bold text-slate-700">Isi catatan atau revisi <span class="text-red-600">*</span></span><textarea name="isi_catatan" x-model="noteText" rows="6" minlength="5" maxlength="5000" required class="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm leading-6 text-slate-900 outline-none placeholder:text-slate-400 focus:border-brand-500 focus:ring-2 focus:ring-brand-100" placeholder="Contoh: materi perlu dilengkapi tujuan pembelajaran dan sumber referensi."></textarea><span class="mt-1.5 flex justify-between text-[10px] text-slate-400"><span>Minimal 5 karakter</span><span><span x-text="noteText.length"></span>/5000</span></span></label>
        </div>
        <footer class="flex justify-end gap-2 border-t border-slate-200 bg-slate-50 p-4"><button type="button" @click="$refs.noteDialog.close()" class="h-10 rounded-xl px-4 text-xs font-bold text-slate-600 hover:bg-slate-200">Batal</button><button type="submit" :disabled="submittingNote || noteText.trim().length < 5" class="inline-flex h-10 items-center gap-2 rounded-xl bg-brand-600 px-4 text-xs font-bold text-white hover:bg-brand-700 disabled:cursor-not-allowed disabled:bg-slate-300"><i class="fas" :class="submittingNote ? 'fa-spinner fa-spin' : 'fa-paper-plane'" aria-hidden="true"></i><span x-text="submittingNote ? 'Mengirim...' : 'Kirim catatan'"></span></button></footer>
    </form>
</dialog>
